### PR TITLE
Fix STJ source gen missing type parameter constraints on generic accessor wrappers

### PR DESCRIPTION
**Pull request by eiriktsarpalis**
> [!NOTE]
> This PR was generated with the assistance of GitHub Copilot.

## Description

Fixes the aspnetcore build failure reported in https://github.com/dotnet/dotnet/pull/5880#issuecomment-4182510988, caused by https://github.com/dotnet/runtime/pull/124650.

When the STJ source generator emits `UnsafeAccessor` wrapper classes for generic types (e.g., `__GenericAccessors_MyType<T>`), it was not propagating type parameter constraints from the original type definition. This caused **CS0314** compilation errors in downstream consumers (aspnetcore) when the type parameter had constraints like `where TResponse : notnull, AuthenticatorResponse`.

### Before (broken)
```csharp
private static class __GenericAccessors_...<TResponse>  // missing constraint!
{
    [UnsafeAccessor(...)]
    public static extern ... __get_...(PublicKeyCredential<TResponse> obj);  // CS0314
}
```

### After (fixed)
```csharp
private static class __GenericAccessors_...<TResponse> where TResponse : notnull, global::...AuthenticatorResponse
{
    [UnsafeAccessor(...)]
    public static extern ... __get_...(PublicKeyCredential<TResponse> obj);  // OK
}
```

## Changes

- **`PropertyGenerationSpec.cs`** — Added `DeclaringTypeParameterConstraintClauses` property to store constraint clauses
- **`JsonSourceGenerator.Parser.cs`** — Added `GetTypeParameterConstraintClause()` and `GetTypeParameterConstraintsCombined()` to extract all constraint kinds (`struct`, `class`, `notnull`, `unmanaged`, base types, interfaces, `new()`) from `ITypeParameterSymbol`
- **`JsonSourceGenerator.Emitter.cs`** — Appends constraint clauses to the generic wrapper class declaration

## Tests

- **Unit test**: `GenericTypeWithConstrainedTypeParameters_InitOnlyProperties` — verifies source gen compiles for constrained generic types
- **Runtime test**: `InitOnlyProperties_GenericTypeWithConstraints_CanRoundtrip` — verifies serialization/deserialization end-to-end for a generic type with `where T : notnull, BaseClass` constraints
- All 194 source gen unit tests pass
- All 378 PropertyVisibility runtime tests pass

### CODE REVIEW

File: src/libraries/System.Text.Json/gen/JsonSourceGenerator.Parser.cs [hunk 1]
```diff
@@ -2188,6 +2196,81 @@ void AddTypeIfNotNull(ITypeSymbol? type)
                 }
             }
 
+            /// <summary>
+            /// Builds a <c>where T : ...</c> constraint clause string for the specified type parameter,
+            /// or returns null if the type parameter has no constraints.
+            /// </summary>
+            private static string? GetTypeParameterConstraintClause(ITypeParameterSymbol typeParameter)
```
Comment (stephentoub) [inline src/libraries/System.Text.Json/gen/JsonSourceGenerator.Parser.cs]: There's nothing built in to roslyn that supports emitting this? It feels very fragile to need to reconstruct the constraint string, especially since it'll be almost guaranteed to break if/when C# adds more.

Comment (eiriktsarpalis) [reply src/libraries/System.Text.Json/gen/JsonSourceGenerator.Parser.cs]: cc @dotnet/roslyn

Comment (eiriktsarpalis) [reply src/libraries/System.Text.Json/gen/JsonSourceGenerator.Parser.cs]: Seems Copilot had the solution ready for us: https://github.com/dotnet/runtime/pull/126507/changes/a04c4845135c7a1779e42acd050b36e5d9272518

**Review by stephentoub — APPROVED** [review]
