### ISSUE TITLE
IDE Warnings not reported with 9.0.101

### ISSUE THREAD

**Issue by danstur** [dotnet/runtime#110673]
### Description

It seems that 9.0.101 has introduced a regression compared to 9.0.100. IDEXXX warning such as unused variables, usings, etc. aren't reported and do not cause build warnings

### Reproduction Steps

Foo.csproj
```
<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<TargetFramework>net9.0</TargetFramework>
		<EnableNETAnalyzers>true</EnableNETAnalyzers>
		<AnalysisLevel>9.0-Recommended</AnalysisLevel>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
		<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
	</PropertyGroup>
</Project>
```

Program.cs
```
// block scoped namespaces are the default, but if you want a less controversial
// example just add using System.Collections; or similar 
namespace CSharpSample; 

internal static class Program
{
}
```

### Expected behavior

With dotnet 9.0.100 this fails as expected:
```
dotnet build
Restore complete (0,6s)
  CSharpSample failed with 1 error(s) (0,4s)
    D:\Source\Samples\CSharpSample\CSharpSample\Program.cs(1,1): error IDE0160: Convert to block scoped namespace (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0160)

Build failed with 1 error(s) in 1,3s
```

### Actual behavior

Dotnet 9.0.101 on the other hand builds it without complaint:
```
 dotnet build
Restore complete (0,6s)
  CSharpSample succeeded (0,3s) → CSharpSample\bin\Debug\net9.0\CSharpSample.dll

Build succeeded in 1,2s
```

### Regression?

Works fine with 9.0.100.

### Known Workarounds

None known.

### Configuration

Dotnet 9.0.101 x64 Windows
OS: Win11 Prox

The same also occurs on the machine when running dotnet 9.0.101 in WSL Ubuntu.

**Comment by CyrusNajmabadi** [comment]
@sharwell @JoeRobich @arunchndr known issue?  Dupe of the things we've fixed or rolled back?

**Comment by JoeRobich** [comment]
This is by design as we reverted the .NET 9 SDK behavior of applying new CodeStyle diagnostic defaults back to match .NET 8. The plan is to bring this experience in .NET 10 with a better tooling and messaging.

@danstur As a workaround to get the defaults in .NET 9, you can add `<AnalysisModeStyle>Recommended</AnalysisModeStyle>` to your property group.

**Comment by danstur** [comment]
@JoeRobich That works, but I'm confused. 

I thought using `<AnalysisLevel>9.0-Recommended</AnalysisLevel>` is the same 
as
```
<AnalysisLevel>9.0</AnalysisLevel>
<AnalysisMode>Recommended</AnalysisMode>
```

At least that's how I understand [the documentation](https://learn.microsoft.com/en-us/dotnet/core/project-sdk/msbuild-props#analysislevel). But clearly it makes a difference here.

**Comment by JoeRobich** [comment]
Due to a bug code style analyzers (IDE####) were **not** given new default severity based on the AnalysisMode prior to 9.0.100. The fix in behavior broke many customers builds as they also enable `TreatWarningsAsErrors`. The decision was to revert the change in 9.0.101 and rethink this scenario for .NET 10 so that we can provide this feature without breaking our customers.
