### ISSUE TITLE
Json source generator compiler error using reserved property names and DefaultIgnoreCondition

### ISSUE THREAD

**Issue by vsfeedback** [dotnet/runtime#98050]
_This issue has been moved from [a ticket on Developer Community](https://developercommunity.visualstudio.com/t/Json-source-generator-compiler-error-usi/10535386)._

---
[severity:I'm unable to use this version]
In .net8 using JSON source generator with property names that are preserved c# names and using JsonIgnoreCondition.WhenWritingNull, invalid sources will be generated.

[SourceGenBug.zip](https://aka.ms/dc/file?name=Bf7a5de6e950a4d23bd03eb3e0d802f5a638374833787755809_SourceGenBug.zip&tid=f7a5de6e950a4d23bd03eb3e0d802f5a638374833787755809)

```
public class Model
{
  public string type { get; set; }
  public string alias { get; set; }
}

[JsonSourceGenerationOptions(DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull)]
[JsonSerializable(typeof(Model))]
internal partial class ModelContext : JsonSerializerContext
{
}

```
This will generate source with a lot of compilation errors.
It wil generate

```
        string __value_@type = ((global::Model)value).@type;
        if (__value_@type != null)
        {
            writer.WriteString(PropName_type, __value_@type);
        }
```
In dotnet 7 it would generate:

```
            if (value.@type != null)
            {
                writer.WriteString(PropName_type, value.@type);
            }

```

---
#### Feedback Bot on 12/6/2023, 06:10 PM: 

(private comment, text removed)

---
### Original Solutions
(no solutions)

**Comment by eiriktsarpalis** [comment]
Appears to be a regression caused by https://github.com/dotnet/runtime/pull/87725, we should service .NET 8.
