### ISSUE TITLE
[release/6.0] ILVerify does not build in source-build

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/runtime#64817]
The .NET source-build tarball is failing to build on release/6.0.3xx with the following error:

```
/tarball/src/runtime.3a25a7f1cc446b60678ed25c9d829420d6321eba/artifacts/source-build/self/src/src/coreclr/tools/ILVerify/Program.cs(498,31): error CS0103: The name 'CommandHandler' does not exist in the current context [/tarball/src/runtime.3a25a7f1cc446b60678ed25c9d829420d6321eba/artifacts/source-build/self/src/src/coreclr/tools/ILVerify/ILVerify.csproj]
```

This stems from a couple of factors.  

1. Source build only builds one version of each repo.  The sdk's dependency on dotnet/command-line-api is the version included in source-build.
2. dotnet/command-line-api made some breaking changes and the dotnet/sdk took a [dependency on the latest release](https://github.com/dotnet/sdk/blob/release/6.0.3xx/eng/Version.Details.xml#L271) while dotnet/runtime is on an [older version](https://github.com/dotnet/runtime/blob/release/6.0/eng/Versions.props#L123).

Updating dotnet/runtime's version of command-line-api to the same as the sdk will solve the problem for release/6.0.3xx but it will then break release/6.0.2xx and release/6.0.1xx which are on the older version.  Upgrading the sdk to the latest command-line-api is a significant amount of work and was rejected to 6.0.2xx.

Options to fix this issue.
1. Exclude ILVerify from source-build.  I took a cursory look and see that ILVerification.nupkg is required but ILVerify might not be needed.
2. Update ILVerify to be conditioned so that it could build with either version (beta1 or beta2) of command-line-api.
3. Build both command-line-api versions in source-build.  This is a new feature which feels too for a servicing release.  It should only be a last resort after exhausting all other options.

cc @dotnet/source-build-internal

**Comment by jkotas** [comment]
> Exclude ILVerify from source-build. 

This gets bundled into https://www.nuget.org/packages/dotnet-ilverify/ global tool. Is it ok to omit this global tool from the source build?

**Comment by MichaelSimons** [comment]
>This gets bundled into https://www.nuget.org/packages/dotnet-ilverify/ global tool. Is it ok to omit this global tool from the source build?

It doesn't look like dotnet-ilverify get's bundled with the SDK.  If so, then dotnet-ilverify does not have to be included in source-build.  We only source-build what is included in the SDK.

**Comment by jkotas** [comment]
ILVerification nuget package is not included in the SDK either. Where is it required?

**Comment by MichaelSimons** [comment]
>ILVerification nuget package is not included in the SDK either. Where is it required?

I'm not finding a reference in source-build either.  I propose we remove is from source-build as well.  If you create a PR, I can run a full source tarball build with the changes to verify the e2e.

**Comment by jkotas** [comment]
The PR is up at #64833

**Comment by MichaelSimons** [comment]
@jkotas - FYI, I had kicked off a build over the weekend but just discovered I based it off the wrong commit.  I am re-running a new build this morning.

**Comment by MichaelSimons** [comment]
@jkotas - I was able to verify the change locally and everything passes.  I apologize that it took a while to verify.  Fixing this got the 6.0.3xx build further along and surfaced another issue that I had to work through.

**Comment by jkotas** [comment]
Thanks! Do you need the fix ported to 6.0 or is the patch from https://github.com/dotnet/installer/pull/13175 good enough?

**Comment by MichaelSimons** [comment]
Please backport.  We don't want to utilizes patches unless absolutely needed.
