### ISSUE TITLE
A part of lambda improvements feature doesn't work with latest SDK 6.0.101

### ISSUE THREAD

**Issue by acple** [dotnet/runtime#63374]
### Describe the bug
Below code is no longer compiled with latest SDK 6.0.101.

```csharp
Enumerable.Range(0, 0).Select(_ => (int x, int y) => x + y);
```
message:
```
error CS0411: The type arguments for method 'Enumerable.Select<TSource, TResult>(IEnumerable<TSource>, Func<TSource, int, TResult>)' cannot be inferred from the usage. Try specifying the type arguments explicitly. [/test/Test.csproj]
```

### To Reproduce
Build the C#10 project with above code on .NET 6.0 SDK 6.0.101.
This could be compiled on .NET 6.0 SDK 6.0.100.

### Further technical details
Environment:
* Docker image:  mcr.microsoft.com/dotnet/sdk:6.0.101-alpine3.14
* dotnet --info (in docker)
```
dotnet/sdk#8 [4/5] RUN dotnet --info
dotnet/sdk#8 sha256:d0c665ccd8313952f0043f3c178130f9867385a5390cbed239e4af724429a7da
dotnet/sdk#8 0.448 .NET SDK (reflecting any global.json):
dotnet/sdk#8 0.448  Version:   6.0.101
dotnet/sdk#8 0.448  Commit:    ef49f6213a
dotnet/sdk#8 0.448
dotnet/sdk#8 0.448 Runtime Environment:
dotnet/sdk#8 0.450  OS Name:     alpine
dotnet/sdk#8 0.450  OS Version:  3.14
dotnet/sdk#8 0.452  OS Platform: Linux
dotnet/sdk#8 0.479  RID:         alpine.3.14-x64
dotnet/sdk#8 0.479  Base Path:   /usr/share/dotnet/sdk/6.0.101/
dotnet/sdk#8 0.481
dotnet/sdk#8 0.486 Host (useful for support):
dotnet/sdk#8 0.486   Version: 6.0.1
dotnet/sdk#8 0.486   Commit:  3a25a7f1cc
dotnet/sdk#8 0.486
dotnet/sdk#8 0.486 .NET SDKs installed:
dotnet/sdk#8 0.486   6.0.101 [/usr/share/dotnet/sdk]
dotnet/sdk#8 0.486
dotnet/sdk#8 0.486 .NET runtimes installed:
dotnet/sdk#8 0.486   Microsoft.AspNetCore.App 6.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
dotnet/sdk#8 0.486   Microsoft.NETCore.App 6.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
dotnet/sdk#8 0.486
dotnet/sdk#8 0.486 To install additional .NET runtimes or SDKs:
dotnet/sdk#8 0.486   https://aka.ms/dotnet-download
dotnet/sdk#8 DONE 0.5s
```
