### PR TITLE
Build integration support for Bionic in NativeAOT

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Contributes to #87340.

Doesn't actually work E2E because the inline threadstatics work broke our Android support (the Android support code added in https://github.com/dotnet/corert/pull/8323).

```
  C:\Users\michals\.nuget\packages\microsoft.netcore.app.runtime.nativeaot.linux-bionic-arm64\8.0.0-preview.6.23307.4/r
  untimes/linux-bionic-arm64/\native\libRuntime.WorkstationGC.a(MiscStubs.S.o): In function `RhpGetInlinedThreadStaticB
  ase':
  /__w/1/s/src/coreclr/nativeaot/Runtime/arm64/MiscStubs.S:12: undefined reference to `tls_InlinedThreadStatics'
  /__w/1/s/src/coreclr/nativeaot/Runtime/arm64/MiscStubs.S:12: undefined reference to `tls_InlinedThreadStatics'
  /__w/1/s/src/coreclr/nativeaot/Runtime/arm64/MiscStubs.S:12: undefined reference to `tls_InlinedThreadStatics'
  /__w/1/s/src/coreclr/nativeaot/Runtime/arm64/MiscStubs.S:12: undefined reference to `tls_InlinedThreadStatics'
```

The general instructions on Bionic once all of the PRs merge:

* Download Android NDK and make sure clang from the NDK is first on the PATH
* `dotnet publish -r linux-bionic-arm64 /p:DisableUnsupportedError=true /p:PublishAotUsingRuntimePack=true`

This is of course blocked on the TLS issue. The fix is probably along the lines of #77475 but because #87148 is in flight, I don't know what to do about it. I was hoping this would be previewable in .NET 8 Preview 6.

Cc @dotnet/ilc-contrib

### CODE REVIEW

File: src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets [hunk 1]
```diff
@@ -153,11 +154,16 @@ The .NET Foundation licenses this file to you under the MIT license.
       <LinkerArg Include="-Wl,--eh-frame-hdr" Condition="'$(_IsApplePlatform)' != 'true'" />
     </ItemGroup>
 
-    <Exec Command="command -v &quot;$(CppLinker)&quot;" IgnoreExitCode="true" StandardOutputImportance="Low">
+    <PropertyGroup>
+      <_CommandProbe>command -v</_CommandProbe>
+      <_CommandProbe Condition="$([MSBuild]::IsOSPlatform('Windows'))">where</_CommandProbe>
```
Comment (am11) [inline src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets:159]: This file is not used on Windows, right? (i.e. we don't support cross-OS publishing in cross build mode)

Comment (MichalStrehovsky) [reply src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets:159]: I ran the above `dotnet publish -r linux-bionic-arm64 /p:DisableUnsupportedError=true /p:PublishAotUsingRuntimePack=true` with this on Windows. Worked fine with this change.

File: src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets [hunk 2]
```diff
@@ -64,7 +65,7 @@ The .NET Foundation licenses this file to you under the MIT license.
       <NetCoreAppNativeLibrary Include="System.Native" />
       <NetCoreAppNativeLibrary Include="System.Globalization.Native" Condition="'$(StaticICULinking)' != 'true' and '$(InvariantGlobalization)' != 'true'" />
       <NetCoreAppNativeLibrary Include="System.IO.Compression.Native" />
-      <NetCoreAppNativeLibrary Include="System.Net.Security.Native" />
+      <NetCoreAppNativeLibrary Include="System.Net.Security.Native" Condition="'$(_linuxLibcFlavor)' != 'bionic'" />
```
Comment (jkotas) [inline src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets:68]: If I am reading the correctly, uses of System.Net.Security.Native are not ifdefed out for linux-bionic in 
https://github.com/dotnet/runtime/blob/680043eca3595352930235fbf9353e1fb9e1f174/src/libraries/System.Net.Security/src/System.Net.Security.csproj#L16

Do we need a matching fix in the libraries too?

**Comment by VSadov** [comment]
>> The fix is probably along the lines of https://github.com/dotnet/runtime/pull/77475 but because https://github.com/dotnet/runtime/pull/87148 is in flight, I don't know what to do about it.

> You can make it jump directly to the slow path with emulated TLS for now.

You can also disable TLS inlining for Bionic in the ILC. 
The uninlined scenario has fewer platform dependencies and more suitable for platform bring-up.

File: src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets (hunk 2 above)
Comment (MichalStrehovsky) [reply src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets:68]: I don't know. Looking at the latest Bionic Mono build, we're not building this library there either so this can't be a NativeAOT specific problem, if it is a problem:

https://dnceng.visualstudio.com/7ea9116e-9fac-403d-b258-b31fcf1bb293/_apis/build/builds/2202215/logs/1188

```
2023-06-16T01:47:31.0970341Z   Install the project...
2023-06-16T01:47:31.1000197Z   -- Install configuration: "RELEASE"
2023-06-16T01:47:31.1000861Z   -- Installing: /__w/1/s/artifacts/bin/native/net8.0-linux-Release-arm64/./libSystem.IO.Compression.Native.so.dbg
2023-06-16T01:47:31.1019420Z   -- Installing: /__w/1/s/artifacts/bin/native/net8.0-linux-Release-arm64/./libSystem.IO.Compression.Native.so
2023-06-16T01:47:31.1028723Z   -- Installing: /__w/1/s/artifacts/bin/native/net8.0-linux-Release-arm64/./libSystem.IO.Compression.Native.a
2023-06-16T01:47:31.1064467Z   -- Installing: /__w/1/s/artifacts/bin/native/net8.0-linux-Release-arm64/./libSystem.Native.so.dbg
2023-06-16T01:47:31.1070650Z   -- Installing: /__w/1/s/artifacts/bin/native/net8.0-linux-Release-arm64/./libSystem.Native.so
2023-06-16T01:47:31.1074222Z   -- Installing: /__w/1/s/artifacts/bin/native/net8.0-linux-Release-arm64/./libSystem.Native.a
2023-06-16T01:47:31.1085002Z   -- Installing: /__w/1/s/artifacts/bin/native/net8.0-linux-Release-arm64/./libSystem.Globalization.Native.so.dbg
2023-06-16T01:47:31.1089764Z   -- Installing: /__w/1/s/artifacts/bin/native/net8.0-linux-Release-arm64/./libSystem.Globalization.Native.so
2023-06-16T01:47:31.1092925Z   -- Installing: /__w/1/s/artifacts/bin/native/net8.0-linux-Release-arm64/./libSystem.Globalization.Native.a
2023-06-16T01:47:31.1101678Z   -- Installing: /__w/1/s/artifacts/bin/native/net8.0-linux-Release-arm64/./libSystem.Security.Cryptography.Native.OpenSsl.so.dbg
2023-06-16T01:47:31.1107872Z   -- Installing: /__w/1/s/artifacts/bin/native/net8.0-linux-Release-arm64/./libSystem.Security.Cryptography.Native.OpenSsl.so
2023-06-16T01:47:31.1114082Z   -- Installing: /__w/1/s/artifacts/bin/native/net8.0-linux-Release-arm64/./libSystem.Security.Cryptography.Native.OpenSsl.a
2023-06-16T01:47:31.1130823Z   /__w/1/s/src/native/libs
```

I currently can't even test this enough to run a hello world so I'm not able to answer this question. It won't be much worse than Mono-Bionic.

Comment (jkotas) [reply src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets:68]: We may want to open an issue on it since it looks like a problem.

**Review by jkotas — APPROVED** [review]

File: src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets (hunk 2 above)
Comment (MichalStrehovsky) [reply src/coreclr/nativeaot/BuildIntegration/Microsoft.NETCore.Native.Unix.targets:68]: Filed #87665. It looks like System.Net.Security tests are disabled on Bionic due to "Timeout on Helix, cannot repro locally".
