### ISSUE TITLE
Microsoft.DotNet.CodeAnalysis.dll depends on newer assemblies than the compiler provides

### ISSUE THREAD

**Issue by ericstj** [dotnet/runtime#99141]
### Description

1. When running on the SDK compiler, the compiler server will run with the depdnencies in the SDK + the runtime specified in `sdk\9.0.100-preview.1.24101.2\Roslyn\bincore\VBCSCompiler.runtimeconfig.json`  -- this gets customized by the SDK to be the runtime that's bundled with that SDK.

2. When running on the toolset compiler (`Microsoft.Net.Compilers.Toolset` package) the runtime config is not customized, so host probing takes over.  If the CLI/SDK is copy local and isolated, with only the latest runtime, it will just roll-forward to that runtime.  If the machine-wide CLI/SDK is used then the host might find the lower exact match (EG: 8.0.0) and use it instead.

3. When running in VS we run on .NETFramework and use the dependencies in the Roslyn folder:
`C:\Program Files\Microsoft Visual Studio\2022\Preview\MSBuild\Current\Bin\Roslyn`

Cases 2 and 3 above will have older versions of dependencies like `System.Reflection.Metadata` and `System.Collections.Immutable`.

### Reproduction Steps

Clone dotnet/runtime for any coimmit after `70eae707742d7e977aa5c3a7e2cf44ceea5a454a`

Have the 9.0.0-preview1 SDK installed machine wide.

Try to `dotnet build` a test project using the machine wide dotnet, or open a sln in VS to build.

### Expected behavior

Builds successfully.

### Actual behavior

```
CSC : error CS8032: An instance of analyzer Microsoft.DotNet.CodeAnalysis.Analyzers.AppContextDefaultsAnalyzer cannot be created from <userProfile>.nuget\packages\microsoft.dotnet.codeanalysis\9.0.0-beta.24127.4\analyzers\Microsoft.DotNet.CodeAnalysis.dll : Could not load file or assembly 'System.Collections.Immutable, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified..
```

### Regression?

Yes, as of 70eae707742d7e977aa5c3a7e2cf44ceea5a454a in runtime introduced by https://github.com/dotnet/arcade/commit/d9930e5e9a0069e5b7726c119f614486b8ef438f

### Known Workarounds

Preferred workaround: remove https://github.com/dotnet/runtime/blob/8806af9f837a234ae726ad75ffa420ef966255f3/eng/Analyzers.targets#L22

Or disable the toolset compiler (only works for commandline): https://github.com/dotnet/runtime/blob/24a9ec6cf63ebac2e5e59b6dbdb8f1ff1d73fd6d/eng/Versions.props#L30
