### PR TITLE
Add metadatatoken override to SymbolMethod

### LINKED ISSUE #53300: RefEmit SymbolMethod should probably have a Metadata token override
The recent PR to add MedataToken getter overrides to builder classes has broken FSI code generation on dotnet 6.0:  Add MetadataToken getter override to builder classes (#43330) · dotnet/runtime@b72b13e (github.com)

The method:

```
private int GetMethodTokenNoLock(MethodInfo method, bool getGenericTypeDefinition)
```
was modified here: runtime/src/coreclr/System.Private.CoreLib/src/System/Reflection/Emit/ModuleBuilder.cs at 01b7e73cd378145264a7cb7a09365b41ed42b240 · dotnet/runtime (github.com)

This working code:
```
                if (symMethod.GetModule() == this)
1231
                    return symMethod.GetToken();
1232
```
Became this failing code:
```
                if (symMethod.GetModule() == this)
                    return symMethod.MetadataToken;
```

`symMethod` is an instance of `System.Reflection.Emit.SymbolMethod`: here  runtime/SymbolMethod.cs at main · dotnet/runtime (github.com)

Which does not provide an override for the MetadataToken property, thus it relies on MemberInfos base implementation which throws a System.InvalidOperationException: 'Operation is not valid due to the current state of the object.'

I assume, someone should either revert the change back to return symMethod.GetToken();  … or provide an overload for MetadataToken on System.Reflection.Emit.SymbolMethod.

Repro:
On a machine with a Net6.0 dotnet sdk installed:

In a command window type:
````
dotnet fsi

let arr = Array2D.create 3 4 0
let _ = Array2D.get arr 0 0
;;
````
observe the output:
````
error FS0193: internal error: Operation is not valid due to the current state of the object.
````

You may see a bunch of warnings on fsi startup like this, this is an unrelated bug, a fix is in the pipeline:
````
unknown(1,1): warning FS3384: The .NET SDK for this script could not be determined. If the script is in a directory using a 'global.json' then ensure the relevant .NET SDK is installed. Unexpected error 'Could not find a part of the path 'C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\0.0.0.0\ref'.'.
````

### PR DESCRIPTION
**Pull request by KevinRansom**
Fixes #53300 - RefEmit SymbolMethod should probably have a Metadata token override

The MetadataToken base implementation of MetadataToken throws an exception.  This provides an implementation that merely returns m_token to get a token for the symbol.

Originally the token was retrieved using the GetToken() method removed here:   https://github.com/dotnet/runtime/commit/b72b13e#diff-0db30e8f862ac0489421d919d343654824ac89bd001e8fb50e3c54cb53862b85L138

m_token is passed in to the SymbolMethod constructor

**Without Fix**
````
C:\kevinransom\runtime\artifacts\bin\testhost\net6.0-windows-Release-x64>dotnet C:\kevinransom\fsharp\artifacts\bin\fsi\Release\net5.0\fsi.dll

Microsoft (R) F# Interactive version 11.4.2.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> let arr = Array2D.create 3 4 0
- let _ = Array2D.get arr 0 0;;


error FS0193: internal error: Operation is not valid due to the current state of the object.

>
````

**With Fix**
````
C:\kevinransom\runtime\artifacts\bin\testhost\net6.0-windows-Release-x64>dotnet C:\kevinransom\fsharp\artifacts\bin\fsi\Release\net5.0\fsi.dll

Microsoft (R) F# Interactive version 11.4.2.0 for F# 5.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> let arr = Array2D.create 3 4 0
- let _ = Array2D.get arr 0 0;;
val arr : int [,] = [[0; 0; 0; 0]
                     [0; 0; 0; 0]
                     [0; 0; 0; 0]]
````

### CODE REVIEW

**Comment by jkotas** [comment]
Could you please also augment https://github.com/dotnet/runtime/blob/01b7e73cd378145264a7cb7a09365b41ed42b240/src/libraries/System.Reflection.Emit/tests/ModuleBuilder/ModuleBuilderGetArrayMethod.cs#L132 to validate that the MethodToken property returns a value that looks like a method token?

**Comment by jkotas** [comment]
cc @steveharter Fix for a regression introduced by #43330

**Review by jkotas — APPROVED** [review]
