### PR TITLE
Fix CLR_Tools_Tests build break in WasmArgumentLayoutTests

### LINKED ISSUE #131504: [ci-scan] Build break: ILCompiler.ReadyToRun.Tests fails CS7036 on ReadyToRunCompilerContext ctor
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1530244
Build error leg or test failing: linux-x64 checked CLR_Tools_Tests - ILCompiler.ReadyToRun.Tests

`main` @ 95b776802e7925130bde329247a2679b718f1e06 does not build.

Semantic merge conflict between two PRs that landed within ~18 hours of each other,
so neither one's CI saw the other:

- #131429 (merged 2026-07-27T20:14Z) added
  `src/coreclr/tools/aot/ILCompiler.ReadyToRun.Tests/WasmArgumentLayoutTests.cs`,
  which constructs `ReadyToRunCompilerContext` with 5 arguments.
- #130622 (merged 2026-07-28T14:04Z) added a `bool targetAllowsRuntimeCodeGeneration`
  parameter to that constructor, making it 6.

## Error Details

```
/__w/1/s/src/coreclr/tools/aot/ILCompiler.ReadyToRun.Tests/WasmArgumentLayoutTests.cs(166,45): error CS7036: There is no argument given that corresponds to the required parameter 'instructionSetSupport' of 'ReadyToRunCompilerContext.ReadyToRunCompilerContext(TargetDetails, SharedGenericsMode, bool, bool, InstructionSetSupport, CompilerTypeSystemContext)' [/__w/1/s/src/coreclr/tools/aot/ILCompiler.ReadyToRun.Tests/ILCompiler.ReadyToRun.Tests.csproj]
```

## Error Message

```json
{
  "ErrorMessage": "WasmArgumentLayoutTests.cs(166,45): error CS7036: There is no argument given that corresponds to the required parameter 'instructionSetSupport'",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

> [!NOTE]
> This issue body was drafted with GitHub Copilot and reviewed by me before filing.

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=1530244
**Error message validated:** `[WasmArgumentLayoutTests.cs(166,45): error CS7036: There is no argument given that corresponds to the required parameter 'instructionSetSupport'`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/28/2026 10:51:17 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

### PR DESCRIPTION
**Pull request by lewing**
`main` does not currently build. The `linux-x64 checked CLR_Tools_Tests` leg fails in `Build product`:

```
src/coreclr/tools/aot/ILCompiler.ReadyToRun.Tests/WasmArgumentLayoutTests.cs(166,45): error CS7036: There is no argument given that corresponds to the required parameter 'instructionSetSupport' of 'ReadyToRunCompilerContext.ReadyToRunCompilerContext(TargetDetails, SharedGenericsMode, bool, bool, InstructionSetSupport, CompilerTypeSystemContext)'
```

## Cause

A semantic merge conflict between two PRs that landed ~18 hours apart, so neither one's CI saw the other:

- #131429 (merged 2026-07-27T20:14Z) added `WasmArgumentLayoutTests.cs`, whose `CreateWasmContext` constructs `ReadyToRunCompilerContext` with 5 arguments.
- #130622 (merged 2026-07-28T14:04Z) added a `bool targetAllowsRuntimeCodeGeneration` parameter to that constructor, making it 6.

## Fix

Pass the missing argument. `false` is the value crossgen2 itself computes for this target: `Program.GetTargetAllowsRuntimeCodeGeneration` returns `false` when the OS is `Browser`/`Wasi`/Apple-mobile or the architecture is `Wasm32`, and this test context mirrors `--targetarch wasm --targetos browser` (as its own doc comment states). The flag governs whether `Vector<T>` stays optimistic and whether explicitly-unsupported ISA markers are emitted — on wasm there is no runtime codegen to fall back to.

## Validation

- `./build.sh clr+libs -rc Checked` succeeds, and `ILCompiler.ReadyToRun.Tests.csproj` then compiles clean — the exact compile that fails in CI.
- All 20 `WasmArgumentLayoutTests` cases pass, so the regression coverage #131429 added still tests what it was written to test.

Other tests in that assembly fail on my macOS-arm64 box for an unrelated local reason (`DllNotFoundException` for `clrjit_universal_arm64_arm64` / `clrjit_unix_x64_arm64` — `build.sh clr+libs` publishes only the wasm cross-jit into the crossgen2 output directory on this host). Those suites invoke crossgen2 as a subprocess and do not touch the changed file.

Fixes #131504

> [!NOTE]
> This change was developed with GitHub Copilot and reviewed by me before submitting.

### CODE REVIEW

**Review by jkoritzinsky — APPROVED** [review]

**Comment by lewing** [comment]
/ba-g fast merging to fix build break
