### ISSUE TITLE
Possible bug with Reverse LINQ method when updating SDK to 9.0.2

### ISSUE THREAD

**Issue by danfma** [dotnet/runtime#112540]
### URL(s)

https://github.com/dotnet/core/blob/main/release-notes/9.0/9.0.2/9.0.2.md

### Description

After updating to the SDK 9.0.2 from 9.0.0 I got a compilation error in a code that worked before. The Reverse LINQ operation was not being recognized anymore.

It's like if the IEnumerable Reverse extension method (which returns an IEnumerable<T>) is being replaced by the native `Array.Reverse` (which returns void). Causing the error below:

```
.../src/CarRacing/NeuralNetworks/NeuralNetworkTrainer.cs(90,30): error CS1579: foreach statement cannot operate on variables of type 'void' because 'void' does not contain a public instance or extension definition for 'GetEnumerator' [.../src/CarRacing/CarRacing.csproj]
```

![Image](https://github.com/user-attachments/assets/436cee4d-edd4-4f57-89e2-9df6154e0104)

**Comment by richlander** [comment]
- Left: original code
- Right: updated code adapted to the error message

Yes?

**Comment by lewing** [comment]
What is the LangVersion set to in your project? This looks like a duplicate of https://github.com/dotnet/runtime/issues/111532#issuecomment-2599043124

**Comment by richlander** [comment]
I rewrote your code with `List` and hit the same issue (possibly for different reasons). I then cast it to `IEnumerable` to avoid `List.Reverse` but to use `Enumerable.Reverse` and that works well.

```csharp
List<string> strings = ["Athens", "Berlin", "Canmore"];
IEnumerable<string> str = strings;

foreach (var s in str.Reverse())
{
    Console.WriteLine(s);
}
```

**Comment by danfma** [comment]
Hey, @lewing ! 

I'm using LangVersion=Preview configured by a `Directory.Build.props`.

```xml
<LangVersion>preview</LangVersion>
```

**Comment by danfma** [comment]
Yes, @richlander ! I imagined that it would work if I did the casting to the IEnumerable<T> there, but in that case, accessing the array directly has better performance, so I've opted for the old-style for-loop there! :D

**Comment by danfma** [comment]
Some time ago I read somewhere that we had some enhancements related to LINQ and array usage in an attempt to remove virtual calls to gain performance. So, I guess that it might be the case. Maybe the compiler is doing a wrong optimization in that case, or I hit the corner case of that approach! :D

**Comment by richlander** [comment]
I think we got to the bottom of this. Thanks for the report!
