### ISSUE TITLE
.NET 8 macOS *.app does not launch after code signing

### ISSUE THREAD

**Issue by namigop** [dotnet/runtime#95727]
### Description

Unable to launch a macOS *.app file after code signing.  The app opens briefly and then immediately closes

## Steps to reproduce 
1. clone the repo https://github.com/namigop/FintX
2. Edit the *.csproj and *.fsproj to target `.net8.0`
3. build : `dotnet build   --configuration Release`
4. publish: `dotnet publish --self-contained --runtime osx-x64  --configuration Release`
5. create an *.app bundle
   - in the Tefin.csproj folder, run 
   `dotnet msbuild -t:BundleApp -p:RuntimeIdentifier=osx-x64  -property:Configuration=Release`
6. In the /publish folder, double-click the created Fintx.app file.  It will open and run fine
7. Close the FintX.app
8. For every file within the FintX.app (it's just a folder), run 
`codesign --force --verbose --timestamp --options=runtime --entitlements  {entitlements} --sign {signIdentity} {file}`

  where 
- {entitlements} : is https://github.com/namigop/FintX/blob/main/source/Tefin/FintX.entitlements 
- {signIdentity}  : is the Common Name of the Developer Id Application signing certificate.  For example,it looks like 
                                      this `Developer ID Application: FirstName LastName (ABCDEJGYUP)`
- {file} : is the the file path

9. Sign the FintX.app using the same codesign command as above
10. Run `codesign --verify --verbose {path_to_fintx.app}`. Note that the verification output will indicate FintX.app was successfully signed
11.   Double-click on FintX.app.  It will briefly open and then immediately close
- Not sure if this will help but If you open a terminal and run `./FintX.app`, it will show a `permission denied` error and the app, of course, does not launch

### Expected behavior

If the projects are targeting `net7.0`, the signed *.app file, runs properly

### Actual behavior

The signed *.app file opens briefly, then immediately closes.

### Regression?

Yes, this works in net7.0. Please see the repo : https://github.com/namigop/FintX.  I had to retarget it to .NET 7.0

### Configuration

runtime: net8.0, osx-x64
OS: macOS Monterey v12.7.1
chip: Apple M1 Pro

### Other information

I thought the *.app was crashing, but when I open Console and check the Crash Reports, I dont see any entry there.

**Comment by namigop** [comment]
Dear dotnet team,

any updates on this ticket please?

**Comment by filipnavara** [comment]
I wanted to give the repro a try but I already failed at step 3:
> /Users/filipnavara/.nuget/packages/grpc.tools/2.58.0/build/_protobuf/Google.Protobuf.Tools.targets(52,5): error : Google.Protobuf.Tools proto compilation is only supported by default in a C# project (extension .csproj)

**Comment by namigop** [comment]
Thank you for the reply @filipnavara . Regarding the proto compilation error, you can `negate the condition` in that the Google.Protobuf.Tools.targets file.  The fsproj that has a reference to that package but does not need to generate C# code from proto files, but it does need the library

**Comment by filipnavara** [comment]
For posterity, running `dotnet build --configuration Release -p:Protobuf_ProjectSupported=true` requires no changes to .targets file.

Next failing step is the one with `BundleApp` target from `DotNet.Bundle`. It doesn't actually create the package with self-contained executable. That could be a result of a documented breaking change where `--self-contained` needs to be explicitly specified in .NET 8. That way the created app bundle now depends on some system assemblies in a different location. That can easily be fixed by adding `-p:SelfContained=true` to the command line: `dotnet msbuild -t:BundleApp -p:RuntimeIdentifier=osx-x64 -p:SelfContained=true -property:Configuration=Release -p:Protobuf_ProjectSupported=true`.

Next up, sign the whole app bundle in one command - `codesign --force --verbose --timestamp --options=runtime --entitlements ./FintX.entitlements --sign "*" --deep ./bin/Release/net8.0/osx-x64/publish/FintX.app`. The result works just fine for me.

**Comment by namigop** [comment]
Just tried it out and yes the adding the `p:SelfContained=true` arg fixed it.  My fault for not knowing about the braking change on .NET 8 about needing to explicitly specify self-contained when publishing. 

Thank you so much for looking into this ticket @filipnavara

**Comment by namigop** [comment]
Adding a link to the change then closing this ticket. https://learn.microsoft.com/en-us/dotnet/core/compatibility/sdk/8.0/runtimespecific-app-default
