### PR TITLE
Update dependencies from https://github.com/dotnet/arcade build 20210908.7

### PR DESCRIPTION
**Pull request by ericstj**
Needed for installer validation. Manually ran:
```
darc update-dependencies --id 107680
```

### CODE REVIEW

**Review by ViktorHofer — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Hmm there are issues in the build. Probably a break in the Arcade SDK

**Comment by ericstj** [comment]
Ah, I didn't get the fix for that, which merged later that day.  Let me pick a different build.

**Comment by ericstj** [comment]
Hmm, it looks like it had the fix  https://github.com/dotnet/arcade/commit/89db4b3b7dc2f19eec43f948ad51efc0d496fc8c  but needed a follow up one https://github.com/dotnet/arcade/pull/7870

**Comment by ViktorHofer** [comment]
The compiler errors are appearing because of a roslyn update: https://github.com/dotnet/arcade/commit/ae0ffc22e728ec379f894c02d7659484d8fe4441. cc @stephentoub

**Comment by stephentoub** [comment]
> The compiler errors are appearing because of a roslyn update

@cston, @jaredpar, is this fallout from the delegate inference changes? These tests now failing to compile with ambiguity haven't been touched in a long time.

**Comment by stephentoub** [comment]
@cston, @jaredpar, here's a repro:
```C#
using System;

var source = new C<int>();
source.Aggregate(() => 0, (i, j) => i, (i, j) => i, i => i);

class C<T> { }

static class Extensions
{
    public static TResult Aggregate<TSource, TAccumulate, TResult>(
        this C<TSource> source,
        Func<TAccumulate> seedFactory,
        Func<TAccumulate, TSource, TAccumulate> updateAccumulatorFunc,
        Func<TAccumulate, TAccumulate, TAccumulate> combineAccumulatorsFunc,
        Func<TAccumulate, TResult> resultSelector) => default!;

    public static TResult Aggregate<TSource, TAccumulate, TResult>(
        this C<TSource> source,
        TAccumulate seed,
        Func<TAccumulate, TSource, TAccumulate> updateAccumulatorFunc,
        Func<TAccumulate, TAccumulate, TAccumulate> combineAccumulatorsFunc,
        Func<TAccumulate, TResult> resultSelector) => default!;
}
```
That compiles fine with LangVersion 9.0.  It fails with the following now on LangVersion 10.0:
```
error CS0121: The call is ambiguous between the following methods or properties: 'Extensions.Aggregate<TSource, TAccumulate, TResult>(C<TSource>, Func<TAccumulate>, Func<TAccumulate, TSource, TAccumulate>, Func<TAccumulate, TAccumulate, TAccumulate>, Func<TAccumulate, TResult>)' and 'Extensions.Aggregate<TSource, TAccumulate, TResult>(C<TSource>, TAccumulate, Func<TAccumulate, TSource, TAccumulate>, Func<TAccumulate, TAccumulate, TAccumulate>, Func<TAccumulate, TResult>)'
```

**Comment by cston** [comment]
@stephentoub, thanks for the repro.

Yes, the ambiguities are a result of the compiler changes for lambda expressions. In your repro, method type inference is inferring `TAccumulate = System.Func<int>` from the argument `() => 0` for the second overload (previously, that argument would have been ignored in type inference), so both overloads are applicable but neither overload is preferred over the other.

I will create a PR to update the tests.

**Comment by ericstj** [comment]
@cston looks like another hit of the same problem: https://github.com/dotnet/runtime/blob/main/src/libraries/System.Linq/tests/AggregateTests.cs

I'll try to copy your workaround in this branch.

**Comment by ericstj** [comment]
Disregard this PR (and deleted comment).  I confused this with https://github.com/dotnet/runtime/pull/58865.  That seems to be progressing.  Closing this.
