### ISSUE TITLE
Incremental builds failing because of missing FireEtwGCDynamicEvent

### ISSUE THREAD

**Issue by AndyAyersMS** [dotnet/runtime#100556]
Have run into this now on both windows and linux.

I pull in latest main, but have built against older hashes. Rebuilding then fails with
```
  /home/andy/repos/runtime0/src/coreclr/nativeaot/Runtime/gctoclreventsink.cpp:34:5: error: use of undeclared identifier 'FireEtwGCDynamicEvent'
      FireEtwGCDynamicEvent(wideEventName, payloadSize, (const BYTE*)payload, GetClrInstanceId());
      ^
  1 error generated.
  make[2]: *** [nativeaot/Runtime/Full/CMakeFiles/Runtime.ServerGC.dir/build.make:230: nativeaot/Runtime/Full/CMakeFiles/Runtime.ServerGC.dir/__/gctoclreventsink.cpp.o] Error 1
```
This can be fixed with `git clean -dfx`

**Comment by MichalStrehovsky** [comment]
I hit this too. It was probably introduced in #99862. The EventPipe Python goo that is supposed to generate this is probably not incremental. Don't really know what area path to put this to.
