### ISSUE TITLE
Brotli native code is compiled with LTCG

### ISSUE THREAD

**Issue by MichalStrehovsky** [dotnet/runtime#111566]
And this is going to break everyone who doesn't use exactly the same version of VC++ as we used on the build machine.

Reported at https://github.com/aspnet/Benchmarks/issues/2047. We should also check zlib.

```
  brotlienc.lib(encode.c.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
EXEC : fatal error C1900: Il mismatch between 'P1' version '20240319' and 'P2' version '20220715' [C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-6848\ooktqbfk.xuf\src\Benchmarks\Benchmarks.csproj]
LINK : fatal error LNK1257: code generation failed [C:\Users\Administrator\AppData\Local\Temp\benchmarks-agent\benchmarks-server-6848\ooktqbfk.xuf\src\Benchmarks\Benchmarks.csproj]
```

**Comment by jkotas** [comment]
cc @jkoritzinsky Regression introduced by #109707 ?

**Comment by jkoritzinsky** [comment]
Yes this was introduced by #109707.

**Comment by MichalStrehovsky** [comment]
@jkoritzinsky will you have time to look at this soon-ish? If we're unlucky and VC++ ships an update at the same time we ship preview 1, this could mean that native AOT in Preview 1 won't be usable since most people will have a VC++ compiler that is not compatible with what we built.

**Comment by jkoritzinsky** [comment]
I put out a fix in https://github.com/dotnet/runtime/pull/111805
