### ISSUE TITLE
Arm64/Sve: Test build failing because of ShiftLeftLogical/ShiftRightLogical

### ISSUE THREAD

**Issue by kunalspathak** [dotnet/runtime#104190]
```
: Argument 1: cannot convert from 'System.Numerics.Vector<sbyte>' to 'System.Runtime.Intrinsics.Vector128<byte>' [d:\git\runtime2\src\tests\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro.cs
proj] [d:\git\runtime2\src\tests\build.proj]
d:\git\runtime2\artifacts\tests\coreclr\obj\windows.arm64.Release\Managed\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro\Sve_ro\gen\Sve.ShiftLeftLogical.sbyte.ulong.cs(145,58): error CS1503
: Argument 2: cannot convert from 'System.Numerics.Vector<ulong>' to 'byte' [d:\git\runtime2\src\tests\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro.csproj] [d:\git\runtime2\src\tests\buil
d.proj]
d:\git\runtime2\artifacts\tests\coreclr\obj\windows.arm64.Release\Managed\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro\Sve_ro\gen\Sve.ShiftLeftLogical.ushort.cs(145,51): error CS1503: Arg
ument 1: cannot convert from 'System.Numerics.Vector<ushort>' to 'System.Runtime.Intrinsics.Vector128<byte>' [d:\git\runtime2\src\tests\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro.csproj
] [d:\git\runtime2\src\tests\build.proj]
d:\git\runtime2\artifacts\tests\coreclr\obj\windows.arm64.Release\Managed\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro\Sve_ro\gen\Sve.ShiftLeftLogical.ushort.cs(145,58): error CS1503: Arg
ument 2: cannot convert from 'System.Numerics.Vector<ushort>' to 'byte' [d:\git\runtime2\src\tests\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro.csproj] [d:\git\runtime2\src\tests\build.pr
oj]
d:\git\runtime2\artifacts\tests\coreclr\obj\windows.arm64.Release\Managed\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro\Sve_ro\gen\Sve.ShiftRightLogical.byte.cs(145,52): error CS1503: Argu
ment 1: cannot convert from 'System.Numerics.Vector<byte>' to 'System.Runtime.Intrinsics.Vector128<byte>' [d:\git\runtime2\src\tests\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro.csproj] [
d:\git\runtime2\src\tests\build.proj]
d:\git\runtime2\artifacts\tests\coreclr\obj\windows.arm64.Release\Managed\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro\Sve_ro\gen\Sve.ShiftRightLogical.byte.cs(145,59): error CS1503: Argu
ment 2: cannot convert from 'System.Numerics.Vector<byte>' to 'byte' [d:\git\runtime2\src\tests\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro.csproj] [d:\git\runtime2\src\tests\build.proj]
d:\git\runtime2\artifacts\tests\coreclr\obj\windows.arm64.Release\Managed\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro\Sve_ro\gen\Sve.ShiftLeftLogical.ushort.ulong.cs(145,51): error CS150
3: Argument 1: cannot convert from 'System.Numerics.Vector<ushort>' to 'System.Runtime.Intrinsics.Vector128<byte>' [d:\git\runtime2\src\tests\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro.
csproj] [d:\git\runtime2\src\tests\build.proj]
d:\git\runtime2\artifacts\tests\coreclr\obj\windows.arm64.Release\Managed\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro\Sve_ro\gen\Sve.ShiftLeftLogical.ushort.ulong.cs(145,58): error CS150
3: Argument 2: cannot convert from 'System.Numerics.Vector<ulong>' to 'byte' [d:\git\runtime2\src\tests\JIT\HardwareIntrinsics\Arm\Sve\Sve_ro.csproj] [d:\git\runtime2\src\tests\bui
ld.proj]
```

Introduced by https://github.com/dotnet/runtime/pull/104119

**Comment by kunalspathak** [comment]
@amanasifkhalid - can you please take a look? This is blocking building the test.

**Comment by kunalspathak** [comment]
I forgot to build libraries and hence was getting those errors. Sorry about that.
