### ISSUE TITLE
Http/SSl StressTest build failures

### ISSUE THREAD

**Issue by antonfirsov** [dotnet/runtime#80706]
The Http(Ssl)Stress projects fail to build, most likely because of #78354.

```
/app/Program.cs(4,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [/app/HttpStress.csproj]
```

https://dev.azure.com/dnceng-public/public/_build/results?buildId=138183&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=7fe64d4e-bb7a-5b68-0c5c-ad57d12d4da9&l=2462
