### PR TITLE
Fix to build mono on Windows with ninja by default as well

### LINKED ISSUE #50753: Mono Windows Cross build failing
The Mono AOT cross build is failing to build in CI with the following errors:

>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.28.29333\include\emmintrin.h(24,1): fatal error C1189: #error:  This header is specific to X86 and X64 targets [D:\workspace\_work\1\s\artifacts\obj\mono\Android.arm64.Release\cross\mono\mini\monosgen-objects.vcxproj]

See https://dev.azure.com/dnceng/public/_build/results?buildId=1072786&view=results for an example in master.

cc: @directhex 

Runfo Tracking Issue: [Mono windows crossaot build failure](https://runfo.azurewebsites.net/tracking/issue/167)
|Definition|Build|Kind|Job Name|
|---|---|---|---|

Build Result Summary
|Day Hit Count|Week Hit Count|Month Hit Count|
|---|---|---|
|0|0|0|

runfo seems to be glitching on populating the table, so here's a runfo query for the failures: https://runfo.azurewebsites.net/search/timelines/?bq=definition%3Aruntime+started%3A%7E5&tq=type%3Aerror+text%3A%22cmake+--build+.+--target+install+--config+Release+--parallel+4%22+jobName%3A%22Mono+crossaot+Product+Build+windows+x64+release%22

### PR DESCRIPTION
**Pull request by akoeplinger**
This got broken by https://github.com/dotnet/runtime/commit/8c2158f9fe12c82cd3c0a7f4150773654bc78aaf since we no longer passed `/p:Ninja=true` down to mono.proj from build.cmd/ps1

Fixes https://github.com/dotnet/runtime/issues/50753

### CODE REVIEW

**Review by directhex — APPROVED** [review]

**Review by jkoritzinsky — APPROVED** [review]

**Comment by akoeplinger** [comment]
Looks like this was missed in the initial PR because it didn't touch any files in src/mono so CI didn't trigger mono legs.

@safern should we add `eng/*` as triggers to `eng/pipelines/common/evaluate-default-paths.yml`?

**Comment by safern** [comment]
Hmmm that should already be included: 

https://github.com/dotnet/runtime/blob/main/eng/pipelines/common/evaluate-default-paths.yml#L28-L45

**Comment by safern** [comment]
I do see mono build running on that PR build:

https://dev.azure.com/dnceng/public/_build/results?buildId=1054503&view=logs&j=e4304a73-856f-5230-44ef-10471e0044a5

Also this is the output for evaluate paths for the mono subset:

```
******* Probing mono exclude paths *******
eng/Version.Details.xml
*.md
LICENSE.TXT
PATENTS.TXT
THIRD-PARTY-NOTICES.TXT
docs/*
src/installer/*
src/coreclr/*
src/libraries/*
src/tests/*
eng/pipelines/installer/*
eng/pipelines/coreclr/*
eng/pipelines/libraries/*

+ git diff -M -C -b --ignore-cr-at-eol --ignore-space-at-eol --exit-code --quiet 'HEAD^1' -- ':!eng/Version.Details.xml' ':!*.md' ':!LICENSE.TXT' ':!PATENTS.TXT' ':!THIRD-PARTY-NOTICES.TXT' ':!docs/*' ':!src/installer/*' ':!src/coreclr/*' ':!src/libraries/*' ':!src/tests/*' ':!eng/pipelines/installer/*' ':!eng/pipelines/coreclr/*' ':!eng/pipelines/libraries/*'

----- Matching files for mono -----
+ git diff -M -C -b --ignore-cr-at-eol --ignore-space-at-eol --name-only 'HEAD^1' -- ':!eng/Version.Details.xml' ':!*.md' ':!LICENSE.TXT' ':!PATENTS.TXT' ':!THIRD-PARTY-NOTICES.TXT' ':!docs/*' ':!src/installer/*' ':!src/coreclr/*' ':!src/libraries/*' ':!src/tests/*' ':!eng/pipelines/installer/*' ':!eng/pipelines/coreclr/*' ':!eng/pipelines/libraries/*'
eng/build.ps1
eng/native/configurecompiler.cmake
eng/native/functions.cmake
eng/pipelines/global-build.yml
src/native/corehost/CMakeLists.txt
src/native/corehost/build.cmd

Setting pipeline variable containsChange=true
```

**Review by safern — APPROVED** [review]

**Comment by akoeplinger** [comment]
@safern hmm you're right, it did run in the PR. I was confused because GitHub doesn't show it in the PR result summary at the end of the PR (only lists 100 statuses there) but does show it on the Checks tab:

image

vs.

image

This PR should still fix the issue though.

**Comment by akoeplinger** [comment]
`Mono crossaot Product Build windows x64 release` passed, the other failures are infrastructure issues.
