### ISSUE TITLE
Building runtime on Visual Studio fails with compilation errors

### ISSUE THREAD

**Issue by aromaa** [dotnet/runtime#95564]
Trying to build the runtime on Visual Studio leads to the following compilation errors but works fine on the command line. Reverting #91563 seems to fix this.

```
dbghelpers.obj : error LNK2047: module contains C++ EH or complex EH metadata but was not compiled with /guard:ehcont
UMThunkStub.obj : error LNK2047: module contains C++ EH or complex EH metadata but was not compiled with /guard:ehcont
ThePreStubAMD64.obj : error LNK2047: module contains C++ EH or complex EH metadata but was not compiled with /guard:ehcont
RedirectedHandledJITCase.obj : error LNK2047: module contains C++ EH or complex EH metadata but was not compiled with /guard:ehcont
GenericComPlusCallStubs.obj : error LNK2047: module contains C++ EH or complex EH metadata but was not compiled with /guard:ehcont
GenericComCallStubs.obj : error LNK2047: module contains C++ EH or complex EH metadata but was not compiled with /guard:ehcont
CallDescrWorkerAMD64.obj : error LNK2047: module contains C++ EH or complex EH metadata but was not compiled with /guard:ehcont
artifacts\obj\coreclr\windows.x64.Checked\ide\dlls\mscoree\coreclr\Checked\coreclr.dll : fatal error LNK1386: could not generate metadata for one or more modules not compiled with /guard:ehcont; use /force:guardehcont to link anyways
Done building project "coreclr.vcxproj" -- FAILED.
```

Windows 10 22H2 build 19045.3693
x64
Microsoft Visual Studio Community 2022 Version 17.9.0 Preview 1.1

**Comment by jkotas** [comment]
cc @janvorli

**Comment by janvorli** [comment]
@aromaa thank you for reporting this issue. I am looking into it.

**Comment by janvorli** [comment]
@aromaa It is actually a cmake bug. See https://gitlab.kitware.com/cmake/cmake/-/issues/24289. Some of the options we set for the assembler (namely `/guard:ehcont`) are not propagated to the ml64.exe (MASM). It was already fixed in a recent cmake. I've first ran the build with cmake 3.22 and the issue occured. After discovering the issue, I've installed cmake 3.28 and the issue is gone.

**Comment by aromaa** [comment]
Aha! That indeed solves my problem. Is it worthwhile to add add some kind of warning that would show up in Visual Studio or a note in the documentation? Or maybe this issue is enough for anyone that could encounter this in the future.

In any case, this can be closed on my end.

**Comment by agocke** [comment]
Closing as resolved.
