### PR TITLE
Fix build error due to unused windowSize parameter in pal_console.c

### PR DESCRIPTION
**Pull request by akoeplinger**
```
src/native/libs/System.Native/pal_console.c(42,45): error G60964CEC: (NETCORE_ENGINEERING_TELEMETRY=Build) unused parameter 'windowSize' [-Werror,-Wunused-parameter]
```

Introduced in https://github.com/dotnet/runtime/pull/75824

### CODE REVIEW

**Review by adamsitnik — APPROVED** [review]
LGTM, big thanks for the fix and apologies for breaking you @akoeplinger !

Just for my education: I did not see any failing Android builds in #75824, so I assume we don't run them by default?

**Comment by akoeplinger** [comment]
> Just for my education: I did not see any failing Android builds in https://github.com/dotnet/runtime/pull/75824, so I assume we don't run them by default?

Correct, we use some heuristics to detect whether to trigger them (e.g. changes in src/mono) so this didn't get triggered there. No big deal, we knew we'd sometimes have build errors sneak in when we made that tradeoff.
