### ISSUE TITLE
Tests don't run for System.Threading.AccessControl library

### ISSUE THREAD

**Issue by eugene-shcherbo** [dotnet/runtime#43447]
I use the command `dotnet build /t:test` from [this guide](https://github.com/dotnet/runtime/blob/master/docs/workflow/building/libraries/README.md) to build and run tests for #43346 System.Threading.AccessControl library, but it doesn't seem to work. 

It actually just tries to restore some projects and that's it. Even if I make a compilation error in the test code or add an Assert which always fails it doesn't see the changes. The output is always the same:

```
% dotnet build /t:test
Microsoft (R) Build Engine version 16.8.0-preview-20451-02+51a1071f8 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.

  Determining projects to restore...
  All projects are up-to-date for restore.

Build succeeded.
    0 Warning(s)
    0 Error(s)

Time Elapsed 00:00:01.68
```

I also tried this command to run tests `./build.sh -projects src/libraries/System.Threading.AccessControl/tests/*.csproj` but it fails with the following error:
>  error MSB3202: The project file "src/libraries/System.Threading.AccessControl/tests/System.Threading.AccessControl.Tests.csproj" was not found.

If  I run just `dotnet build` command it builds the project and see all the compilation errors if any, but it doesn't run tests.

I'm working on **MacOS Catalina v10.15.7** and, by the way, when I was working on the issue related to the Microsoft.Extensions.Logging library I was able to run the tests using `dotnet build /t:test`.

I'm sorry if it's not correct to create an issue for this type of problems, I'm just quite new to the repo and OSS contribution, so didn't find any other way to solve the issue.

Thanks!

**Comment by eugene-shcherbo** [comment]
I actually realized that target frameworks of the project are **all** Windows specific, so I can't run it on OSX. Need to switch to Windows to continue working on the issue.
`<TargetFrameworks>$(NetCoreAppCurrent)-Windows_NT;net461-Windows_NT</TargetFrameworks>`
