### PR TITLE
Suppress linker analysis warnings on GetImmutableDictionaryCreateRangeMethod

### LINKED ISSUE #42902: Compilation error: ApiCompat shows Trim analysis error for IEnumerableConverterFactoryHelpers
Building `master` currently is giving me a compilation error.

Steps to reproduce:

1. Check out `master` (bisect shows this was introduced in 994dca6f34dc709aa91a5976ea8322ef7a9604d1)
2. Run `./build.sh -rc release -s clr+libs`

Eventually, the `ApiCompat` step fails:

> /code/personal/dotnet/runtime/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Collection/IEnumerableConverterFactoryHelpers.cs(179,17): Trim analysis error IL2075: System.Text.Json.Serialization.IEnumerableConverterFactoryHelpers.GetImmutableDictionaryCreateRangeMethod(Type,Type,Type): The requirements declared via the 'DynamicallyAccessedMembersAttribute' on the return value of method 'System.Text.Json.Serialization.IEnumerableConverterFactoryHelpers.GetImmutableDictionaryConstructingType(Type)' don't match those on the implicit 'this' parameter of method 'System.Type.GetMethods()'. The source value must declare at least the same requirements as those declared on the target location it's assigned to [/code/personal/dotnet/runtime/src/libraries/src.proj]

and

> code/personal/dotnet/runtime/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/Converters/Collection/IEnumerableConverterFactoryHelpers.cs(187,25): Trim analysis error IL2060: System.Text.Json.Serialization.IEnumerableConverterFactoryHelpers.GetImmutableDictionaryCreateRangeMethod(Type,Type,Type): Call to `System.Reflection.MethodInfo.MakeGenericMethod(Type[])` can not be statically analyzed. It's not possible to guarantee the availability of requirements of the generic method. [/code/personal/dotnet/runtime/src/libraries/src.proj]

Occurs on Ubuntu 20.04.

/cc @layomia

### PR DESCRIPTION
**Pull request by layomia**
Fixes https://github.com/dotnet/runtime/issues/42902.

These changes need to be made following https://github.com/dotnet/runtime/pull/42835 which added a new parameter to the method. That PR was merged before the [baseline suppressions](https://github.com/dotnet/runtime/pull/40691) were checked in. In the future, the linker warnings would be caught in CI or locally if the `libs` subset is rebuilt.

### CODE REVIEW

**Review by eerhardt — APPROVED** [review]
Looks good.

**Review by stephentoub — APPROVED** [review]

**Review by ViktorHofer — APPROVED** [review]

**Review by steveharter — APPROVED** [review]
LGTM; currently affecting CI in https://github.com/dotnet/runtime/pull/42538/checks?check_run_id=1188656484

**Comment by ViktorHofer** [comment]
Merging to unblock CI. Building is finished in the legs anyway.
