### PR TITLE
Fix freebsd cross build with cmake 3.25

### LINKED ISSUE #78528: FreeBSD build break with cmake version 3.25.0
## Repro

Try to build the repo using latest mcr.microsoft.com/dotnet-buildtools/prereqs:ubuntu-18.04-cross-freebsd-12 image

## Result:

Build breaks (src/native/libs/System.Native/pal_networkstatistics.c(430,16): error G3B749D71: (NETCORE_ENGINEERING_TELEMETRY=Build) assigning to 'struct inpcb' from incompatible type 'struct xinpcb')

Context https://github.com/dotnet/runtime/issues/78522

Revert https://github.com/dotnet/runtime/pull/78526 as part of fixing this issue.

### PR DESCRIPTION
**Pull request by am11**
In cmake 3.25, the toolchain file is called with context containing `LINUX` variable set. This causes problem for non-Linux platform. Fix is to unset platform variables which we use in the toolchain file.

Upstream PR: https://github.com/dotnet/arcade/pull/11672
Fixes: #78528

### CODE REVIEW

**Comment by am11** [comment]
cc @jkotas, reverted pinned container reference. FreeBSD legs are green. It was this change in cmake 3.25 which sets LINUX to 1: https://github.com/Kitware/CMake/commit/62cd3904bf22fd75a2502af09ef67f8458ce06e1.

**Review by jkotas — APPROVED** [review]
Thank you!

**Comment by akoeplinger** [comment]
We have similar code in eng/native/tryrun.cmake. This sounds like a cmake bug to me, could you please report it to them?

The [changelog](https://cmake.org/cmake/help/latest/release/3.25.html#variables) only mentions this:
> The [LINUX](https://cmake.org/cmake/help/latest/variable/LINUX.html#variable:LINUX) and [CMAKE_HOST_LINUX](https://cmake.org/cmake/help/latest/variable/CMAKE_HOST_LINUX.html#variable:CMAKE_HOST_LINUX) variables are now set to true when the target or host system is Linux, respectively.

Maybe we should also stop relying on these variables and introduce our own (e.g. similar to the `CLR_CMAKE_HOST_FREEBSD`)

**Comment by akoeplinger** [comment]
Ah this is in the cross-build docker images so the host system is actually Linux right? That makes more sense then and makes me wish we'd stop using these variables even more.

**Comment by am11** [comment]
It can refactored separately, I don't feel strongly that we _should_; because:

1. The toolchain file and try_compile is a cmake built-in mechanism and cmake invoke these files at different times with different contexts in cross-build mode. We should not mix the variable names which will be set _later_ by configureplatform.cmake (e.g. `CLR_CMAKE_HOST_FREEBSD`).

2. The root-cause of why Linux.cmake is even included in the [toolchain file](https://cmake.org/cmake/help/latest/manual/cmake-toolchains.7.html#cross-compiling) (which is supposed to act like a seed file in cross-compilation mode to locate usable toolchain) is because we make decision about the target platform _in_ this file, rather than _before_ invoking cmake. We can easily move these conditions: https://github.com/dotnet/runtime/blob/9ff3fc24d663c1e1d2857b52cc30bedd817f3695/eng/common/cross/toolchain.cmake#L10-L23 to `gen-buildsys.sh` and set `CMAKE_SYSTEM_NAME` to the desired target platform before invoking cmake (as we already do for Darwin in `gen-buildsys.sh`..). But we haven't done that intentionally from the get go because we wanted to keep build-rootfs.sh and toolchain.cmake pair tightly coupled and independent; those hint paths to detect platform come from (or cause by) `build-rootfs.sh`.

**Comment by akoeplinger** [comment]
Yeah I'm mostly worried that we're basically overriding CMake-internal variables and who knows what impact that has.

**Comment by jkotas** [comment]
I agree with @am11 that overwriting built-in CMake variables during cross-compilation seems to be pretty standard pattern. It is even suggested in official CMake docs.

**Comment by jkotas** [comment]
All failures are known issues according to the Build Analysis.

**Comment by akoeplinger** [comment]
Right but we're apparently using these variables not in the way that cmake intended (i.e. for cross compilation targets rather than the host). I think refactoring to use e.g. a `CROSS_TARGET_` prefix would make it clearer.

**Comment by akoeplinger** [comment]
We also need to backport this or some other fix to all servicing branches.

**Comment by jkotas** [comment]
> we're apparently using these variables not in the way that cmake intended (i.e. for cross compilation targets rather than the host OS). 

CMake documentation says that it is meant to represent target system: https://github.com/Kitware/CMake/commit/62cd3904bf22fd75a2502af09ef67f8458ce06e1#diff-186bb1bd28bd5ab49edaeb9820e3a5218c73bf02fec15bd71d221da5a130608bR4

**Comment by akoeplinger** [comment]
Ah ok, yeah then this approach looks good to me.

**Comment by jkotas** [comment]
> We also need to backport this or some other fix to all servicing branches.

I have triggered the backports in arcade repo. We can let the codeflow to take care of the rest in the servicing trees.
