### ISSUE TITLE
System.Collections.Generic.ValueListBuilder<T> does not implement Insert method correctly

### ISSUE THREAD

**Issue by assumenothing** [dotnet/runtime#97928]
### Description

While looking through the implementation of the internal generic ValueListBuilder type, I happened to notice that the `index` parameter of the `Insert(int index, scoped ReadOnlySpan<T> source)` method is only used for the debug argument validation. The current method implementation assumes that an index of zero is always used and will always insert the given data at the beginning of the list.

### Reproduction Steps

```csharp
using (var vlb = new ValueListBuilder<char>())
{
    vlb.Append("a bunch of coconuts");
    vlb.Insert(2, "lovely ");
    Console.WriteLine(vlb.AsSpan().ToString());
}
```

### Expected behavior

```
a lovely bunch of coconuts
```
The string "lovely" should be inserted just after the word "a".

### Actual behavior

```
lovely a bunch of coconuts
```
The string "lovely" is always inserted at the beginning of the string, regardless of the value of the `index` parameter.

### Configuration

- Windows 10.0.19045.0 x64
- .NET 8.0.1 x64
- Bug should not be specific to any platform/architecture.

**Comment by jkotas** [comment]
Introduced by https://github.com/dotnet/runtime/pull/84587/files#diff-a9e6f5bccd6400574df64428954305d28522b4e267355ab613aecc690c26f6dcR89-R101 

cc @stephentoub
