### PR TITLE
Forcibly disable use of libstdc++ C++11 ABI on Mono LLVM

### PR DESCRIPTION
**Pull request by directhex**
This feature is documented at https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html

Basically, the C++ ABI of the LLVM libraries needs to match the ABI of Mono. The CentOS7 images we build with on CI use the old (GCC 4 style) ABI by default, which ends up embedded in our LLVM nupkgs. This results in linker errors when building runtime.git on distributions which use the C++11 ABI instead, like Ubuntu 16.04+:

```
./.libs/libmini.a(llvm-jit.o): In function `mono_llvm_create_ee':
/home/directhex/Projects/runtime/src/mono/mono/mini/llvm-jit.cpp:447: undefined reference to `MonoEHFrameSymbol[abi:cxx11]'
./.libs/libmini.a(llvm-jit.o): In function `llvm::RTDyldMemoryManager::getSymbolAddress(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
/home/directhex/Projects/runtime/artifacts/obj/mono/Linux.x64.Debug/llvm/include/llvm/ExecutionEngine/RTDyldMemoryManager.h:84: undefined reference to `llvm::RTDyldMemoryManager::getSymbolAddressInProcess(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)'
./.libs/libmini.a(llvm-jit.o):(.data.rel.ro+0x90): undefined reference to `llvm::RTDyldMemoryManager::getPointerToNamedFunction(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool)'
```

Adding a define to `CXXFLAGS`, `-D _GLIBCXX_USE_CXX11_ABI=0` forces the build to use the same ABI as the LLVM nupkgs we produce.

The alternative would be to modify our LLVM build to enable the non-default-in-our-CentOS-images C++11 ABI.

### CODE REVIEW

**Comment by directhex** [comment]
Modifying the LLVM packages isn't really feasible, as the C++11 ABI requires libstdc++ 5.x, and CentOS 7 has 4.8

**Comment by lambdageek** [comment]
From some research: LLVM 6 is known to compile correctly with GCC 4.8, LLVM 9 makes it a soft-error (but will still compile corectly), and LLVM 10 will remove support (minimum GCC is 5.1).

Links:
* (llvm9 soft error) https://github.com/llvm/llvm-project/commit/388cefa78d4d2876ace1772eeea33d30ffc3fc37
* (llvm10 limit bump) https://github.com/llvm/llvm-project/commit/20644a9540c85f1d6af601fd7ca56f758831601e

**Review by lambdageek — APPROVED** [review]
LGTM, although I don't know the full details of mono.proj yet
