### PR TITLE
Reuse more Microsoft.Interop.SourceGeneration code in JS generators

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Reuse more of the code in Microsoft.Interop.SourceGeneration in the JavaScript source generators instead of duplicating the logic.

Refactor the JavaScript generators to use the GeneratedStatements type instead  of providing its own JSGeneratedStatements type.

Refactor the JSSignatureContext type to wrap a SignatureContext instead of providing a very similar surface area with a lot of duplicated code.

This PR also enhances the API surface of types in Microsoft.Interop.SourceGeneration to enable these sorts of scenarios.

### CODE REVIEW

**Comment by lewing** [comment]
the wasm built test failures are likely from https://github.com/dotnet/runtime/pull/74897 

@ericstj @danmoseley can you verify?

**Comment by ericstj** [comment]
Yes:
```
        [Debug_ts3wnijw.n3w] CSC : warning CS8784: Generator 'JSExportGenerator' failed to initialize. It will not contribute to the output and compilation errors may occur as a result. Exception was of type 'FileNotFoundException' with message 'Could not load file or assembly 'Microsoft.Interop.SourceGeneration, Version=42.42.42.42, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The system cannot find the file specified.' [C:\helix\work\workitem\e\Debug_ts3wnijw.n3w\Debug_ts3wnijw.n3w.csproj]
```

That's been fixed now, we can retrigger the pipeline.

File: src/libraries/System.Runtime.InteropServices.JavaScript/gen/JSImportGenerator/JSImportStubContext.cs [hunk 1]
```diff
@@ -2,21 +2,17 @@
...
 
 using Microsoft.CodeAnalysis;
-using Microsoft.CodeAnalysis.CSharp;
-using Microsoft.CodeAnalysis.CSharp.Syntax;
-using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;
 
 namespace Microsoft.Interop.JavaScript
 {
-    internal sealed class JSSignatureContext : IEquatable<JSSignatureContext>
+    internal sealed record JSSignatureContext : IEquatable<JSSignatureContext>
```
Comment (pavelsavara) [inline src/libraries/System.Runtime.InteropServices.JavaScript/gen/JSImportGenerator/JSImportStubContext.cs:15]: Please change the file name to match the type.

File: src/libraries/System.Runtime.InteropServices.JavaScript/gen/JSImportGenerator/JSImportStubContext.cs [hunk 2]
```diff
@@ -63,62 +34,22 @@ static bool IsSkipLocalsInitAttribute(AttributeData a)
...
-                            Attribute(ParseName(TypeNames.System_CodeDom_Compiler_GeneratedCodeAttribute),
-                                AttributeArgumentList(
-                                    SeparatedList(
-                                        new[]
-                                        {
-                                            AttributeArgument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(GeneratorName))),
-                                            AttributeArgument(LiteralExpression(SyntaxKind.StringLiteralExpression, Literal(GeneratorVersion)))
-                                        }))))));
-            }
+            string stubTypeFullName = method.ContainingType.ToDisplayString(new SymbolDisplayFormat(typeQualificationStyle: SymbolDisplayTypeQualificationStyle.NameAndContainingTypesAndNamespaces));
```
Comment (pavelsavara) [inline src/libraries/System.Runtime.InteropServices.JavaScript/gen/JSImportGenerator/JSImportStubContext.cs:46]: `NameAndContainingTypesAndNamespaces` is better than what we have in the `GetFullyQualifiedMethodName` and `s_typeNameFormat`, please unify it.

File: src/libraries/System.Runtime.InteropServices.JavaScript/gen/JSImportGenerator/JSExportCodeGenerator.cs [hunk 3]
```diff
@@ -98,6 +98,7 @@ public BlockSyntax GenerateJSExportBody()
             }
 
             tryStatements.AddRange(statements.NotifyForSuccessfulInvoke);
+            tryStatements.AddRange(statements.PinnedMarshal);
```
Comment (pavelsavara) [inline src/libraries/System.Runtime.InteropServices.JavaScript/gen/JSImportGenerator/JSExportCodeGenerator.cs:101]: I think `PinnedMarshal` is new stage since the JS gen inception, right ? It's good to have it.

File: src/libraries/System.Runtime.InteropServices/gen/LibraryImportGenerator/DefaultMarshallingInfoParser.cs [hunk 4]
```diff
@@ -0,0 +1,57 @@
+﻿// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using System;
+using System.Collections.Generic;
```
Comment (pavelsavara) [inline src/libraries/System.Runtime.InteropServices/gen/LibraryImportGenerator/DefaultMarshallingInfoParser.cs:5]: multiple unused `using`

File: src/libraries/System.Runtime.InteropServices.JavaScript/gen/JSImportGenerator/JSImportStubContext.cs [hunk 5]
```diff
@@ -2,21 +2,17 @@
 // The .NET Foundation licenses this file to you under the MIT license.
 
 using System;
-using System.Collections.Generic;
 using System.Collections.Immutable;
 using System.Diagnostics;
```
Comment (pavelsavara) [inline src/libraries/System.Runtime.InteropServices.JavaScript/gen/JSImportGenerator/JSImportStubContext.cs:6]: unused `using`

**Review by pavelsavara — APPROVED** [review]
love it!

File: src/libraries/System.Runtime.InteropServices.JavaScript/gen/JSImportGenerator/JSImportStubContext.cs (hunk 2 above)
Comment (maraf) [reply src/libraries/System.Runtime.InteropServices.JavaScript/gen/JSImportGenerator/JSImportStubContext.cs:46]: If we use `NameAndContainingTypesAndNamespaces` in `GetFullyQualifiedMethodName`, how do we determine which "." separate class names and which namespace names?

Context: mono special naming convention requires to separate class names with `/` and namespaces with '.'.

Comment (jkoritzinsky) [reply src/libraries/System.Runtime.InteropServices.JavaScript/gen/JSImportGenerator/JSImportStubContext.cs:46]: I think to meet the Mono naming requirements with `NameAndContainingTypesAndNamespaces` would require us to go back to using `ToDisplayParts()`. I'll leave that for now since we just moved away from that.

File: src/libraries/System.Runtime.InteropServices.JavaScript/gen/JSImportGenerator/JSExportCodeGenerator.cs (hunk 3 above)
Comment (jkoritzinsky) [reply src/libraries/System.Runtime.InteropServices.JavaScript/gen/JSImportGenerator/JSExportCodeGenerator.cs:101]: Yep! It was added to help generalize some of the support used with the custom marshaller design.

**Comment by jkoritzinsky** [comment]
Failures are https://github.com/dotnet/runtime/issues/75329 and https://github.com/dotnet/runtime/issues/75378

Merging this in
