### ISSUE TITLE
.NET 9 Emscripten 3.1.56 SDL3

### ISSUE THREAD

**Issue by LloydJHowarth** [dotnet/runtime#120187]
I've got a working .NET 9 (wasm-tools) project using SDL2. However I've been thinking about moving towards SDL3 for future development. I noticed that Emscripten 4.0.15 has a new SDL3 port available but since we are locked at Emscripten 3.1.56 I decided to backport the sdl3.py file to work and build with Emscripten 3.1.56. I've now produced a libSDL3.a file that I can include in my project the same way I did with the libSDL2.a file as a NativeFileReference. The project builds successfully with no major issues. At runtime I get SDL Initialized, SDL Events and can call any other SDL related functions, even create renderer. The only thing I can't do is create a window.

Running this code

>         Console.WriteLine("Initialize");
>         bool init = SDL.SDL_Init(SDL.SDL_InitFlags.SDL_INIT_VIDEO | SDL.SDL_InitFlags.SDL_INIT_AUDIO);
>         Console.WriteLine($"SDL Initialize: {init}");
> 
>         window = SDL.SDL_CreateWindow("SDL3 Window", 600, 800, SDL.SDL_WindowFlags.SDL_WINDOW_HIGH_PIXEL_DENSITY);
>         Console.WriteLine($"SDL Window: {window != IntPtr.Zero}");
>         
>         renderer = SDL.SDL_CreateRenderer(window, String.Empty);
>         Console.WriteLine($"SDL Renderer: {renderer != IntPtr.Zero}");

I get this output:

> dotnet.native.4f59ihtvzf.js:1819 Initialize
> dotnet.native.4f59ihtvzf.js:1819 SDL Initialize: True
> main.js:28 Error: RuntimeError: null function or function signature mismatch
>     at dotnet.native.wasm.do_icall (dotnet.native.wasm-04a687ea:0x115c3d)
>     at dotnet.native.wasm.do_icall_wrapper (dotnet.native.wasm-04a687ea:0x111fb3)
>     at dotnet.native.wasm.mono_interp_exec_method (dotnet.native.wasm-04a687ea:0x103207)
>     at dotnet.native.wasm.interp_runtime_invoke (dotnet.native.wasm-04a687ea:0x1134be)
>     at dotnet.native.wasm.mono_jit_runtime_invoke (dotnet.native.wasm-04a687ea:0x2324a0)
>     at dotnet.native.wasm.do_runtime_invoke (dotnet.native.wasm-04a687ea:0x1f2430)
>     at dotnet.native.wasm.mono_runtime_try_invoke (dotnet.native.wasm-04a687ea:0x1f2eb0)
>     at dotnet.native.wasm.mono_runtime_invoke (dotnet.native.wasm-04a687ea:0x1f5ad4)
>     at dotnet.native.wasm.mono_wasm_invoke_jsexport (dotnet.native.wasm-04a687ea:0x3b074e)
>     at dotnet.native.4f59ihtvzf.js:811:12
> mainloop @ main.js:28
> requestAnimationFrame
> (anonymous) @ main.js:34Understand this error
> dotnet.native.4f59ihtvzf.js:1819 Running
> 2dotnet.native.4f59ihtvzf.js:1819 SDL Event: SDL_EVENT_AUDIO_DEVICE_ADDED
> 35dotnet.native.4f59ihtvzf.js:1819 Running
> :7205/favicon.ico:1  Failed to load resource: the server responded with a status of 404 ()Understand this error
> 1276dotnet.native.4f59ihtvzf.js:1819 Running

As you can see SDL initialized, at the bottom SDL Events are being called. But when we attempt to create a window it throws a runtime error: null function or function signature mismatch. At first I thought it may be an issue with the SDL_CreateWindow method but I don't think it is.

Trying to track the origin of the error at dotnet.native.4f59ihtvzf.js:811:12:

```
function createExportWrapper(name) {
  return (...args) => {
  assert(runtimeInitialized, `native function \`${name}\` called before runtime initialization`);
  assert(!runtimeExited, `native function \`${name}\` called after runtime exit (use NO_EXIT_RUNTIME to keep it alive after main() exits)`);
  var f = wasmExports[name];
  assert(f, `exported native function \`${name}\` not found`);
  return f(...args); <--- This is line (811)
};
```

Which means the function didn't throw on assert(f, `exported native function \`${name}\` not found`); so the method was found.

Looking at dotnet.native.js.symbols:

> 1713:SDL_CreateWindow

The method is there.

```
SDL_CreateWindow in C
SDL_Window * SDL_CreateWindow(const char *title, int w, int h, SDL_WindowFlags flags);

SDL_CreateWindow in C#
[LibraryImport(nativeLibName, StringMarshalling = StringMarshalling.Utf8)]
[UnmanagedCallConv(CallConvs = [typeof(CallConvCdecl)])]
public static partial IntPtr SDL_CreateWindow(string title, int w, int h, SDL_WindowFlags flags);
```

Here is my main.js & index.html setup as well for more information.

Index.html
```
<!DOCTYPE html>

<html>

    <head>
        <title>SDL3</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script type='module' src="./main.js"></script>
    </head>
    
    <body>
        <canvas id="canvas"></canvas>
    </body>

</html>
```

Main.js
```
import { dotnet } from './_framework/dotnet.js'

const { setModuleImports, getAssemblyExports, getConfig } = await dotnet
    .withDiagnosticTracing(false)
    .withApplicationArgumentsFromQuery()
    .create();

const config = getConfig();
const exports = await getAssemblyExports(config.mainAssemblyName);
const main = exports.Program.Main;

var canvas = document.getElementById("canvas");
dotnet.instance.Module.canvas = canvas;

// Commented out to debug
// Use this normally but for now just use mainloop function which doesn't stop on exceptions.
// dotnet.instance.Module.setMainLoop(entry);

function mainloop()
{
    try
    {
        main();
    }
    catch (e)
    {
        console.error("Error:", e);
    }
    
    requestAnimationFrame(mainloop);
}

requestAnimationFrame(mainloop);
```

I've even tried modifying my SDL_CreateWindow bindings to see if there was a mismatch but they already map correctly to the C Headers. This works on all platforms as well such as Window, Linux, MacOS but not dotnet using Emscripten. This is working using only C + Emscripten.

I don't think it is the SDL_CreateWindow function that's throwing the error but maybe something else internal that gets called when trying to call SDL_CreateWindow but I could be wrong.

Any help would be appreciated.

**Comment by LloydJHowarth** [comment]
Here is my main.js & index.html setup as well for more information.

Index.html
```
<!DOCTYPE html>

<html>

    <head>
        <title>SDL3</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script type='module' src="./main.js"></script>
    </head>
    
    <body>
        <canvas id="canvas"></canvas>
    </body>

</html>
```


Main.js
```
import { dotnet } from './_framework/dotnet.js'

const { setModuleImports, getAssemblyExports, getConfig } = await dotnet
    .withDiagnosticTracing(false)
    .withApplicationArgumentsFromQuery()
    .create();

const config = getConfig();
const exports = await getAssemblyExports(config.mainAssemblyName);
const main = exports.Program.Main;

var canvas = document.getElementById("canvas");
dotnet.instance.Module.canvas = canvas;

// Commented out to debug
// Use this normally but for now just use mainloop function which doesn't stop on exceptions.
// dotnet.instance.Module.setMainLoop(entry);

function mainloop()
{
    try
    {
        main();
    }
    catch (e)
    {
        console.error("Error:", e);
    }
    
    requestAnimationFrame(mainloop);
}

requestAnimationFrame(mainloop);
```
