### ISSUE TITLE
CS1620 Usage of Unsafe.AsRef(in) no longer working with 8.0 rc1?

### ISSUE THREAD

**Issue by xoofx** [dotnet/runtime#93251]
Hey,

With latest .NET SDK used `8.0.100-rc.1.23463.5`, the `Unsafe.AsRef(in)` is no longer working with latest Roslyn. For the following code:

```c#
using System.Runtime.CompilerServices;
public static class Tester {
    public static ref T GetAsRef<T>(in T value) => ref Unsafe.AsRef(in value);
}
```

```
1>C:\code\tmp\TestDebugging\TestDebugging\Tester.cs(4,72,4,77): error CS1620: Argument 1 must be passed with the 'ref' keyword
```

The same used to work fine with previous versions (sharplab [here](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA+ABADAAgwRgDoAlAVwDsAXASwFsZCBhCWgB2oBsYoBlbgN2pgYAZwDcAWABQGAMx58SPACYcAFVGVu0gN7ScBvPIJLYAM3U4A4jEoBBEcRhmAPGoB8ACmrlL/AIYcpDAAlDgAvO445jgAquQi/mYMDk5m3r4BQaGSUgC+QA))

Is it a known issue? (Couldn't find any recent issue related to this)

**Comment by xoofx** [comment]
Oh, I'm on Visual Studio `17.7.3`, and when compiling from the command line I don't have the error, but I get it when compiling from the IDE.

It still says that it is using it from the IDE

```
1>C:\Program Files\dotnet\sdk\8.0.100-rc.1.23463.5\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.RuntimeIdentifierInference.targets(311,5): message NETSDK1057: You are using a preview version of .NET. See: https://aka.ms/dotnet-support-policy
```

So the resolution of the compiler is different in the IDE, even when doing a regular build? Which version does it take then?

**Comment by tannergooding** [comment]
Yes, the IDE compiler comes from VS and can be out of sync with the IDE used by your build.

In such a case, you may see `IntelliSense` diagnostics that do not match the diagnostics reported by your actual build (which likely uses the .NET SDK bits).

Typically preview versions of C# require preview versions of VS for things to work as expected; otherwise, edge cases like this can crop up.

**Comment by tannergooding** [comment]
> It still says that it is using it from the IDE

What gets shown in `Build` output is what's used by the actual build, not what's used by `IntelliSense`.

If you add in `#error version` you may see a different number reported in different places. Alternatively, you can try looking at the `Help->About Visual Studio->C# Tools`.

**Comment by xoofx** [comment]
Oh right, I think I asked a similar question years ago actually about a similar problem 😅 

Yeah, the version from the command line is giving me

```
error CS8304: Compiler version: '4.8.0-1.23419.1 (5fcefbef)'
```

but from the IDE it gives me:

```
error CS8304: Compiler version: '4.7.0-3.23416.8 (43b0b05c)'. Language version: preview.
```

As many C# 12 features had been working so far, I assumed that I was using the latest, but actually not...

Sorry for the noise! 🙂

**Comment by xoofx** [comment]
Hey, I have just 2 questions to clarify my understanding:

1. When we configure to use a rc1 SDK like this (through global.json), do I understand correctly that when running from VS, it will still use a specific version of Roslyn, even if the MSBuild part is still using the one coming from the configured SDK?
2. If only Roslyn is overridden by VS, how is it done? (e.g env variable?)
