### PR TITLE
Fix unconditional success in CLR tests

### PR DESCRIPTION
**Pull request by tomeksowi**
Test introduced in #100289 failed the build of CLR tests for e.g. RISC-V:
```
/runtime/src/tests/Loader/classloader/explicitlayout/Regressions/100220/Runtime_100220.cs(15,23): error XUW1002: Tests should not unconditionally return 100. Convert to a void return.
```

Part of #84834, cc @dotnet/samsung

### CODE REVIEW

**Comment by jakobbotsch** [comment]
This isn't the first time an issue like this makes it through CI... #94146 and #94531 are similar instances. We should figure out why this doesn't fail in CI. cc @markples

**Review by gbalykov — APPROVED** [review]

**Review by yurai007 — APPROVED** [review]

**Review by Bajtazar — APPROVED** [review]

**Review by sirntar — APPROVED** [review]

**Review by jakobbotsch — APPROVED** [review]

**Comment by markples** [comment]
Question for @tomeksowi and any others who have hit these - what are you doing to expose this?  Are you possibly running on a branch with a very old dotnet/main?

I believe that #91235 disabled the analyzers due to the addition of `'$(_CLRTEstNeedsToRun)' == 'true'` in `src/test/Directory.Build.targets`.  @ivdiazsa any chance that you remember why you needed to add this?  I imagine that the proper fix is to separate the analyzers into a pure analyzer phase as @jkoritzinsky as suggested in the past.  I don't know how to do this and think it would probably take me a while to figure out - if there was a pattern that I could copy then I could probably do it easily.

**Comment by gbalykov** [comment]
@markples for both cases when I fixed similar ones our CI built latest main branch from scratch in clean cloned repo, so all nugets and sdk were downloaded during build. Maybe the way we build has some effect, but I'm not exactly sure right now for which configuration we've observed this. It probably was smth like https://github.com/dotnet/runtime/issues/97791#issuecomment-1980576184.

**Comment by markples** [comment]
Thank you @gbalykov - the BuildAsStandalone is the difference.  To be clear, this isn't incorrect on your part, but it is different from the CI jobs and most local builds.  It's useful to know this because it is consistent with my theory above.
