### PR TITLE
Implement hash and HMAC stream one shots

### LINKED ISSUE #62489: [API Proposal]: One shot hashing of `Stream`
### Background and motivation

As of .NET 5 (Hash) and .NET 6 (HMAC) we have static one-shots for computing the hash of bytes, either in the form of an array of a `ReadOnlySpan<byte>`.

This one shot I think is a good direction for .NET. To re-cap what we have today in terms of APIs:

1. `HASHALG.HashData` - one shot of fixed-length buffers, array or span
2. `IncrementalHash` - updatable hash
3. `HASHALG.Create` - .NET Framework 1.0 design

My personal belief is that number three should be mostly de-emphasized for common use cases. One shots should use option one, and incremental should use two. `Create` should be there for cases where polymorphic behavior is desired, if ever.

There is one case remaining (I believe) where option one and two don't handle as well as three: hashing streams, because the `HashAlgorithm` instances have `ComputeHash(Stream stream)`

It's not uncommon to need to hash a stream all in one go (thus still a one-shot). I would propose that these should also be one shots to further reduce the need for option three.

As a matter of implementation, the goal is not to necessarily use platform APIs to produce the most optimal hashing API (though we can certainly do our best to optimize some certain situations). Rather the goal is to provide an API surface that does not require developers to manage an instance of a hash object.

### API Proposal

```C#
namespace System.Security.Cryptography {
    public abstract partial class MD5 {
        public static byte[] HashData(Stream source);
        public static int HashData(Stream source, Span<byte> destination);

        public static async ValueTask<byte[]> HashDataAsync(Stream source, CancellationToken cancellationToken = default);
        public static async ValueTask<int> HashDataAsync(Stream source, Memory<byte> destination, CancellationToken cancellationToken = default);
    }

    public abstract partial class SHA1 {
        public static byte[] HashData(Stream source);
        public static int HashData(Stream source, Span<byte> destination);

        public static async ValueTask<byte[]> HashDataAsync(Stream source, CancellationToken cancellationToken = default);
        public static async ValueTask<int> HashDataAsync(Stream source, Memory<byte> destination, CancellationToken cancellationToken = default);
    }

    public abstract partial class SHA256 {
        public static byte[] HashData(Stream source);
        public static int HashData(Stream source, Span<byte> destination);

        public static async ValueTask<byte[]> HashDataAsync(Stream source, CancellationToken cancellationToken = default);
        public static async ValueTask<int> HashDataAsync(Stream source, Memory<byte> destination, CancellationToken cancellationToken = default);
    }

    public abstract partial class SHA384 {
        public static byte[] HashData(Stream source);
        public static int HashData(Stream source, Span<byte> destination);

        public static async ValueTask<byte[]> HashDataAsync(Stream source, CancellationToken cancellationToken = default);
        public static async ValueTask<int> HashDataAsync(Stream source, Memory<byte> destination, CancellationToken cancellationToken = default);
    }

    public abstract partial class SHA512 {
        public static byte[] HashData(Stream source);
        public static int HashData(Stream source, Span<byte> destination);

        public static async ValueTask<byte[]> HashDataAsync(Stream source, CancellationToken cancellationToken = default);
        public static async ValueTask<int> HashDataAsync(Stream source, Memory<byte> destination, CancellationToken cancellationToken = default);
    }

    public abstract partial class HMACMD5 {
        public static byte[] HashData(ReadOnlySpan<byte> key, Stream source);
        public static int HashData(ReadOnlySpan<byte> key, Stream source, Span<byte> destination);

        public static async ValueTask<byte[]> HashDataAsync(ReadOnlyMemory<byte> key, Stream source, CancellationToken cancellationToken = default);
        public static async ValueTask<int> HashDataAsync(ReadOnlyMemory<byte> key, Stream source, Memory<byte> destination, CancellationToken cancellationToken = default);
    }

    public abstract partial class HMACSHA1 {
        public static byte[] HashData(ReadOnlySpan<byte> key, Stream source);
        public static int HashData(ReadOnlySpan<byte> key, Stream source, Span<byte> destination);

        public static async ValueTask<byte[]> HashDataAsync(ReadOnlyMemory<byte> key, Stream source, CancellationToken cancellationToken = default);
        public static async ValueTask<int> HashDataAsync(ReadOnlyMemory<byte> key, Stream source, Memory<byte> destination, CancellationToken cancellationToken = default);
    }

    public abstract partial class HMACSHA256 {
        public static byte[] HashData(ReadOnlySpan<byte> key, Stream source);
        public static int HashData(ReadOnlySpan<byte> key, Stream source, Span<byte> destination);

        public static async ValueTask<byte[]> HashDataAsync(ReadOnlyMemory<byte> key, Stream source, CancellationToken cancellationToken = default);
        public static async ValueTask<int> HashDataAsync(ReadOnlyMemory<byte> key, Stream source, Memory<byte> destination, CancellationToken cancellationToken = default);
    }

    public abstract partial class HMACSHA384 {
        public static byte[] HashData(ReadOnlySpan<byte> key, Stream source);
        public static int HashData(ReadOnlySpan<byte> key, Stream source, Span<byte> destination);

        public static async ValueTask<byte[]> HashDataAsync(ReadOnlyMemory<byte> key, Stream source, CancellationToken cancellationToken = default);
        public static async ValueTask<int> HashDataAsync(ReadOnlyMemory<byte> key, Stream source, Memory<byte> destination, CancellationToken cancellationToken = default);
    }

    public abstract partial class HMACSHA512 {
        public static byte[] HashData(ReadOnlySpan<byte> key, Stream source);
        public static int HashData(ReadOnlySpan<byte> key, Stream source, Span<byte> destination);

        public static async ValueTask<byte[]> HashDataAsync(ReadOnlyMemory<byte> key, Stream source, CancellationToken cancellationToken = default);
        public static async ValueTask<int> HashDataAsync(ReadOnlyMemory<byte> key, Stream source, Memory<byte> destination, CancellationToken cancellationToken = default);
    }
}
```

### API Usage

```C#
static void Example1() {
    using (FileStream fs = File.Open("/please/hash/me", FileMode.Open)) {
        byte[] fileHash = SHA256.HashData(fs);
    }
}

static void Example2() {
    using (FileStream fs = File.Open("/please/hash/me", FileMode.Open)) {
        Span<byte> buffer = stackalloc byte[32];
        int written = SHA256.TryHashData(fs, buffer);
    }
}

static async Task Example3() {
    using (FileStream fs = File.Open("/please/hash/me", FileMode.Open)) {
        byte[] fileHash = await SHA256.HashDataAsync(fs);
    }
}

static async Task Example4() {
    using (FileStream fs = File.Open("/please/hash/me", FileMode.Open)) {
        Memory<byte> existingBuffer = default; // Something reasonable here.
        int written = await SHA256.TryHashDataAsync(fs, existingBuffer);
    }
}
```

### Alternative Designs

"Do nothing" is likely the best alternative to this. It's possible to do this today using `IncrementalHash` (read from the stream, update, done) or `HASHALG.ComputeHash{Async}`. Both of these options however require managing an instance of the hash object.

### PR DESCRIPTION
**Pull request by vcsjones**
This implements hashing and HMAC statics for streams. Additionally,
"LiteHmac" and "LiteHash" were introduced. The existing HMAC and hash
provider functionality do some bookkeeping we don't need for resetting.
Since we do not need to use these hash handles after the digest has
been finalized, resetting is unnecessary work. For HMAC, that also means
keeping a copy of the key around for some implementations which we don't
need to do.

The LiteHash and LiteHmac types are implemented as structs with a common
interface. To avoid boxing, generics are used and constrained to the interface
where possible.

The Browser implementation just defers to the existing HashDispenser rather
than do anything novel.

Closes #62489.

### CODE REVIEW

**Comment by vcsjones** [comment]
Draft to get feedback from CI, and this is going to conflict with #63685. That should be merged first and I will resolve conflicts.

**Comment by vcsjones** [comment]
This does not implement any shortcuts for some streams. We could possibly do this for `MemoryStream` (`TryGetBuffer`) and `UnmanagedMemoryStream` (`PositionPointer`). That can be done in a follow-up PR rather than make this PR bigger.

File: src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/HMACMD5.cs [hunk 1]
```diff
@@ -155,6 +158,181 @@ public static bool TryHashData(ReadOnlySpan<byte> key, ReadOnlySpan<byte> source
...
+        ///   <paramref name="source" /> does not support reading.
+        /// </exception>
+        public static ValueTask<byte[]> HashDataAsync(ReadOnlyMemory<byte> key, Stream source, CancellationToken cancellationToken = default)
+        {
+            if (source is null)
+                return ValueTask.FromException<byte[]>(new ArgumentNullException(nameof(source)));
+
+            if (!source.CanRead)
+                return ValueTask.FromException<byte[]>(
+                    new ArgumentException(SR.Argument_StreamNotReadable, nameof(source)));
```
Comment (stephentoub) [inline src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/HMACMD5.cs:257]: We typically don't wrap user errors (e.g. argument exceptions) in tasks.

Comment (vcsjones) [reply src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/HMACMD5.cs]: Ha, that makes sense. Fixed.

File: src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/LiteHashProvider.cs [hunk 2]
```diff
@@ -0,0 +1,191 @@
...
+            }
+
+            LiteHmac hash = CreateHmac(hashAlgorithmId, key);
+            return ProcessStreamAsync(hash, source, cancellationToken);
+        }
+
+        /// This takes ownership of the hash parameter and disposes of it when done.
+        private static int ProcessStream<T>(T hash, Stream source, Span<byte> destination) where T : ILiteHash
+        {
+            byte[] rented = CryptoPool.Rent(4096);
```
[the remark this answers is not in the document]
Comment (vcsjones) [reply src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/LiteHashProvider.cs]: I don't think it would matter in practice, the safe handles would get finalized. But I don't see a reason why we can't address it anyway, so, fixed.

File: src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/LiteHashProvider.cs [hunk 3]
```diff
@@ -0,0 +1,195 @@
...
+            {
+                return ValueTask.FromCanceled<byte[]>(cancellationToken);
+            }
+
+            LiteHmac hash = CreateHmac(hashAlgorithmId, key);
+            return ProcessStreamAsync(hash, source, cancellationToken);
+        }
+
+        /// This takes ownership of the hash parameter and disposes of it when done.
+        private static int ProcessStream<T>(T hash, Stream source, Span<byte> destination) where T : ILiteHash
```
Comment (bollhals) [inline src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/LiteHashProvider.cs:117]: I've done something similar (in readonly struct + generic constrained to interface) in a library I contribute to and while it works, any method called on that interface will force a defensive copy, since the compiler is not able to recognize that the struct method itself is readonly. I think it only sees the interface and thus decides on a defensive copy. I'm also not sure anymore whether without the in modifier as you have here, the compiler is able to figure it out properly or not.

Based on the size of the structs used, I assume it's not as relevant here, just wanted to mention it.

File: src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/HMACSHA256.cs [hunk 4]
```diff
@@ -163,6 +165,176 @@ public static bool TryHashData(ReadOnlySpan<byte> key, ReadOnlySpan<byte> source
...
+        /// </exception>
+        public static ValueTask<int> HashDataAsync(
+            ReadOnlyMemory<byte> key,
+            Stream source,
+            Memory<byte> destination,
+            CancellationToken cancellationToken = default)
+        {
+            ArgumentNullException.ThrowIfNull(source);
+
+
```
Comment (bartonjs) [inline src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/HMACSHA256.cs:322]: Nit: Too many blank lines

```suggestion

```

File: src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/LiteHash.Apple.cs [hunk 5]
```diff
@@ -0,0 +1,163 @@
...
+        }
+
+        private static LiteHmac CreateHmac(string hashAlgorithmId, ReadOnlySpan<byte> key)
+        {
+            PAL_HashAlgorithm algorithm = HashAlgorithmNames.HashAlgorithmToPal(hashAlgorithmId);
+            return new LiteHmac(algorithm, key);
+        }
+    }
+
+    internal readonly struct LiteHash : ILiteHash
```
Comment (bartonjs) [inline src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/LiteHash.Apple.cs:26]: LiteHash looks a lot like HashProvider.  Why do we need both?

File: src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/LiteHash.Windows.cs [hunk 6]
```diff
@@ -0,0 +1,173 @@
+// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+using Microsoft.Win32.SafeHandles;
+using System.Diagnostics;
+using System.Runtime.InteropServices;
+
+using NTSTATUS = Interop.BCrypt.NTSTATUS;
+using BCryptOpenAlgorithmProviderFlags = Interop.BCrypt.BCryptOpenAlgorithmProviderFlags;
+using BCryptCreateHashFlags = Interop.BCrypt.BCryptCreateHashFlags;
```
Comment (bartonjs) [inline src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/LiteHash.Windows.cs:10]: Sorted looks better to my eye.

```suggestion
using BCryptCreateHashFlags = Interop.BCrypt.BCryptCreateHashFlags;
using BCryptOpenAlgorithmProviderFlags = Interop.BCrypt.BCryptOpenAlgorithmProviderFlags;
using NTSTATUS = Interop.BCrypt.NTSTATUS;
```

File: src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/MD5.cs [hunk 7]
```diff
@@ -112,6 +115,133 @@ public static bool TryHashData(ReadOnlySpan<byte> source, Span<byte> destination
...
+        /// <exception cref="ArgumentNullException">
+        ///   <paramref name="source" /> is <see langword="null" />.
+        /// </exception>
+        /// <exception cref="ArgumentException">
+        ///   <paramref name="source" /> does not support reading.
+        /// </exception>
+        public static ValueTask<byte[]> HashDataAsync(Stream source, CancellationToken cancellationToken = default)
+        {
+            if (source is null)
+                return ValueTask.FromException<byte[]>(new ArgumentNullException(nameof(source)));
```
Comment (bartonjs) [inline src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/MD5.cs:189]: The HMACs all threw these as preconditions instead of results.  Preconditions seems correct.

```suggestion
                throw new ArgumentNullException(nameof(source));
```

File: src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/MD5.cs [hunk 8]
```diff
@@ -112,6 +115,133 @@ public static bool TryHashData(ReadOnlySpan<byte> source, Span<byte> destination
...
+
+            if (!source.CanRead)
+                return ValueTask.FromException<byte[]>(
+                    new ArgumentException(SR.Argument_StreamNotReadable, nameof(source)));
```
Comment (bartonjs) [inline src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/MD5.cs:193]: throw

File: src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/MD5.cs [hunk 9]
```diff
@@ -112,6 +115,133 @@ public static bool TryHashData(ReadOnlySpan<byte> source, Span<byte> destination
...
+            if (source is null)
+                return ValueTask.FromException<int>(new ArgumentNullException(nameof(source)));
+
+            if (destination.Length < HashSizeInBytes)
+                return ValueTask.FromException<int>(
+                    new ArgumentException(SR.Argument_DestinationTooShort, nameof(destination)));
+
+            if (!source.CanRead)
+                return ValueTask.FromException<int>(
+                    new ArgumentException(SR.Argument_StreamNotReadable, nameof(source)));
```
Comment (bartonjs) [inline src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/MD5.cs:235]: throw :smile:

Comment (vcsjones) [reply src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/MD5.cs:235]: 🤔 thought I fixed all of these from Steve's feedback. Maybe I didn't push something.

File: src/libraries/System.Security.Cryptography/tests/HashAlgorithmTestDriver.cs [hunk 10]
```diff
@@ -320,6 +374,85 @@ protected void VerifyRepeating(string input, int repeatCount, string output)
...
+        {
+            AssertExtensions.Throws<ArgumentException>("destination", () => HashData(Stream.Null, Span<byte>.Empty));
+        }
+
+        [Fact]
+        public async Task HashDataAsync_Null_Stream_Throws()
+        {
+            await AssertExtensions.ThrowsAsync<ArgumentNullException>(
+                "source",
+                async () => await HashDataAsync((Stream)null, cancellationToken: default));
```
Comment (bartonjs) [inline src/libraries/System.Security.Cryptography/tests/HashAlgorithmTestDriver.cs:425]: The argument validation ones can/should be synchronous.

```suggestion
            Assert.Throws<ArgumentNullException>(
                "source",
                HashDataAsync((Stream)null, cancellationToken: default));
```

File: src/libraries/System.Security.Cryptography/tests/Sha384Tests.cs [hunk 11]
```diff
@@ -42,7 +118,7 @@ public void Sha384_NistShaAll_1()
         }
 
         [Fact]
-        public void Sha256_Fips180_MultiBlock()
+        public void SHA384_Fips180_MultiBlock()
```
Comment (bartonjs) [inline src/libraries/System.Security.Cryptography/tests/Sha384Tests.cs:121]: Why change the casing here?  All of the rest of the methods are little-H/little-A

File: src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/LiteHash.Apple.cs (hunk 5 above)
Comment (vcsjones) [reply src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/LiteHash.Apple.cs:26]: * LiteHmac doesn't keep a key copy for resets
* LiteHash / LiteHmac don't reset once used.
* LiteHash / LiteHmac don't keep track of whether operations are in-flight with `_running`
* It's a struct

_Could we put a `Reset` on these (taking the key for the HMAC variant) and have `HashProvider` wrap those?_

Maybe. That's kind of what I did for the symmetric one-shots (replacing IV for HMAC keys). I avoided that here because I felt that the structs were simple enough on their own, really just a few methods on a `SafeHandle`. De-duplicating it would just mean another level of indirection on the HashProviders to the Lite ones.

File: src/libraries/System.Security.Cryptography/tests/Sha384Tests.cs (hunk 11 above)
Comment (vcsjones) [reply src/libraries/System.Security.Cryptography/tests/Sha384Tests.cs:121]: Ah, well, it was called out as SHA**256** instead of SHA**384** and I guess my fingers just did the wrong thing while fixing the algorithm size. Will fix.

File: src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/LiteHash.Apple.cs (hunk 5 above)
Comment (bartonjs) [reply src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/LiteHash.Apple.cs:26]: Hm.  Feels like the HashProvider could just have a LiteHash as a field, and then manage the state on top of that.

If it doesn't nest easily, then it's not a whole lot of duplication... but it's still nice to only need to make changes N times (Windows, Unix, Android, Apple OSes, Browser) instead of N * M (when M > 1)... so I have to ask :smile:

File: src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/MD5.cs (hunk 9 above)
Comment (bartonjs) [reply src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/MD5.cs:235]: Looks like only MD5 got missed.  Probably just missed it as the only hash to not start with S.

File: src/libraries/System.Security.Cryptography/tests/Sha384Tests.cs (hunk 11 above)
Comment (bartonjs) [reply src/libraries/System.Security.Cryptography/tests/Sha384Tests.cs:121]: Ah.  Clearly my internal diffing algorithm stopped at the first change. :)

File: src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/MD5.cs (hunk 9 above)
Comment (vcsjones) [reply src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/MD5.cs:235]: Ah I missed MD5 because I'm a dummy.

File: src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/LiteHash.Apple.cs (hunk 5 above)
Comment (vcsjones) [reply src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/LiteHash.Apple.cs:26]: This "works" for Unix / Android and Apple. It works less-so to me for Windows. The Windows one was already somewhat specialized, and it does upfront work to determine if the platform supports usable CNG hashes.

What didn't work either was a single `HashProvider` for multiple platforms, even if they wrapped their own `LiteHash`, since everyone wants their own state.

If the last two commits are just seem like noise without pushing far enough in to the "make it less duplicated", I can revert or drop them.

The alternative, if we really do not like the duplication is to make the stream one shots allocate a bunch more and abandon the lite hashes altogether. Though I believe the one-shots should remain as light as reasonably possible, even if they do end up allocating a safe-handle or two.

**Review by bartonjs — APPROVED** [review]

File: src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/LiteHash.Apple.cs (hunk 5 above)
Comment (bartonjs) [reply src/libraries/System.Security.Cryptography/src/System/Security/Cryptography/LiteHash.Apple.cs:26]: While "no duplication" would be ideal, "less duplication" is at least virtuous.  Thanks for pursuing it.
