### PR TITLE
Fix debug build of libraries tests

### PR DESCRIPTION
**Pull request by gbalykov**
Without this change there's error:

```
/home/runtime/src/libraries/System.Net.Security/tests/FunctionalTests/TestConfiguration.cs(29,158): error CS0103: The name 'RuntimeInformation' does not exist in the current context [/home/runtime/src/libraries/System.Net.Security/tests/FunctionalTests/System.Net.Security.Tests.csproj::TargetFramework=net11.0-unix]
```

This is introduced in https://github.com/dotnet/runtime/pull/129479

### CODE REVIEW

**Comment by gbalykov** [comment]
cc @am11

**Comment by am11** [comment]
Ops, it was in a subsequent commit I was cherry-picking from a branch.

**Review by am11 — APPROVED** [review]

**Review by vcsjones — APPROVED** [review]

**Comment by vcsjones** [comment]
/ba-g verified change fixes build; merging now because the only lane waiting has been timing out and we don't want to wait for a timeout to fix a build break.
