### ISSUE TITLE
Libraries build fail

### ISSUE THREAD

**Issue by gbalykov** [dotnet/runtime#62574]
Failed after https://github.com/dotnet/runtime/pull/62507

```sh
./build.sh --arch x64 --runtimeConfiguration Release --librariesConfiguration Release --subset clr+libs
```
output:
```
Build FAILED.

CSC : error CS2001: Source file '/home/z/Dev/runtime/src/libraries/Common/src/Interop/Interop.ZLib.cs' could not be found. [/home/z/Dev/runtime/src/libraries/System.IO.Compression/src/System.IO.Compression.csproj]
CSC : error CS2001: Source file '/home/z/Dev/runtime/src/libraries/Common/src/Interop/Interop.ZLib.cs' could not be found. [/home/z/Dev/runtime/src/libraries/System.Net.WebSockets/src/System.Net.WebSockets.csproj]
    0 Warning(s)
    2 Error(s)
```

Simple rename `src/libraries/Common/src/Interop/Interop.zlib.cs` -> `src/libraries/Common/src/Interop/Interop.ZLib.cs` needed?
