### PR TITLE
fix compilation on freebsd

### PR DESCRIPTION
**Pull request by wfurt**
regression caused by #34334:
```
Scanning dependencies of target cee_wks
/home/furt/github/wfurt-runtime2/src/coreclr/src/gc/unix/cgroup.cpp:30:10: fatal error: 'sys/vfs.h' file not found
#include <sys/vfs.h>
         ^~~~~~~~~~~
1 error generated.
src/gc/CMakeFiles/clrgc.dir/build.make:296: recipe for target 'src/gc/CMakeFiles/clrgc.dir/unix/cgroup.cpp.o' failed
make[2]: *** [src/gc/CMakeFiles/clrgc.dir/unix/cgroup.cpp.o] Error 1
```

It may be better long run include vfs.h only if exist but this is fix follows current pattern based on OS.

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Review by janvorli — APPROVED** [review]
LGTM, thank you!
