### ISSUE TITLE
.NET Framework build appears broken

### ISSUE THREAD

**Issue by vcsjones** [dotnet/runtime#130886]
I am seeing this build failure in PRs, such as https://github.com/dotnet/runtime/pull/130875. From the [build log](https://dev.azure.com/dnceng-public/public/_build/results?buildId=1512625&view=logs&jobId=0b6dc52c-e488-59ef-e44c-bdccc8ffc4ce&j=0b6dc52c-e488-59ef-e44c-bdccc8ffc4ce&t=a8fdb3c4-bfc0-5388-f6fb-933b17be0186)

```
D:\a\_work\1\s\src\libraries\Microsoft.Extensions.Caching.Abstractions\tests\TrimmingTests\HybridCacheEntryOptionsAccessorTest.cs(17,6): error CS0246: The type or namespace name 'UnsafeAccessorAttribute' could not be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\libraries\Microsoft.Extensions.Caching.Abstractions\tests\Microsoft.Extensions.Caching.Abstractions.Tests.csproj::TargetFramework=net481]
D:\a\_work\1\s\src\libraries\Microsoft.Extensions.Caching.Abstractions\tests\TrimmingTests\HybridCacheEntryOptionsAccessorTest.cs(17,6): error CS0246: The type or namespace name 'UnsafeAccessor' could not be found (are you missing a using directive or an assembly reference?) [D:\a\_work\1\s\src\libraries\Microsoft.Extensions.Caching.Abstractions\tests\Microsoft.Extensions.Caching.Abstractions.Tests.csproj::TargetFramework=net481]
D:\a\_work\1\s\src\libraries\Microsoft.Extensions.Caching.Abstractions\tests\TrimmingTests\HybridCacheEntryOptionsAccessorTest.cs(17,21): error CS0103: The name 'UnsafeAccessorKind' does not exist in the current context [D:\a\_work\1\s\src\libraries\Microsoft.Extensions.Caching.Abstractions\tests\Microsoft.Extensions.Caching.Abstractions.Tests.csproj::TargetFramework=net481]
    0 Warning(s)
    3 Error(s)
```

This appears to have been introduced in #130403 cc @svick
