### PR TITLE
Fix HttpStress & SslStress

### LINKED ISSUE #80706: Http/SSl StressTest build failures
The Http(Ssl)Stress projects fail to build, most likely because of #78354.

```
/app/Program.cs(4,17): error CS0234: The type or namespace name 'AspNetCore' does not exist in the namespace 'Microsoft' (are you missing an assembly reference?) [/app/HttpStress.csproj]
```

https://dev.azure.com/dnceng-public/public/_build/results?buildId=138183&view=logs&j=22fea640-1099-5f32-ec5d-316ad83f359a&t=7fe64d4e-bb7a-5b68-0c5c-ad57d12d4da9&l=2462

### PR DESCRIPTION
**Pull request by antonfirsov**
The live-built runtime became 8.0 with #78354, we need to update version settings within the stress infra.

Fixes #80706

### CODE REVIEW

**Review by MihaZupan — APPROVED** [review]

**Comment by antonfirsov** [comment]
Stress tests are passing now, failures in other pipelines are unrelated.
