### PR TITLE
Rename JsonPropertyInfo<TConverter> to JsonPropertyInfo<TTypeToConvert>.

### PR DESCRIPTION
**Pull request by ahsonkhan**
Using `TConverter` to refer to the generic type that the `JsonConverter<T>` supports seemed odd (it makes it seem like we are referring to the converter, not the T that the converter supports).

If you have other suggestions that might be clearer, let me know.

cc @stephentoub

### CODE REVIEW

**Review by stephentoub — APPROVED** [review]

**Review by jozkee — APPROVED** [review]

**Review by safern — APPROVED** [review]

**Comment by ahsonkhan** [comment]
The CI failures are unrelated (fixed in https://github.com/dotnet/runtime/pull/32211)

> src/libraries/Common/src/System/Threading/Tasks/TaskCompletionSourceWithCancellation.cs(28,59): error CS8600: Converting null literal or possible null value to non-nullable type.

> System/Diagnostics/Process.cs(1431,63): error CS8625: Cannot convert null literal to non-nullable reference type.
