### PR TITLE
Revert "Fix handling of array constructors in Crossgen2"

### PR DESCRIPTION
**Pull request by trylek**
Reverts dotnet/runtime#48557

The change started causing nullrefs on Unix. Reverting for now to unblock PR runs.

Thanks

Tomas

### CODE REVIEW

**Review by jkotas — APPROVED** [review]

**Comment by trylek** [comment]
I take it back, the test was broken by https://github.com/dotnet/runtime/pull/50437, not https://github.com/dotnet/runtime/pull/48557. cc @davidwrighton - the problem is that, in

https://github.com/dotnet/runtime/blob/18f9a0712f4b73b2b97a19d52cddb9603731cd55/src/coreclr/tools/Common/JitInterface/CorInfoImpl.cs#L1293

While it may seem that the default <code>NotFoundBehavior</code> is <code>Throw</code> according to

https://github.com/dotnet/runtime/blob/18f9a0712f4b73b2b97a19d52cddb9603731cd55/src/coreclr/tools/Common/TypeSystem/IL/EcmaMethodIL.cs#L134

the call actually uses the default value specified on

https://github.com/dotnet/runtime/blob/18f9a0712f4b73b2b97a19d52cddb9603731cd55/src/coreclr/tools/Common/TypeSystem/IL/MethodIL.cs#L89

i.e. <code>ReturnNull</code> which ends up smuggling an unresolved external symbol into <code>resolveToken</code> as null, wreaking havoc in the module type resolver. At the first glance it looks like it should suffice to adjust the virtual declaration in <code>MethodIL</code> to be also <code>Throw</code> but I'd prefer to wait for David's confirmation and I'm double-checking how exactly this transformed in his change.
