### PR TITLE
Fix superpmi.py collect script

### PR DESCRIPTION
**Pull request by BruceForstall**
Collect also does a replay, so needs all the replay arguments set to something.
Fixes this error: `'CoreclrArguments' object has no attribute 'compile'`

### CODE REVIEW

**Comment by BruceForstall** [comment]
fyi @SeanWoo -- regression from https://github.com/dotnet/runtime/pull/62217. There's an unfortunately subtle issue with argument processing for `superpmi.py collect`.

**Comment by BruceForstall** [comment]
@kunalspathak @dotnet/jit-contrib PTAL

**Review by kunalspathak — APPROVED** [review]
LGTM

**Comment by SeanWoo** [comment]
> fyi @SeanWoo -- regression from #62217. There's an unfortunately subtle issue with argument processing for `superpmi.py collect`.
What is the problem?
