### ISSUE TITLE
Build FAILED after #106209 PR (Implement type name resolution for ILLink analyzer)

### ISSUE THREAD

**Issue by AlexRadch** [dotnet/runtime#106321]
### Description

Can not build runtime after  #106209 PR (Implement type name resolution for ILLink analyzer)

With the next log:
```
  System.Private.CoreLib -> C:\AProj\runtime\artifacts\bin\System.Private.CoreLib\ref\Release\net9.0\System.Private.CoreLib.dll

Build FAILED.

CSC : error CS8032: An instance of analyzer ILLink.RoslynAnalyzer.RequiresUnreferencedCodeAnalyzer cannot be created from C:\AProj\runtime\artifacts\bin\ILLink.RoslynAnalyzer\Debug\netstandard2.0\ILLink.RoslynAnalyzer.dll : Could not load file or assembly 'System.Collections.Immutable, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The specified file cannot be found. [C:\AProj\runtime\src\coreclr\System.Private.CoreLib\System.Private.CoreLib.csproj]
CSC : error CS8032: An instance of analyzer ILLink.RoslynAnalyzer.RequiresAssemblyFilesAnalyzer cannot be created from C:\AProj\runtime\artifacts\bin\ILLink.RoslynAnalyzer\Debug\netstandard2.0\ILLink.RoslynAnalyzer.dll : Could not load file or assembly 'System.Collections.Immutable, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The specified file cannot be found. [C:\AProj\runtime\src\coreclr\System.Private.CoreLib\System.Private.CoreLib.csproj]
CSC : error CS8032: An instance of analyzer ILLink.RoslynAnalyzer.COMAnalyzer cannot be created from C:\AProj\runtime\artifacts\bin\ILLink.RoslynAnalyzer\Debug\netstandard2.0\ILLink.RoslynAnalyzer.dll : Could not load file or assembly 'System.Collections.Immutable, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The specified file cannot be found. [C:\AProj\runtime\src\coreclr\System.Private.CoreLib\System.Private.CoreLib.csproj]
CSC : error CS8032: An instance of analyzer ILLink.RoslynAnalyzer.DynamicallyAccessedMembersAnalyzer cannot be created from C:\AProj\runtime\artifacts\bin\ILLink.RoslynAnalyzer\Debug\netstandard2.0\ILLink.RoslynAnalyzer.dll : Could not load file or assembly 'System.Collections.Immutable, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The specified file cannot be found. [C:\AProj\runtime\src\coreclr\System.Private.CoreLib\System.Private.CoreLib.csproj]
CSC : error CS8032: An instance of analyzer ILLink.RoslynAnalyzer.RequiresDynamicCodeAnalyzer cannot be created from C:\AProj\runtime\artifacts\bin\ILLink.RoslynAnalyzer\Debug\netstandard2.0\ILLink.RoslynAnalyzer.dll : Could not load file or assembly 'System.Collections.Immutable, Version=9.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'. The specified file cannot be found. [C:\AProj\runtime\src\coreclr\System.Private.CoreLib\System.Private.CoreLib.csproj]
    0 Warning(s)
    5 Error(s)

Time Elapsed 00:01:14.99
Build failed with exit code 1. Check errors above.
Some builds failed:
        Configuration: Debug, Architecture: x64
```

### Reproduction Steps

```
git clean -xdf
git pull upstream main
build.cmd clr+libs -rc Release
```

### Expected behavior

Successful Build.

### Actual behavior

Build FAILED

### Regression?

Yes!!!

### Known Workarounds

Use runtime before this PR.

### Configuration

.NET 9
Windows 10
x64

**Comment by huoyaoyuan** [comment]
I can also reproduce this in VS.

**Comment by ViktorHofer** [comment]
I can reproduce this as well. Uninstalling the global SDK helped in my case.

**Comment by pavelsavara** [comment]
same here, deleting my local dotnet installation helped.

**Comment by AlexRadch** [comment]
After I removed the .Net 9 global SDK, the build was successful.

**Comment by AlexRadch** [comment]
> Odd, that suggests to me that the build was picking up an older version of the global SDK, but shouldn't that be prevented by the version in global.json? More specific repro steps would be helpful.

When I install the latest .Net 9.0.100-preview.6.24328.19 globally, then the build fails.

**Comment by noahfalk** [comment]
> More specific repro steps would be helpful.

If it helps my repro of this:

1. These SDKs were already installed:

> C:\git\runtime3>dotnet --list-sdks
C:\Program Files\dotnet
8.0.108 [C:\Program Files\dotnet\sdk]
8.0.303 [C:\Program Files\dotnet\sdk]
8.0.400-preview.0.24324.5 [C:\Program Files\dotnet\sdk]
9.0.100-preview.6.24328.19 [C:\Program Files\dotnet\sdk]

2. Clone the runtime repo and pull from https://github.com/dotnet/runtime main

> C:\git\runtime3>git log
commit ec7fd04caa9ff0f018598c30f76b3f3d4ab8673b (HEAD -> main, upstream/main, origin/main, master)
Author: Viktor Hofer <viktor.hofer@microsoft.com>
Date:   Tue Aug 13 19:29:08 2024 +0200

3. Build libs

> build.cmd libs

**Comment by huoyaoyuan** [comment]
> @huoyaoyuan would you be able to share repro instructions that hit this in VS?

Just pulled the change in VS, and invoke "Rebuild" for CoreLib. It's now failing.

**Comment by AlexRadch** [comment]
After I installed the new .NET SDK 9.0.100-preview.7.24407.12 globally, the runtime build was successful.
