### PR TITLE
[NativeAOT] Use QueueUserAPC2 in GC suspension, if available.

### PR DESCRIPTION
**Pull request by VSadov**

### CODE REVIEW

**Comment by VSadov** [comment]
Nothing failed on Windows with NativeAOT and this change - it means that no leg is running on Windows that has working `QueueUserAPC2`/`QUEUE_USER_APC_CALLBACK_DATA_CONTEXT`

I wonder if this could be easy to change.

**Comment by MichalStrehovsky** [comment]
> Most likely everything runs on Win10.

At minimum the ARM64 legs are Win11. From the console log of one of the tests in this PR:

```
Console log: 'Microsoft.Extensions.Configuration.Functional.Tests' from job a5783e36-675c-4d1c-bd66-912b1b2cd73c workitem fd692c4c-6e4e-464a-bffa-2e49f0d3d415 (windows.11.arm64.open) executed on machine a0006UM running Windows-10-10.0.22621-SP0
```

22621 is the 22H2 Windows 11 build.

**Comment by VSadov** [comment]
I am testing locally on 22623.1037 (x64) and it has the feature. 
Perhaps it is different with ARM64? It should not be though. The API is not architecture-specific.

File: src/coreclr/nativeaot/Runtime/CMakeLists.txt [hunk 1]
```diff
@@ -229,6 +229,7 @@ if(WIN32)
   add_definitions(-DFEATURE_ETW)
   add_definitions(-DFEATURE_EVENT_TRACE)
   add_definitions(-DFEATURE_SUSPEND_REDIRECTION)
+  add_definitions(-DFEATURE_SUSPEND_APC2)
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/CMakeLists.txt:232]: The name of the feature flag in CoreCLR is `FEATURE_SPECIAL_USER_MODE_APC`. Can we use the same name in both places?

File: src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp [hunk 2]
```diff
@@ -442,17 +448,78 @@ REDHAWK_PALEXPORT void REDHAWK_PALAPI PalRestoreContext(CONTEXT * pCtx)
...
+typedef BOOL(WINAPI* QueueUserAPC2Proc)(PAPCFUNC ApcRoutine, HANDLE Thread, ULONG_PTR Data, QUEUE_USER_APC_FLAGS Flags);
+static QueueUserAPC2Proc pfnQueueUserAPC2Proc;
+
+static const QUEUE_USER_APC_FLAGS SpecialUserModeApcWithContextFlags = (QUEUE_USER_APC_FLAGS)
+                                    (QUEUE_USER_APC_FLAGS_SPECIAL_USER_APC |
+                                    QUEUE_USER_APC_CALLBACK_DATA_CONTEXT);
+
+static void __stdcall EmptyActivationHandler(ULONG_PTR parameter){}
+
+static void __stdcall ActivationHandler(ULONG_PTR parameter)
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:461]:
```suggestion
static void NTAPI EmptyActivationHandler(ULONG_PTR parameter){}

static void NTAPI ActivationHandler(ULONG_PTR parameter)
```
to match Windows SDK definition of `PAPCFUNC`

File: src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp [hunk 3]
```diff
@@ -442,17 +448,78 @@ REDHAWK_PALEXPORT void REDHAWK_PALAPI PalRestoreContext(CONTEXT * pCtx)
 
 static PalHijackCallback g_pHijackCallback;
 
+#ifdef FEATURE_SUSPEND_APC2
+typedef BOOL(WINAPI* QueueUserAPC2Proc)(PAPCFUNC ApcRoutine, HANDLE Thread, ULONG_PTR Data, QUEUE_USER_APC_FLAGS Flags);
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:452]:
```suggestion
typedef BOOL (WINAPI* QueueUserAPC2Proc)(PAPCFUNC ApcRoutine, HANDLE Thread, ULONG_PTR Data, QUEUE_USER_APC_FLAGS Flags);
```

**Comment by jkotas** [comment]
> Need to figure how to test this in CI

Cet helix queue used by this pipeline https://github.com/dotnet/runtime/blob/main/eng/pipelines/runtime-cet.yml#L93 runs Windows build that supports QueueUseAPC2 API.

@janvorli Do you happen to know whether QueueUseAPC2 works on Windows Arm64?

**Comment by janvorli** [comment]
> @janvorli Do you happen to know whether QueueUseAPC2 works on Windows Arm64?

Based on feedback from the Windows developers in the past, this API should work on Windows Arm64 provided the Windows are of a version that already has support for supplying the interrupted context to the callback.

**Comment by VSadov** [comment]
> Do you happen to know whether QueueUseAPC2 works on Windows Arm64?

I looked at the implementation. It should work on ARM/ARM64 the same as on x86/x64, if the OS version has the changes. 
I now have doubts that this feature made it into 21H2, even though it is documented as requiring [Windows Build 22000](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/ne-processthreadsapi-queue_user_apc_flags#requirements)  , Which is any Win11, I think

In a way - an implementation that "supports" this by returning `0` is still an implementation. But then even Win10 "supports" it, so it is a bit confusing.

**Comment by janvorli** [comment]
> In a way - an implementation that "supports" this by returning `0` is still an implementation. But then even Win10 "supports" it, so it is a bit confusing.

I am not sure I understand. We need the version that passes `CONTEXT` of the interrupted location to the callback. The check that we do tests that. The version that doesn't support the `QUEUE_USER_APC_CALLBACK_DATA_CONTEXT` flag would return error from the `QueueUserAPC2`.

**Comment by VSadov** [comment]
> I am not sure I understand. 

I am just finding the documentation confusing a bit. Assuming that this API returns error for `QUEUE_USER_APC_CALLBACK_DATA_CONTEXT` , then is it actually "supported"? Or maybe "supported" just means "you can pass this to the API", but in such case even Win10 "supports" this.

On our part, since we need to run on Win10, we need to probe for working API anyways. 

It is just a question what OS version we need to use in the lab to be sure the feature is working and documentation seems to say "any Win11" is ok, while we see that is not the case, at least on arm64.

This PR right now has a change that would intentionally cause failures if `QUEUE_USER_APC_CALLBACK_DATA_CONTEXT` and we see that everything is passing.

**Comment by VSadov** [comment]
I have just tried a fresh VM with official Win11 22H2 and the feature is supported. (i.e. tests are failing as expected). 

The OS is
```
Edition	Windows 11 Enterprise
Version	22H2
Installed on	‎1/‎2/‎2023
OS build	22621.382
Experience	Windows Feature Experience Pack 1000.22632.1000.0
```

Bow I wonder if the lab image is actually 22621.
Or maybe 22621 arm64 does not have this, while x64 does?

**Comment by VSadov** [comment]
@MichalStrehovsky - do you know if `extra platforms` runs anything NativeAOT on Windows11 x64 ?

**Comment by VSadov** [comment]
Hold on. Maybe it is just the way I am trying to cause the failure (`UNREACHABLE_MSG`) does not cause a failure in Release?

**Comment by janvorli** [comment]
The QueueUserAPC2 API itself was added quite some time ago, but without support for the `QUEUE_USER_APC_CALLBACK_DATA_CONTEXT`. So it would schedule the APC, but it would not be passed the context where the thread was interrupted. That was making it useless for GC purposes, so after we have discussed the issue with Windows developers, they have updated it to support passing in the context to the callback. But it only does that when the `QUEUE_USER_APC_CALLBACK_DATA_CONTEXT` is passed in.

**Comment by VSadov** [comment]
> But it only does that when the QUEUE_USER_APC_CALLBACK_DATA_CONTEXT is passed in.

Right. And it looks like official 22H2 build (22621.382) has the change, at east on x64, so this PR can be lab-tested.

Let's see if there will be failures now in the `Build windows arm64 Release NativeAOT` leg

**Comment by jkotas** [comment]
> do you know if extra platforms runs anything NativeAOT on Windows11 x64 ?

You can tell by looking at the log. This is the log from your earlier extra platforms run: https://dev.azure.com/dnceng-public/public/_build/results?buildId=122374&view=logs&jobId=f50bdeb8-70f9-5fe0-0c12-4bd43ab59b51&j=e2a090ef-1ffe-5b5a-8213-260fbf226a4b&t=f60bbc11-44b7-557d-f3f2-48d48cb3fb2d

Look for this in the log: `Using Queues: Windows.81.Amd64.Open+Windows.10.Amd64.Server2022.ES.Open+Windows.11.Amd64.Client.Open+(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64`

**Comment by VSadov** [comment]
> Look for this in the log: Using Queues: Windows.81.Amd64.Open+Windows.10.Amd64.Server2022.ES.Open+Windows.11.Amd64.Client.Open+(Windows.Nano.1809.Amd64.Open)windows.10.amd64.serverrs5.open@mcr.microsoft.com/dotnet-buildtools/prereqs:nanoserver-1809-helix-amd64

Right - there is Windows11 in the set.

And now ` windows arm64 Release NativeAOT` failed as expected too. 
So it was a problem with the change that supposed to cause failures, but did not do it in Release. 

It looks like we have coverage sensitive to this PR in both regular and in `extra platforms` and on arm64 too. It was just my way to "introduce a break" did not work as planned.

**Comment by VSadov** [comment]
I will now remove the intentional break and we can run the whole thing once more. To be sure all is working.

**Comment by VSadov** [comment]
Performance of asynchronous suspension is substantially faster with this change. 

I see almost 10X reduction in average suspension latency in a targeted microbenchmark. Occurrence of long suspensions have been reduced too.

Note that this is a "difficult" scenario where threads run compute-heavy barrier-heavy loops. 
In this case we need to suspend threads asynchronously and there are chances we will not find them on GC-safe points at first try. In real-world scenarios many threads will "cooperate" by making hijackable calls, doing allocations, PInvokes or other actions that indirectly poll for suspension, but occasionally we will see groups of "stubborn" threads.

This is a relatively small machine with 6 cores (12 logical). The improvements will be more noticeable as the number of cores/threads grow.

```
	Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz

	Base speed:	3.19 GHz
	Sockets:	1
	Cores:	6
	Logical processors:	12
```

Before the change (typical output):
The interesting measure is the average suspension time when threads do not poll. It is in msec, lower is better.

```
frequent GC-polling        : True
#suspensions in 5 sec.     : 238340
Average suspension took    : 0.020978434169673574
longest suspend  was (msec): 1

frequent GC-polling        : False
#suspensions in 5 sec.     : 7398
Average suspension took    : 0.6758583400919167
longest suspend  was (msec): 5

frequent GC-polling        : True
#suspensions in 5 sec.     : 230512
Average suspension took    : 0.021690844728257098
longest suspend  was (msec): 1

frequent GC-polling        : False
#suspensions in 5 sec.     : 7361
Average suspension took    : 0.6792555359326179
longest suspend  was (msec): 9
```

After the change (typical output):
```
frequent GC-polling        : True
#suspensions in 5 sec.     : 248014
Average suspension took    : 0.02016015224946979
longest suspend  was (msec): 1

frequent GC-polling        : False
#suspensions in 5 sec.     : 61518
Average suspension took    : 0.08127702461068305
longest suspend  was (msec): 5

frequent GC-polling        : True
#suspensions in 5 sec.     : 246619
Average suspension took    : 0.02027418812013673
longest suspend  was (msec): 1

frequent GC-polling        : False
#suspensions in 5 sec.     : 61910
Average suspension took    : 0.08076239702794379
longest suspend  was (msec): 1
```

==== the benchmark:
```cs
using System;
using System.Diagnostics;
using System.Runtime.CompilerServices;
using System.Threading;

class Program
{
    static object[] arr1 = new Exception[10000];

    static int[] flags;

    enum E1
    {
        a
    }

    static object box = E1.a;

    static void DoSomeWork(int i)
    {
        var a1 = arr1;

        ArgumentNullException val = new ArgumentNullException();
        for (; ; )
        {
            Assign(a1, 1, val);
            Assign(a1, 2, val);
            Assign(a1, 3, val);
            Assign(a1, 4, val);
            Assign(a1, 5, val);
            Assign(a1, 6, val);
            Assign(a1, 7, val);

            if (flags[i] == 0)
                flags[i] = 1;
        }
    }

    static bool doPoll;

    [MethodImpl(MethodImplOptions.NoInlining)]
    private static void Assign(object[] a, int i, ArgumentNullException val)
    {
        if (val != null)
        {
            a[i] = val;
        }

        if (doPoll)
        {
            // enum->int  unbox will perform a GC-polling FCALL   (easy case for suspension)
            // int unboxed = (int)box;

            // unboxing is not an FCall in NativeAOT and does not poll.
            // use PInvoke instead as an "easy for suspension" case
            Thread.Yield();
        }

        a[i] = null;
    }

    static void Main()
    {
        int numThreads = Environment.ProcessorCount - 1;

        flags = new int[numThreads];
        for (int i = 0; i < numThreads; i++)
        {
            int j = i;
            new Thread(() =>
            {
                DoSomeWork(j);
            }).Start();
        }

        Thread.Sleep(10);
        Thread.CurrentThread.Priority = ThreadPriority.Highest;
        for (; ; )
        {
            long longest = 0;
            int iterations = 0;
            doPoll ^= true;

            // do 5sec of suspension/resume
            var sw = Stopwatch.StartNew();
            long totalSuspendedTime = 0;
            while (totalSuspendedTime < 5000)
            {
                long oneIter = sw.ElapsedMilliseconds;

                // Suspend/Resume EE
                GC.GetTotalAllocatedBytes(precise: true);

                oneIter = sw.ElapsedMilliseconds - oneIter;

                longest = Math.Max(longest, oneIter);
                iterations++;
                totalSuspendedTime += oneIter;

                // Make sure other threads actually resumed
                for (int i = 0; i < numThreads; i++)
                {
                    flags[i] = 0;
                    while (flags[i] == 0)
                        Thread.SpinWait(1);
                }
            }

            {
                Console.WriteLine($"frequent GC-polling        : {doPoll}");
                Console.WriteLine($"#suspensions in 5 sec.     : {iterations}");
                Console.WriteLine($"Average suspension took    : {(double)totalSuspendedTime / iterations}");
                Console.WriteLine($"longest suspend  was (msec): {longest}");
                Console.WriteLine();
            }
        }
    }
}
```

**Comment by VSadov** [comment]
I has just occurred to me that we are now measuring times well below 1 msec. It was not always the case, but now the benchmark should be using `ElapsedTicks`, not `ElapsedMilliseconds` for better precision.

Hold on. I will update the measurements and the benchmark code.

File: src/coreclr/nativeaot/Runtime/threadstore.inl [hunk 4]
```diff
@@ -25,16 +25,6 @@ inline Thread * ThreadStore::GetCurrentThread()
     return pCurThread;
 }
 
-// static
-inline Thread * ThreadStore::GetCurrentThreadIfAvailable()
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/threadstore.inl:29]: We do not compile with link time codegen enabled currently (we would have to ship all runtime C/C++sources in the package in order to do that). It means that explicitly inlining methods like this is more important here than in coreclr (coreclr.dll compiles with link time codegen).

Is this method called on any perf critical paths that will regress once it stops being inlined?

File: src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp [hunk 5]
```diff
@@ -968,22 +969,26 @@ static void ActivationHandler(int code, siginfo_t* siginfo, void* context)
         g_pHijackCallback((NATIVE_CONTEXT*)context, NULL);
         errno = savedErrNo;
     }
+
+    Thread* pThread = ThreadStore::GetCurrentThreadIfAvailable();
+    if (pThread)
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp:974]: When can this be null?

File: src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp [hunk 6]
```diff
@@ -442,17 +448,81 @@ REDHAWK_PALEXPORT void REDHAWK_PALAPI PalRestoreContext(CONTEXT * pCtx)
...
+                hThread,
+                (ULONG_PTR)pThreadToHijack,
+                SpecialUserModeApcWithContextFlags);
+
+            if (!success)
+            {
+                // Failure to send the signal is fatal.
+                // There are no known transient reasons for this to fail.
+                ASSERT(!"failed to queue an APC");
+                abort();
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:518]: We seem to using `RhFailFast` in Windows PAL

File: src/coreclr/nativeaot/Runtime/threadstore.inl (hunk 4 above)
Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/threadstore.inl:29]: I think most perf-sensitive cases will call `GetCurrentThread` if they know the thread is available or `GetCurrentThreadRaw` if unsure.

The reason this cannot be `inline` is that we fail on Linux at linking stage with missing method when we call this from `PalHijack`. In the context of `PalHijack` inline would not be too important as we are making syscalls which are heavier things.

Perhaps I can just make a sibling method that is not inlined - just to call from `PalHijack.

File: src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp (hunk 5 above)
Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp:974]: If someone else sends a signal to a random thread in our process, that has not seen managed code. 
Not sure if this can happen in practice, but it is cheap to check.

Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp:974]: I can imagine profilers sending signals to do stack probing, for example.

On MacOS we use SIGUSR1, so it is more likely to share the signal with somebody.

File: src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp (hunk 6 above)
Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:518]: Yes, `RhFailFast` may be better.  I am also thinking maybe not crash here? I am not 100% sure there cannot be a transient failure to queue. 

I looked through what happens in this call on the OS side and it can fail, but the reasons are basically either invalid arguments or something is wrong with the target thread and it is unlikely to go away on the next try.

I am not 100% sure though. I've been hesitating a lot on this one.

File: src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp (hunk 5 above)
Comment (jkotas) [reply src/coreclr/nativeaot/Runtime/unix/PalRedhawkUnix.cpp:974]: Ok, makes sense.

File: src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp (hunk 6 above)
Comment (jkotas) [reply src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:518]: Can this fail on out-of-memory?

File: src/coreclr/nativeaot/Runtime/threadstore.inl (hunk 4 above)
Comment (jkotas) [reply src/coreclr/nativeaot/Runtime/threadstore.inl:29]: > The reason this cannot be inline is that we fail on Linux at linking stage with missing method when we call this from PalHijack.

You should be able to fix that by `#including` `thread.inl` in the PAL implementation file.

File: src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp (hunk 6 above)
Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:518]: Unix has a few rare scenarios where queuing a signal can fail transiently - like when a thread is about to exit, OSX may refuse to signal it. - At the moment we decide to send a signal the thread is alive and runs managed code, but when we get to sending it is already native and stopped on theadstore lock trying to leave runtime for good. This is where we get ESRCH error. On the next iteration we will see the thread is no longer running managed code.
This is a rare race, but we have seen it happening.


Perhaps something like this is possible on Windows.

Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:518]: > Can this fail on out-of-memory?

Actually yes - there is a part that needs to allocate a small piece of nonpaged memory to put the APC in the list of APCs hanging off the thread before scheduling/signaling the thread. The insertion can fail with `STATUS_NO_MEMORY`.

I guess we should not fail then.

Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:518]: I will keep the assert though - in case this happens in tests, which is more likely to indicate that something is broken.

File: src/coreclr/nativeaot/Runtime/threadstore.inl (hunk 4 above)
Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/threadstore.inl]: Somehow did not think about that.

**Comment by VSadov** [comment]
@jkotas - anything else we might want to add to this change?

File: src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp [hunk 7]
```diff
@@ -442,17 +448,82 @@ REDHAWK_PALEXPORT void REDHAWK_PALAPI PalRestoreContext(CONTEXT * pCtx)
 
 static PalHijackCallback g_pHijackCallback;
 
+#ifdef FEATURE_SPECIAL_USER_MODE_APC
+typedef BOOL (WINAPI* QueueUserAPC2Proc)(PAPCFUNC ApcRoutine, HANDLE Thread, ULONG_PTR Data, QUEUE_USER_APC_FLAGS Flags);
+static QueueUserAPC2Proc pfnQueueUserAPC2Proc;
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:453]:
```suggestion
static QueueUserAPC2Proc g_pfnQueueUserAPC2Proc;
```

File: src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp [hunk 8]
```diff
@@ -442,17 +448,82 @@ REDHAWK_PALEXPORT void REDHAWK_PALAPI PalRestoreContext(CONTEXT * pCtx)
...
 
+#ifdef FEATURE_SPECIAL_USER_MODE_APC
+    // Check if we have QueueUserAPC2
+    HMODULE hKernel32 = LoadKernel32dll();
+    pfnQueueUserAPC2Proc = (QueueUserAPC2Proc)GetProcAddress(hKernel32, "QueueUserAPC2");
+
+    // See if QueueUserAPC2 supports the special user-mode APC with a callback that includes the interrupted CONTEXT
+    if (pfnQueueUserAPC2Proc != NULL)
+    {
+        if (!(*pfnQueueUserAPC2Proc)(EmptyActivationHandler, GetCurrentThread(), 0, SpecialUserModeApcWithContextFlags))
```
[the remark this answers is not in the document]
Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:484]: On Win10 this will always fail, but the API is present. We would need to prevent trying over and over. 
With some sentinel value for "unknown" state and NULL for "does not work" this might be possible.

[the remark this answers is not in the document]
Comment (jkotas) [reply src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:484]: Right, we can have a bool flag that says the API failed with "SpecialUserModeApcWithContextFlags not supported error". Once the flag gets set, we will stop trying.

[the remark this answers is not in the document]
Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp]: I've uses a sentinel value for uninitialized state. Hijacking pass is single-threaded, so initializing on demand is simple. 
Maybe will save us some ticks at startup.

File: src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp [hunk 9]
```diff
@@ -453,6 +479,41 @@ REDHAWK_PALEXPORT UInt32_BOOL REDHAWK_PALAPI PalRegisterHijackCallback(_In_ PalH
 REDHAWK_PALEXPORT void REDHAWK_PALAPI PalHijack(HANDLE hThread, _In_opt_ void* pThreadToHijack)
 {
     _ASSERTE(hThread != INVALID_HANDLE_VALUE);
+
+#ifdef FEATURE_SPECIAL_USER_MODE_APC
+    if (g_pfnQueueUserAPC2Proc == QUEUE_USER_APC2_UNINITIALIZED)
+    {
+        g_pfnQueueUserAPC2Proc = (QueueUserAPC2Proc)GetProcAddress(LoadKernel32dll(), "QueueUserAPC2");
+    }
+
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:488]: This is not thread safe in C/C++.

It is valid for C/C++ compiler to rewrite this as:

```
QueueUserAPC2Proc pfn = g_pfnQueueUserAPC2Proc;
if (g_pfnQueueUserAPC2Proc == QUEUE_USER_APC2_UNINITIALIZED)
{
   g_pfnQueueUserAPC2Proc = pfn = (QueueUserAPC2Proc)GetProcAddress(LoadKernel32dll(), "QueueUserAPC2");
}

if (pfn)
{
....
}
```

It needs to use volatile or something like that.

File: src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp [hunk 10]
```diff
@@ -453,6 +479,41 @@ REDHAWK_PALEXPORT UInt32_BOOL REDHAWK_PALAPI PalRegisterHijackCallback(_In_ PalH
...
+            hThread,
+            (ULONG_PTR)pThreadToHijack,
+            SpecialUserModeApcWithContextFlags);
+
+        if (success)
+        {
+            return;
+        }
+
+        // queuing an APC failed. we will not try again
```
Comment (jkotas) [inline src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:511]: Should we check for specific "not suppported" last error here?

File: src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp (hunk 9 above)
Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:488]: Only one thread may perform suspension/hijacking at a time. This code is single threaded, protected by the thread store lock.

Comment (jkotas) [reply src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:488]: It needs comment at least to make this assumption explicit.

File: src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp (hunk 10 above)
Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:511]: I do not think API documents  particular errors. They just say the error could be fetched via last error. 

If we recognize some errors, what would we do with errors that we do not recognize?

Comment (jkotas) [reply src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:511]: > If we recognize some errors, what would we do with errors that we do not recognize?

Ignore the error and try again a bit later.

File: src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp (hunk 9 above)
Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:488]: I’ve made the variable ‘volatile’ initially n this change, but then realized that there is no need.

Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:488]: I’ll add a comment. It was not obvious. 
I even had ‘Interlocked’, etc, before realizing it is single threaded and can be a lot simpler.

File: src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp (hunk 10 above)
Comment (VSadov) [reply src/coreclr/nativeaot/Runtime/windows/PalRedhawkMinWin.cpp:511]: I’lll check what Win10 sets the last error to.

**Review by jkotas — APPROVED** [review]
Thank you!

**Comment by jkotas** [comment]
Looks like the tests are failing with "failed to queue an APC for unusual reason."

**Comment by VSadov** [comment]
Thanks!!

**Comment by jakobbotsch** [comment]
The build is failing locally for me after this PR:
```scala
  C:\dev\dotnet\runtime\src\coreclr\nativeaot\Runtime\windows\PalRedhawkMinWin.cpp(452): error C2061: syntax error: identifier 'QUEUE_USER_APC_FLAGS'
  C:\dev\dotnet\runtime\src\coreclr\nativeaot\Runtime\windows\PalRedhawkMinWin.cpp(457): error C4430: missing type specifier - int assumed. Note: C++ does not support default-int
  C:\dev\dotnet\runtime\src\coreclr\nativeaot\Runtime\windows\PalRedhawkMinWin.cpp(457): error C2146: syntax error: missing ';' before identifier 'SpecialUserModeApcWithContextFlags'
  C:\dev\dotnet\runtime\src\coreclr\nativeaot\Runtime\windows\PalRedhawkMinWin.cpp(457): error C2059: syntax error: '='
  C:\dev\dotnet\runtime\src\coreclr\nativeaot\Runtime\windows\PalRedhawkMinWin.cpp(463): error C2065: 'APC_CALLBACK_DATA': undeclared identifier
  C:\dev\dotnet\runtime\src\coreclr\nativeaot\Runtime\windows\PalRedhawkMinWin.cpp(463): error C2065: 'data': undeclared identifier
  C:\dev\dotnet\runtime\src\coreclr\nativeaot\Runtime\windows\PalRedhawkMinWin.cpp(463): error C2065: 'APC_CALLBACK_DATA': undeclared identifier
  C:\dev\dotnet\runtime\src\coreclr\nativeaot\Runtime\windows\PalRedhawkMinWin.cpp(463): error C2059: syntax error: ')'
  C:\dev\dotnet\runtime\src\coreclr\nativeaot\Runtime\windows\PalRedhawkMinWin.cpp(464): error C2065: 'data': undeclared identifier
  C:\dev\dotnet\runtime\src\coreclr\nativeaot\Runtime\windows\PalRedhawkMinWin.cpp(466): error C2065: 'data': undeclared identifier
  C:\dev\dotnet\runtime\src\coreclr\nativeaot\Runtime\windows\PalRedhawkMinWin.cpp(507): error C2065: 'SpecialUserModeApcWithContextFlags': undeclared identifier
```

**Comment by jkotas** [comment]
@jakobbotsch What is the Windows SDK version on your machine? (`dir C:\Program Files (x86)\Windows Kits\10\Include`)

**Comment by VSadov** [comment]
As I understand 8.0 main builds with Windows 11 SDK 10.0.22621, which defines these.

**Comment by VSadov** [comment]
Although vsconfig  (https://github.com/dotnet/runtime/blob/main/.vsconfig) lists Windows10SDK.19041

**Comment by VSadov** [comment]
This is confusing. When I tried defining these the lab build failed because of duplicate definitions and I only could reproduce the lab behavior by installing 10.0.22621 locally

**Comment by jkotas** [comment]
https://github.com/dotnet/runtime/blob/main/.vsconfig is always out-of-date.

**Comment by jkotas** [comment]
> As I understand 8.0 main builds with Windows 11 SDK 10.0.22621

FWIW, this is the SDK version that I have on my machines as well. I always use the recommended Workloads installation approach (https://github.com/dotnet/runtime/blob/main/docs/workflow/requirements/windows-requirements.md#visual-studio).

**Comment by VSadov** [comment]
It is possible to redefine the types/constants under different name. It looks like this is what we did in coreclr CET support.

**Comment by VSadov** [comment]
Here is a PR that should build without 22621 https://github.com/dotnet/runtime/pull/80333

**Comment by VSadov** [comment]
With that PR I can build even if I remove 22621. 

I could not remove Windows 11 22000 SDK though, because, according to VS, c++ v143 depends on it and would need to be removed too.

**Comment by jakobbotsch** [comment]
It indeed builds fine for me after updating the SDK, so no worries from my side at least.
