### PR TITLE
[System.Diagnostics.DiagnosticSource] Tracing out of proc sampling

### LINKED ISSUE #102895: System.Diagnostics.Activity out of proc sampling
We have [DiagnosticSourceEventSource](https://github.com/dotnet/runtime/blob/main/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource.cs) which enables listening to `Activity` \ traces out of process. The current design when there is a listener is to create all `Activity` \ spans and write everything to the `EventSource`. We feel for out of process monitoring of traces this will create a lot of overhead in the process being monitored.

The request here is to allow the listener to set some kind of sampling algorithm.

Here is the OTel spec for samplers: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#built-in-samplers

What we have today is essentially `AlwaysOn`.

One suggestion would be to allow the listener to set a ratio. If ratio is supplied we could sample according to these rules:

* If there is a root and it was sampled, always create child spans.
* If there is no root, always create a root span but only set the Recorded\sampled flag based on the TraceIdRatioBased algorithm using the provided ratio.

Always creating the root span is important for log correlation but we only need to create children if the root is sampled. This is how the OTel .NET SDK works today.

/cc @noahfalk @tarekgh @samsp-msft @rajkumar-rangaraj @cijothomas

### PR DESCRIPTION
**Pull request by CodeBlanch**
Fixes #102895

# Changes

* Adds `ParentRatioSampler([ratio])` to the supported sampler types in the `DiagnosticSourceEventSource` "FilterAndPayloadSpecs"
* Adjusts the precedence of samplers so that most specific ruleset applies: 1) source name + activity name, 2) source name + wildcard activity, 3) wildcard source + activity name, 4) wildcard source name + wildcard activity name

/cc @noahfalk @tarekgh

### CODE REVIEW

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource.cs [hunk 1]
```diff
@@ -1575,8 +1616,109 @@ public Subscriptions(IDisposable subscription, Subscriptions? next)
 #endregion
 
         private FilterAndTransform? _specs;                 // Transformation specifications that indicate which sources/events are forwarded.
-        private FilterAndTransform? _activitySourceSpecs;   // ActivitySource Transformation specifications that indicate which sources/events are forwarded.
+        private FilterAndTransform? _rawActivitySourceSpecs;
+        private Dictionary<string, ActivitySourceFilterAndTransformSpecs>? _activitySourceSpecsBySourceName;
```
Comment (CodeBlanch) [inline src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource.cs:1620]: @tarekgh Could we use `FrozenDictionary` here? Thinking it would make the sampling logic execute faster when creating spans using out-of-proc sampling. There is a second `Dictionary` lookup when specific activity names are also defined (ex `[AS]MySource+MyActivity/-ParentRatioSampler(0.05)`)

Comment (tarekgh) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource.cs:1620]: The only concern is the new dependencies. We added Linq dependency before and we had to revert it. If @noahfalk is ok with such dependency. 

CC @stephentoub in case he has more feedback using the frozen collections.

Comment (stephentoub) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource.cs:1620]: With regards to viability, this dictionary is created once, used for the remainder of the process, and lookup speed is critical?

Comment (noahfalk) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource.cs:1620]: I'd be hesitant to add that dependency. At the very least before doing that I'd want to understand what the current performance looks like, what is the goal and where does profiling say the current hot-spots are. 

My best guess is that if you want to make this faster we've probably optimizations that are as good or better and don't need a new dependency. For example instead of using a two-tiered Dictionary you could do a single-tier Dictionary that maps (Source,ActivityName) -> Spec. When you encounter a (Source,ActivityName) tuple for the first time you'd scan the entire set of specs, pick the one which matches best and cache it. Every future time it will be in the dictionary.

File: src/libraries/System.Diagnostics.DiagnosticSource/tests/System.Diagnostics.DiagnosticSource.Tests.csproj [hunk 2]
```diff
@@ -14,16 +14,6 @@
     <Compile Include="TestNotSupported.cs" />
   </ItemGroup>
   <ItemGroup>
-    <Compile Include="..\src\System\Diagnostics\Metrics\Aggregator.cs" Link="Aggregator.cs" />
```
[the remark this answers is not in the document]
Comment (CodeBlanch) [reply src/libraries/System.Diagnostics.DiagnosticSource/tests/System.Diagnostics.DiagnosticSource.Tests.csproj:17]: Interesting! I can revert it. `InternalsVisibleTo` does seem to be used around the repo though 🤷 https://github.com/search?q=repo%3Adotnet%2Fruntime%20assembly%3A%20InternalsVisibleTo(%22&type=code

[the remark this answers is not in the document]
Comment (stephentoub) [reply src/libraries/System.Diagnostics.DiagnosticSource/tests/System.Diagnostics.DiagnosticSource.Tests.csproj:17]: > InternalsVisibleTo does seem to be used around the repo though

Minimally, and really only in places where we inherited it and haven't had the time to remove it.

[the remark this answers is not in the document]
Comment (CodeBlanch) [reply src/libraries/System.Diagnostics.DiagnosticSource/tests/System.Diagnostics.DiagnosticSource.Tests.csproj:17]: I just pushed some changes. I didn't want to just include the entire `DiagnosticSourceEventSource` class in the tests project because then there would be 2 `EventSource`s with the same name in the process. I could have just spun off the sampler stuff into its own file and included it but I felt this code was just in dire need of some refactoring. I tried to separate things out so there is better separation of concerns/less spaghetti. I can revert that and do less but IMO it leaves the camp site in a better state. Check it out, LMK!

**Comment by samsp-msft** [comment]
poke - we should try and get this in .NET 9!

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource/DiagnosticSourceEventSourceListener.cs [hunk 3]
```diff
@@ -0,0 +1,208 @@
...
+
+namespace System.Diagnostics;
+
+internal sealed class DiagnosticSourceEventSourceListener : IDisposable
+{
+    private const string c_ActivitySourcePrefix = "[AS]";
+    private const string c_ParentRatioSamplerPrefix = "ParentRatioSampler(";
+
+    private DiagnosticSourceEventSourceFilterAndTransform? _specList;
+    private DiagnosticSourceEventSourceActivitySourceListener? _activitySourceListener;
```
Comment (noahfalk) [inline src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource/DiagnosticSourceEventSourceListener.cs:15]: To reduce the number of abstractions I would just inline the ActivitySourceListener into this class. Both of them are pretty small, this type is already doing all the parsing for Activity specs and there is no scenario I can see where we'd use the ActivitySourceListener without also needing an instance of this type wrapped around it.

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource/DiagnosticSourceEventSourceListener.cs [hunk 4]
```diff
@@ -0,0 +1,208 @@
...
+                {
+                    if (suffixPart.Equals("Propagate".AsSpan(), StringComparison.OrdinalIgnoreCase))
+                    {
+                        sampleFunc = static (bool hasActivityContext, ref ActivityCreationOptions<ActivityContext> options) => ActivitySamplingResult.PropagationData;
+                    }
+                    else if (suffixPart.Equals("Record".AsSpan(), StringComparison.OrdinalIgnoreCase))
+                    {
+                        sampleFunc = static (bool hasActivityContext, ref ActivityCreationOptions<ActivityContext> options) => ActivitySamplingResult.AllData;
+                    }
+                    else if (suffixPart.StartsWith(c_ParentRatioSamplerPrefix.AsSpan(), StringComparison.OrdinalIgnoreCase))
```
Comment (noahfalk) [inline src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource/DiagnosticSourceEventSourceListener.cs:146]: I'm assuming this is the only change in the parsing code?

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource/DiagnosticSourceEventSourceSamplerBuilder.cs [hunk 5]
```diff
@@ -0,0 +1,69 @@
+﻿// Licensed to the .NET Foundation under one or more agreements.
+// The .NET Foundation licenses this file to you under the MIT license.
+
+namespace System.Diagnostics;
+
+internal static class DiagnosticSourceEventSourceSamplerBuilder
```
Comment (noahfalk) [inline src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource/DiagnosticSourceEventSourceSamplerBuilder.cs:6]: DsesSamplerBuilder

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource/DiagnosticSourceEventSourceSamplerBuilder.cs [hunk 6]
```diff
@@ -0,0 +1,69 @@
...
+{
+    internal delegate ActivitySamplingResult SampleActivityFunc(
```
Comment (noahfalk) [inline src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource/DiagnosticSourceEventSourceSamplerBuilder.cs:8]: DsesSampleFunc (top-level rather than nested)?

**Comment by noahfalk** [comment]
> poke - we should try and get this in .NET 9!

Thanks for reminding me :)

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource/DiagnosticSourceEventSourceActivitySourceListener.cs [hunk 7]
```diff
@@ -0,0 +1,268 @@
...
+        _activityListener.ActivityStarted = OnActivityStarted;
+
+        _activityListener.ActivityStopped = OnActivityStopped;
+
+        ActivitySource.AddActivityListener(_activityListener);
+    }
+
+    private void OnActivityStarted(Activity activity)
+    {
+        if (_wildcardActivitySourceSpecs?.OnActivityStarted(activity) == true)
```
[the remark this answers is not in the document]
Comment (CodeBlanch) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource/DiagnosticSourceEventSourceActivitySourceListener.cs]: @noahfalk

I've pushed changes which I think/hope resolve everything 🤣

* Removed the ability to set a wildcard activity source + specific activity name rule (`[AS]*+MyActivityName`). This helped simplify things.

* Removed the ability to set multiple rules at the same level. Previously you could do things like `[AS]MySource/Start-Propagate\r\n [AS]MySource/Stop-Record`. Now only the first rule will win. This also helped simplify things.

* I implemented something like "TryGetBestSpec". However I didn't implement the caching of the result for a given source name + activity name. I'm a bit hesitant to do that because I'm worried activity name could be high cardinality. Some user _could_ do something silly like use a GUID for the activity name. Having unconstrained cache worried me. I do a bit of organization up front so the lookup is reasonably fast without cache.

* Reduced the abstractions. Now there is only...

  DiagnosticSourceEventSource
  DsesActivitySourceListener
  DsesFilterAndTransform
  DsesSamplerBuilder

  These nested helper types become top-level things:
  DsesActivityEvents
  DsesSampleActivityFunc

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource/DiagnosticSourceEventSourceListener.cs (hunk 4 above)
Comment (CodeBlanch) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DiagnosticSourceEventSource/DiagnosticSourceEventSourceListener.cs]: This ended up moving into `DsesFilterAndTransform` but yes, only adding the ability to parse out `ParentRatioSampler` into `DsesFilterAndTransform.SampleFunc`.

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DsesFilterAndTransform.cs [hunk 8]
```diff
@@ -404,9 +404,6 @@ public void Dispose()
         }
     }
 
-    [UnconditionalSuppressMessage("ReflectionAnalysis", "IL2112:ReflectionToRequiresUnreferencedCode",
```
Comment (eerhardt) [inline src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DsesFilterAndTransform.cs]: @sbomer @agocke - CI was previously failing with https://github.com/dotnet/runtime/pull/104134/checks?check_run_id=27545810735

> /_/src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DsesFilterAndTransform.cs(1005,9): error IL2121: (NETCORE_ENGINEERING_TELEMETRY=Build) System.Diagnostics.DsesFilterAndTransform.MakeImplicitTransforms(Type): Unused 'UnconditionalSuppressMessageAttribute' for warning 'IL2112'. Consider removing the unused warning suppression.


Do you know why these warnings weren't happening before the code was moved out to separate files?

**Review by noahfalk — APPROVED** [review]
LGTM
Also heads up my internet is out and I'm doing what I can from my phone.

**Comment by noahfalk** [comment]
@tarekgh fyi

**Comment by noahfalk** [comment]
fyi @dotnet/dotnet-monitor @pharring - this change adds support for more useful sampling to Activities in DiagnosticSourceEventSource. It also contains some minor breaking changes on how Activity rules (those starting with [AS]) are handled. I'm guessing that nobody was relying on them previously. The changes:
- Each Activity is now resolved to at most one rule. Splitting Start/Stop events across multiple rules is no longer supported.
- Activity rules that used a wildcard for source name but explicitly provided the Activity name are now ignored.

File: src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DsesActivitySourceListener.cs [hunk 9]
```diff
@@ -0,0 +1,251 @@
...
+
+        ActivitySource.AddActivityListener(_activityListener);
+    }
+
+    private bool TryFindSpecForActivity(
+        string activitySourceName,
+        string activityName,
+        [NotNullWhen(true)] out DsesFilterAndTransform? spec)
+    {
+        if (_specsBySourceNameAndActivityName != null)
```
[the remark this answers is not in the document]
Comment (CodeBlanch) [reply src/libraries/System.Diagnostics.DiagnosticSource/src/System/Diagnostics/DsesActivitySourceListener.cs:148]: @noahfalk I'm good with doing this in the future, if needed. I was wary of the cache due to the potential for it to grow unconstrained. I'm hoping the wildcard (`[AS]*`) use case will be the most common, it is optimized to not perform a lookup if there is only a wildcard rule.
