### ISSUE TITLE
[wasm] perf pipeline broken with build errors

### ISSUE THREAD

**Issue by radical** [dotnet/runtime#88108]
This broke due to api change in https://github.com/dotnet/runtime/pull/87988 .
```
[2023/06/27 04:07:21][INFO] /home/helixbot/work/A13E0928/w/B5030976/e/performance/src/benchmarks/micro/libraries/System.Collections/TryGetValue/TryGetValueTrue.cs(49,69): error CS1739: The best overload for 'ToFrozenDictionary' does not have a parameter named 'optimizeForReading' [/home/helixbot/work/A13E0928/w/B5030976/e/performance/src/benchmarks/micro/MicroBenchmarks.csproj::TargetFramework=net8.0]
[2023/06/27 04:07:21][INFO] /home/helixbot/work/A13E0928/w/B5030976/e/performance/src/benchmarks/micro/libraries/System.Collections/TryGetValue/TryGetValueFalse.cs(51,69): error CS1739: The best overload for 'ToFrozenDictionary' does not have a parameter named 'optimizeForReading' [/home/helixbot/work/A13E0928/w/B5030976/e/performance/src/benchmarks/micro/MicroBenchmarks.csproj::TargetFramework=net8.0]
[2023/06/27 04:07:21][INFO] /home/helixbot/work/A13E0928/w/B5030976/e/performance/src/benchmarks/micro/libraries/System.Collections/Create/CtorFromCollection.cs(107,101): error CS1739: The best overload for 'ToFrozenDictionary' does not have a parameter named 'optimizeForReading' [/home/helixbot/work/A13E0928/w/B5030976/e/performance/src/benchmarks/micro/MicroBenchmarks.csproj::TargetFramework=net8.0]
```

### Known Issue Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssues.md#how-to-fill-out-a-known-issue-error-section).

```json
{
  "ErrorMessage": "",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by stephentoub** [comment]
Someone with permissions needs to merge https://github.com/dotnet/performance/pull/3098

**Comment by radical** [comment]
> Someone with permissions needs to merge [dotnet/performance#3098](https://github.com/dotnet/performance/pull/3098)

ah, I was opening a PR with some other changes for this!

**Comment by radical** [comment]
Closing this as fixed by https://github.com/dotnet/performance/pull/3098 . I'll monitor new builds.
