### ISSUE TITLE
Build is broken for main due to conflicting PRs

### ISSUE THREAD

**Issue by stephentoub** [dotnet/runtime#102930]
https://github.com/dotnet/runtime/pull/102636 and https://github.com/dotnet/runtime/pull/102034 got merged in parallel and conflict. The latter made GenericCache generic and the former uses the non-generic.
```
D:\repos\runtime\src\coreclr\System.Private.CoreLib\src\System\RuntimeType.CoreCLR.cs(3970,17): error CS0305: Using the generic type 'GenericCache<TKey, TValue>' requires 2 type arguments [D:\repos\runtime\src\coreclr\System.Private.CoreLib\System.Private.CoreLib.cspro
j]
D:\repos\runtime\src\coreclr\System.Private.CoreLib\src\System\RuntimeType.CoreCLR.cs(3972,29): error CS0122: 'RuntimeType.ActivatorCache.ActivatorCache(RuntimeType)' is inaccessible due to its protection level [D:\repos\runtime\src\coreclr\System.Private.CoreLib\Syste
m.Private.CoreLib.csproj]
D:\repos\runtime\src\coreclr\System.Private.CoreLib\src\System\RuntimeType.CoreCLR.cs(3973,17): error CS0305: Using the generic type 'GenericCache<TKey, TValue>' requires 2 type arguments [D:\repos\runtime\src\coreclr\System.Private.CoreLib\System.Private.CoreLib.cspro
j]
```
cc: @jkoritzinsky, @AaronRobinsonMSFT
