### ISSUE TITLE
armel build broken due to unused arguments in CryptoNative_MLDsaGetPalId

### ISSUE THREAD

**Issue by janvorli** [dotnet/runtime#115805]
A recent change has broken armel build, which now fails in the CI with
```
  /__w/1/s/src/native/libs/System.Security.Cryptography.Native/pal_evp_pkey_ml_dsa.c:10:85: error: unused parameter 'hasSeed' [-Werror,-Wunused-parameter]
     10 | int32_t CryptoNative_MLDsaGetPalId(const EVP_PKEY* pKey, int32_t* mldsaId, int32_t* hasSeed, int32_t* hasSecretKey)
        |                                                                                     ^
  /__w/1/s/src/native/libs/System.Security.Cryptography.Native/pal_evp_pkey_ml_dsa.c:10:103: error: unused parameter 'hasSecretKey' [-Werror,-Wunused-parameter]
     10 | int32_t CryptoNative_MLDsaGetPalId(const EVP_PKEY* pKey, int32_t* mldsaId, int32_t* hasSeed, int32_t* hasSecretKey)
        |                                                                                                       ^
```

**Comment by janvorli** [comment]
This was introduced by https://github.com/dotnet/runtime/pull/115569
cc: @PranavSenthilnathan

**Comment by vcsjones** [comment]
This fix for this was just merged in https://github.com/dotnet/runtime/pull/115767
