### ISSUE TITLE
Unable to run src/tests locally

### ISSUE THREAD

**Issue by jkotas** [dotnet/runtime#43984]
Trying to run the tests locally according to https://github.com/dotnet/runtime/blob/master/docs/workflow/testing/coreclr/windows-test-instructions.md#running-tests :

```
D:\runtime\src\tests>run.cmd
python "D:\runtime\src\tests\\..\..\src\tests\run.py" -arch x64 -build_type Debug
Traceback (most recent call last):
  File "D:\runtime\src\tests\\..\..\src\tests\run.py", line 1642, in <module>
    sys.exit(main(args))
  File "D:\runtime\src\tests\\..\..\src\tests\run.py", line 1616, in main
    args = setup_args(args)
  File "D:\runtime\src\tests\\..\..\src\tests\run.py", line 1005, in setup_args
    requires_coreroot = args.host_os.lower() != "browser" and args.host_os.lower() != "android"
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by jkotas** [comment]
This is regression that was introduced by #42683 . @fanyang-mono Could you please take a look?

**Comment by jkotas** [comment]
cc @akoeplinger
