### ISSUE TITLE
Source-build fails to build w/CS0208: Cannot take the address of, get the size of, or declare a pointer to a managed type

### ISSUE THREAD

**Issue by MichaelSimons** [dotnet/runtime#73850]
The latest dependency flow into installer's broke source-build w/the following errors:

```
  /tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.CoreCLR.cs(319,50): error CS0208: Cannot take the address of, get the size of, or declare a pointer to a managed type ('MethodBase.StackAllocatedByRefs') [/tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/System.Private.CoreLib/System.Private.CoreLib.csproj]
    /tarball/src/runtime/artifacts/source-build/self/src/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBase.cs(249,23): error CS0208: Cannot take the address of, get the size of, or declare a pointer to a managed type ('ByReference') [/tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/System.Private.CoreLib/System.Private.CoreLib.csproj]
    /tarball/src/runtime/artifacts/source-build/self/src/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBase.cs(254,23): error CS0208: Cannot take the address of, get the size of, or declare a pointer to a managed type ('ByReference') [/tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/System.Private.CoreLib/System.Private.CoreLib.csproj]
    /tarball/src/runtime/artifacts/source-build/self/src/src/libraries/System.Private.CoreLib/src/System/Reflection/RuntimeConstructorInfo.cs(149,54): error CS0208: Cannot take the address of, get the size of, or declare a pointer to a managed type ('MethodBase.StackAllocatedByRefs') [/tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/System.Private.CoreLib/System.Private.CoreLib.csproj]
    /tarball/src/runtime/artifacts/source-build/self/src/src/libraries/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs(146,54): error CS0208: Cannot take the address of, get the size of, or declare a pointer to a managed type ('MethodBase.StackAllocatedByRefs') [/tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/System.Private.CoreLib/System.Private.CoreLib.csproj]
    /tarball/src/runtime/artifacts/source-build/self/src/src/libraries/System.Private.CoreLib/src/System/Reflection/RuntimeConstructorInfo.cs(302,54): error CS0208: Cannot take the address of, get the size of, or declare a pointer to a managed type ('MethodBase.StackAllocatedByRefs') [/tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/System.Private.CoreLib/System.Private.CoreLib.csproj]
    /tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/System.Private.CoreLib/src/System/Reflection/Emit/DynamicMethod.cs(507,54): error CS0208: Cannot take the address of, get the size of, or declare a pointer to a managed type ('MethodBase.StackAllocatedByRefs') [/tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/System.Private.CoreLib/System.Private.CoreLib.csproj]
```

[CI Build Failure](https://dev.azure.com/dnceng/internal/_build/results?buildId=1939153&view=logs&j=87a4ea9e-995f-5db7-cd08-b96ecbe4e25a&t=f8cf185b-29d6-52a5-84b1-6edc34dd9fec) (internal Microsoft link)

Source-build does build with the latest compiler version and toolset which is likely a contributing factor here.

**Comment by MichaelSimons** [comment]
This is currently blocking RC1.

**Comment by hoyosjs** [comment]
Oof. looks like we're using a roslyn that's not new enough for the bootstrap? cc: @AaronRobinsonMSFT

**Comment by AaronRobinsonMSFT** [comment]
Thanks @hoyosjs. The fix for this is in-flight https://github.com/dotnet/runtime/pull/73466.

**Comment by jkotas** [comment]
This issue was introduced by https://github.com/dotnet/roslyn/pull/63209 . I do not see the fixes for it in https://github.com/dotnet/runtime/pull/73466 yet. 

The problem is that C# disallows taking an address of ref struct that contains ref fields. It is artificial C# limitation that does not exist in IL. It will be pain to workaround it without taking a perf hit. Any chance we can relax the C# rules and allow taking an address of ref structs that contain object references?

**Comment by AaronRobinsonMSFT** [comment]
> I do not see the fixes for it in https://github.com/dotnet/runtime/pull/73466 yet.

I know I've discussed this issue with @cston offline. I thought this issue was included in that PR. Let me follow-up offline.

**Comment by cston** [comment]
For now, we're reverting https://github.com/dotnet/roslyn/pull/63209 to unblock moving to the latest compiler. See https://github.com/dotnet/roslyn/pull/63367.

**Comment by MichaelSimons** [comment]
We assembled a source-build run with patches that revert https://github.com/dotnet/roslyn/pull/63209 and pull in the https://github.com/dotnet/runtime/pull/73466 changes with the very last sdk/roslyn and a new break appeared.  You can see the source-build configuration here - https://github.com/dotnet/installer/pull/14319

```
    /tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/nativeaot/Runtime.Base/src/System/Runtime/ExceptionHandling.cs(548,28): error CS8167: Cannot return by reference a member of parameter 'exInfo' because it is not a ref or out parameter [/tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/nativeaot/System.Private.CoreLib/src/System.Private.CoreLib.csproj]
    /tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/nativeaot/Runtime.Base/src/System/Runtime/ExceptionHandling.cs(548,13): error CS8350: This combination of arguments to 'EH.DispatchEx(ref StackFrameIterator, ref EH.ExInfo, uint)' is disallowed because it may expose variables referenced by parameter 'frameIter' outside of their declaration scope [/tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/nativeaot/System.Private.CoreLib/src/System.Private.CoreLib.csproj]
    /tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/nativeaot/Runtime.Base/src/System/Runtime/ExceptionHandling.cs(570,28): error CS8167: Cannot return by reference a member of parameter 'exInfo' because it is not a ref or out parameter [/tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/nativeaot/System.Private.CoreLib/src/System.Private.CoreLib.csproj]
    /tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/nativeaot/Runtime.Base/src/System/Runtime/ExceptionHandling.cs(570,13): error CS8350: This combination of arguments to 'EH.DispatchEx(ref StackFrameIterator, ref EH.ExInfo, uint)' is disallowed because it may expose variables referenced by parameter 'frameIter' outside of their declaration scope [/tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/nativeaot/System.Private.CoreLib/src/System.Private.CoreLib.csproj]
    /tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/nativeaot/Runtime.Base/src/System/Runtime/ExceptionHandling.cs(587,28): error CS8167: Cannot return by reference a member of parameter 'exInfo' because it is not a ref or out parameter [/tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/nativeaot/System.Private.CoreLib/src/System.Private.CoreLib.csproj]
    /tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/nativeaot/Runtime.Base/src/System/Runtime/ExceptionHandling.cs(587,13): error CS8350: This combination of arguments to 'EH.DispatchEx(ref StackFrameIterator, ref EH.ExInfo, uint)' is disallowed because it may expose variables referenced by parameter 'frameIter' outside of their declaration scope [/tarball/src/runtime/artifacts/source-build/self/src/src/coreclr/nativeaot/System.Private.CoreLib/src/System.Private.CoreLib.csproj]
```

**Comment by cston** [comment]
Sorry for missing the nativeaot case. I've created https://github.com/dotnet/runtime/pull/73883 which compiles `clr+libs+libs.tests` without errors.

**Comment by cston** [comment]
https://github.com/dotnet/roslyn/pull/63367 and https://github.com/dotnet/runtime/pull/73883 have been merged.

**Comment by cston** [comment]
@jeffschwMSFT, @MichaelSimons, I've closed this issue since the PRs for the two issues have been merged. Please re-open if there is still something blocking here.
