### PR TITLE
Set value for BIGENDIAN

### LINKED ISSUE #104036: BIGENDIAN not defined while building eventpipe on s390x
Our s390x CI cross builds are failing with:
```
      /workdir/dotnet/src/runtime/src/native/eventpipe/ep-stream.c:233:14: error: expected value in expression
      #if BIGENDIAN
                   ^
      1 error generated.
```
This probably regressed in https://github.com/dotnet/runtime/pull/103184.

cc @jkoritzinsky @uweigand @omajid

### PR DESCRIPTION
**Pull request by jkoritzinsky**
Fixes https://github.com/dotnet/runtime/issues/104036

### CODE REVIEW

**Comment by jkoritzinsky** [comment]
This fixes the s390x build.

**Review by jkotas — APPROVED** [review]
