### ISSUE TITLE
superpmi-collect fails with "module 'asyncio' has no attribute 'get_running_loop'"

### ISSUE THREAD

**Issue by jakobbotsch** [dotnet/runtime#89618]
A number of our supermpi-collect jobs are failing with this error after #89404.

cc @TIHan

**Comment by jakobbotsch** [comment]
Fixed by #89663
