### ISSUE TITLE
Blazor WebAssembly preview 7 failing with 'Why are we accessing an entry that is not allocated'

### ISSUE THREAD

**Issue by twsouthwick** [dotnet/runtime#40037]
I was playing around with an MVVM project for blazor and updating it to .NET 5.0. Everything worked fine on 3.2.0. However, when I updated to .NET 5.0 preview 7, I started getting the following:

```
Debugging hotkey: Shift+Alt+D (when application has focus)
:50062/favicon.ico:1 Failed to load resource: the server responded with a status of 404 (Not Found)
blazor.webassembly.js:1 blazor Loaded 8.65 MB resourcesThis application was built with linking (tree shaking) disabled. Published applications will be significantly smaller.
dotnet.5.0.0-preview.7.20364.11.js:1 Stacktrace: 

dotnet.5.0.0-preview.7.20364.11.js:1 Error
    at 179491 (dotnet.5.0.0-preview.7.20364.11.js:1)
    at _emscripten_asm_const_iii (dotnet.5.0.0-preview.7.20364.11.js:1)
    at wasm_logger (:50062/<anonymous>:wasm-function[2750]:0x836cf)
    at eglib_log_adapter (:50062/<anonymous>:wasm-function[5212]:0xe557c)
    at monoeg_g_logstr (:50062/<anonymous>:wasm-function[3859]:0xa5294)
    at monoeg_g_logv_nofree (:50062/<anonymous>:wasm-function[1915]:0x5477f)
    at monoeg_g_log (:50062/<anonymous>:wasm-function[115]:0x2cea)
    at sgen_array_list_get_slot.2 (:50062/<anonymous>:wasm-function[1298]:0x393f1)
    at sgen_gchandle_get_target (:50062/<anonymous>:wasm-function[3599]:0x9a300)
    at mono_gchandle_get_target_internal (:50062/<anonymous>:wasm-function[320]:0xa1e1)
blazor.webassembly.js:1 Why are we accessing an entry that is not allocated
d.printErr @ blazor.webassembly.js:1
put_char @ dotnet.5.0.0-preview.7.20364.11.js:1
write @ dotnet.5.0.0-preview.7.20364.11.js:1
write @ dotnet.5.0.0-preview.7.20364.11.js:1
doWritev @ dotnet.5.0.0-preview.7.20364.11.js:1
_fd_write @ dotnet.5.0.0-preview.7.20364.11.js:1
__stdio_write @ 00526cca:1
__vfprintf_internal @ 00526cca:1
vfiprintf @ 00526cca:1
fiprintf @ 00526cca:1
wasm_logger @ 00526cca:1
eglib_log_adapter @ 00526cca:1
monoeg_g_logstr @ 00526cca:1
monoeg_g_logv_nofree @ 00526cca:1
monoeg_g_log @ 00526cca:1
sgen_array_list_get_slot.2 @ 00526cca:1
sgen_gchandle_get_target @ 00526cca:1
mono_gchandle_get_target_internal @ 00526cca:1
mono_gchandle_get_target_handle @ 00526cca:1
ves_icall_System_GCHandle_InternalGet_raw @ 00526cca:1
do_icall @ 00526cca:1
do_icall_wrapper @ 00526cca:1
interp_exec_method @ 00526cca:1
interp_runtime_invoke @ 00526cca:1
mono_jit_runtime_invoke @ 00526cca:1
do_runtime_invoke @ 00526cca:1
mono_runtime_invoke_checked @ 00526cca:1
mono_runtime_try_invoke_array @ 00526cca:1
ves_icall_InternalInvoke @ 00526cca:1
ves_icall_InternalInvoke_raw @ 00526cca:1
do_icall @ 00526cca:1
do_icall_wrapper @ 00526cca:1
interp_exec_method @ 00526cca:1
interp_runtime_invoke @ 00526cca:1
mono_jit_runtime_invoke @ 00526cca:1
do_runtime_invoke @ 00526cca:1
mono_runtime_try_invoke @ 00526cca:1
mono_runtime_invoke @ 00526cca:1
mono_wasm_invoke_method @ 00526cca:1
Module._mono_wasm_invoke_method @ dotnet.5.0.0-preview.7.20364.11.js:1
call_method @ dotnet.5.0.0-preview.7.20364.11.js:1
(anonymous) @ dotnet.5.0.0-preview.7.20364.11.js:1
beginInvokeDotNetFromJS @ blazor.webassembly.js:1
s @ blazor.webassembly.js:1
e.invokeMethodAsync @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
r @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
r @ blazor.webassembly.js:1
d @ blazor.webassembly.js:1
f @ blazor.webassembly.js:1
l @ blazor.webassembly.js:1
invokeJSFromDotNet @ blazor.webassembly.js:1
_mono_wasm_invoke_js_marshalled @ dotnet.5.0.0-preview.7.20364.11.js:1
do_icall @ 00526cca:1
do_icall_wrapper @ 00526cca:1
interp_exec_method @ 00526cca:1
interp_runtime_invoke @ 00526cca:1
mono_jit_runtime_invoke @ 00526cca:1
do_runtime_invoke @ 00526cca:1
mono_runtime_invoke_checked @ 00526cca:1
mono_runtime_try_invoke_array @ 00526cca:1
ves_icall_InternalInvoke @ 00526cca:1
ves_icall_InternalInvoke_raw @ 00526cca:1
do_icall @ 00526cca:1
do_icall_wrapper @ 00526cca:1
interp_exec_method @ 00526cca:1
interp_runtime_invoke @ 00526cca:1
mono_jit_runtime_invoke @ 00526cca:1
do_runtime_invoke @ 00526cca:1
mono_runtime_invoke_checked @ 00526cca:1
mono_runtime_try_invoke_array @ 00526cca:1
ves_icall_InternalInvoke @ 00526cca:1
ves_icall_InternalInvoke_raw @ 00526cca:1
do_icall @ 00526cca:1
do_icall_wrapper @ 00526cca:1
interp_exec_method @ 00526cca:1
interp_runtime_invoke @ 00526cca:1
mono_jit_runtime_invoke @ 00526cca:1
do_runtime_invoke @ 00526cca:1
mono_runtime_try_invoke @ 00526cca:1
mono_runtime_invoke @ 00526cca:1
mono_wasm_invoke_method @ 00526cca:1
Module._mono_wasm_invoke_method @ dotnet.5.0.0-preview.7.20364.11.js:1
call_method @ dotnet.5.0.0-preview.7.20364.11.js:1
(anonymous) @ dotnet.5.0.0-preview.7.20364.11.js:1
beginInvokeDotNetFromJS @ blazor.webassembly.js:1
s @ blazor.webassembly.js:1
e.invokeMethodAsync @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
t.dispatchEvent @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
e.onGlobalEvent @ blazor.webassembly.js:1
Show 71 more frames
blazor.webassembly.js:1 undefined
blazor.webassembly.js:1 undefined
d.printErr @ blazor.webassembly.js:1
abort @ dotnet.5.0.0-preview.7.20364.11.js:1
_abort @ dotnet.5.0.0-preview.7.20364.11.js:1
wasm_logger @ 00526cca:1
eglib_log_adapter @ 00526cca:1
monoeg_g_logstr @ 00526cca:1
monoeg_g_logv_nofree @ 00526cca:1
monoeg_g_log @ 00526cca:1
sgen_array_list_get_slot.2 @ 00526cca:1
sgen_gchandle_get_target @ 00526cca:1
mono_gchandle_get_target_internal @ 00526cca:1
mono_gchandle_get_target_handle @ 00526cca:1
ves_icall_System_GCHandle_InternalGet_raw @ 00526cca:1
do_icall @ 00526cca:1
do_icall_wrapper @ 00526cca:1
interp_exec_method @ 00526cca:1
interp_runtime_invoke @ 00526cca:1
mono_jit_runtime_invoke @ 00526cca:1
do_runtime_invoke @ 00526cca:1
mono_runtime_invoke_checked @ 00526cca:1
mono_runtime_try_invoke_array @ 00526cca:1
ves_icall_InternalInvoke @ 00526cca:1
ves_icall_InternalInvoke_raw @ 00526cca:1
do_icall @ 00526cca:1
do_icall_wrapper @ 00526cca:1
interp_exec_method @ 00526cca:1
interp_runtime_invoke @ 00526cca:1
mono_jit_runtime_invoke @ 00526cca:1
do_runtime_invoke @ 00526cca:1
mono_runtime_try_invoke @ 00526cca:1
mono_runtime_invoke @ 00526cca:1
mono_wasm_invoke_method @ 00526cca:1
Module._mono_wasm_invoke_method @ dotnet.5.0.0-preview.7.20364.11.js:1
call_method @ dotnet.5.0.0-preview.7.20364.11.js:1
(anonymous) @ dotnet.5.0.0-preview.7.20364.11.js:1
beginInvokeDotNetFromJS @ blazor.webassembly.js:1
s @ blazor.webassembly.js:1
e.invokeMethodAsync @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
r @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
r @ blazor.webassembly.js:1
d @ blazor.webassembly.js:1
f @ blazor.webassembly.js:1
l @ blazor.webassembly.js:1
invokeJSFromDotNet @ blazor.webassembly.js:1
_mono_wasm_invoke_js_marshalled @ dotnet.5.0.0-preview.7.20364.11.js:1
do_icall @ 00526cca:1
do_icall_wrapper @ 00526cca:1
interp_exec_method @ 00526cca:1
interp_runtime_invoke @ 00526cca:1
mono_jit_runtime_invoke @ 00526cca:1
do_runtime_invoke @ 00526cca:1
mono_runtime_invoke_checked @ 00526cca:1
mono_runtime_try_invoke_array @ 00526cca:1
ves_icall_InternalInvoke @ 00526cca:1
ves_icall_InternalInvoke_raw @ 00526cca:1
do_icall @ 00526cca:1
do_icall_wrapper @ 00526cca:1
interp_exec_method @ 00526cca:1
interp_runtime_invoke @ 00526cca:1
mono_jit_runtime_invoke @ 00526cca:1
do_runtime_invoke @ 00526cca:1
mono_runtime_invoke_checked @ 00526cca:1
mono_runtime_try_invoke_array @ 00526cca:1
ves_icall_InternalInvoke @ 00526cca:1
ves_icall_InternalInvoke_raw @ 00526cca:1
do_icall @ 00526cca:1
do_icall_wrapper @ 00526cca:1
interp_exec_method @ 00526cca:1
interp_runtime_invoke @ 00526cca:1
mono_jit_runtime_invoke @ 00526cca:1
do_runtime_invoke @ 00526cca:1
mono_runtime_try_invoke @ 00526cca:1
mono_runtime_invoke @ 00526cca:1
mono_wasm_invoke_method @ 00526cca:1
Module._mono_wasm_invoke_method @ dotnet.5.0.0-preview.7.20364.11.js:1
call_method @ dotnet.5.0.0-preview.7.20364.11.js:1
(anonymous) @ dotnet.5.0.0-preview.7.20364.11.js:1
beginInvokeDotNetFromJS @ blazor.webassembly.js:1
s @ blazor.webassembly.js:1
e.invokeMethodAsync @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
t.dispatchEvent @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
(anonymous) @ blazor.webassembly.js:1
e.onGlobalEvent @ blazor.webassembly.js:1
Show 64 more frames
dotnet.5.0.0-preview.7.20364.11.js:1 Uncaught (in promise) RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info.
    at abort (http://localhost:50062/_framework/dotnet.5.0.0-preview.7.20364.11.js:1:14793)
    at _abort (http://localhost:50062/_framework/dotnet.5.0.0-preview.7.20364.11.js:1:103998)
    at wasm_logger (<anonymous>:wasm-function[2750]:0x836f1)
    at eglib_log_adapter (<anonymous>:wasm-function[5212]:0xe557c)
    at monoeg_g_logstr (<anonymous>:wasm-function[3859]:0xa5294)
    at monoeg_g_logv_nofree (<anonymous>:wasm-function[1915]:0x5477f)
    at monoeg_g_log (<anonymous>:wasm-function[115]:0x2cea)
    at sgen_array_list_get_slot.2 (<anonymous>:wasm-function[1298]:0x393f1)
    at sgen_gchandle_get_target (<anonymous>:wasm-function[3599]:0x9a300)
    at mono_gchandle_get_target_internal (<anonymous>:wasm-function[320]:0xa1e1)
```

This appears to happen when the https://github.com/chris579/MvvmBlazor tries to bind to some of the events using a weak listener pattern. In order to hook up an event it does the following:

```csharp
_eventInfo.AddEventHandler(source,
Delegate.CreateDelegate(_eventInfo.EventHandlerType, this, nameof(HandleEvent)));
```

It then stores the `source` in a `WeakReference<>`. It also seems that this source (which is a readonly field) ends up being null at some point, but is always set in the constructor. This only occurs on .NET 5.0 Preview 7 (the last version to test it was ASP.NET Core 3.2). I did find that if I update the library to not use `Delegate.CreateDelegate`, there is no issue (ie see https://github.com/twsouthwick/MvvmBlazor/commit/795bb8a8add282c60e66e6d2d523f3fabb089f2b).

A repro is available at https://github.com/twsouthwick/MvvmBlazor/tree/repro via the `Repro` project and the important part is in the `ReproComponent` where it will cause the error when trying to run the line with `Model.Counts.Add(1)`.

```csharp
   public class ReproComponent : MvvmComponentBase
    {
        private readonly TestModel Model = new TestModel();

        protected override void BuildRenderTree(RenderTreeBuilder builder)
        {
            Bind(Model, t => t.Counts);

            Model.Counts.Add(1);

            base.BuildRenderTree(builder);
        }

        private class TestModel : ViewModelBase
        {
            public ObservableCollection<int> Counts { get; } = new ObservableCollection<int>();
        }
    }
```

**Comment by marek-safar** [comment]
@SamMonoRT
