### PR TITLE
Fixed serialization of hidden base class members

### LINKED ISSUE #30964: JSON Serialization Name Collision with hidden properties
Take Two Classes:

```cs
public class ClassA
{
    public List<int> SomeList { get; set; }
}

public class ClassB : ClassA
{
    new public IEnumerable<int> SomeList { get; set; }
}
```

If `ClassB` is serialized an exception is thrown:

>The JSON property name for 'ClassB.SomeList' collides with another property.

This seems like unwanted behavior.

### LINKED ISSUE #32106: JSON serializer ignores a base public property hidden by a new slot private one
The following code should serialize the `MyString` property of `ClassWithPublicProperty`, but it doesn't happen because `GetProprties(BindingFlags.Instance | BindingFlags.Public)` doesn't return base properties which are hidden by a new slot member.

```csharp
var obj = new ClassWithNewSlotPrivateProperty();
string json = JsonSerializer.Serialize(obj);
```

```csharp
public class ClassWithPublicProperty
{
    public string MyString { get; set; } = "DefaultValue";
}

public class ClassWithNewSlotPrivateProperty : ClassWithPublicProperty
{
    private new string MyString { get; set; } = "NewDefaultValue";
}
```

**Expected:** `{"MyString":"DefaultValue"}`
**Actual:** `{}`

### PR DESCRIPTION
**Pull request by YohDeadfall**
Closes #32106.
Closes https://github.com/dotnet/runtime/issues/30964.

### CODE REVIEW

File: src/libraries/System.Text.Json/tests/Serialization/PropertyVisibilityTests.cs [hunk 1]
```diff
@@ -11,6 +11,231 @@ namespace System.Text.Json.Serialization.Tests
 {
     public static class PropertyVisibilityTests
```
Comment (layomia) [inline src/libraries/System.Text.Json/tests/Serialization/PropertyVisibilityTests.cs]: We need a couple more tests involving 3 levels of inheritance, particularly where we have collisions on public properties defined at different levels.

**Review by layomia — COMMENTED** [review]
Just a few more test cases to consider.

File: src/libraries/System.Text.Json/tests/Serialization/PropertyVisibilityTests.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (YohDeadfall) [reply src/libraries/System.Text.Json/tests/Serialization/PropertyVisibilityTests.cs]: It's a naming used by EF Core for long test names, but am okay with changing this if you want, but first compare names.

**Before**: `Serialize_base_public_property_on_conflict_with_derived_private`
**After**: `SerializeBasePublicPropertyOnConflictWithDerivedPrivate`

The first one is more readable while the second looks like encoded data and is hard to read. So are you sure that pascal case is better? I can rename other tests and give them meaningful names instead of current (:

[the remark this answers is not in the document]
Comment (layomia) [reply src/libraries/System.Text.Json/tests/Serialization/PropertyVisibilityTests.cs]: I do underscore-delimited pascal case chunks in such cases, e.g. `Serialize_BasePublicProperty_OnConflictWithDerivedPrivate`. The **before** pattern isn't used anywhere else in this codebase.

**Review by layomia — CHANGES_REQUESTED** [review]
This PR should fix https://github.com/dotnet/runtime/issues/30964 as well.

We need tests for the scenarios in https://github.com/dotnet/runtime/issues/30964#issuecomment-581168793, particularly this case:

```C#
public class MyClass
{
    // This should be ignored.
    public int MyNumber { get; set; }
}
	
public class MyDerivedClass : MyClass
{
    // This should be (de)serialized.
    new public double MyNumber { get; set; }
}
```

**Comment by YohDeadfall** [comment]
@layomia I finally found some time to finish this, but there is one question. Is there any reason to create a `JsonProperyInfo` for properties marked as ignored? Probably such members should be filtered out before creation `JsonProperyInfo`s for them, or we could ignore suck infos and not to add them into a cache.

This will help with two things:
* eliminate visibility checks causes by name collisions;
* decrease memory usage.

If an member exists, then it's visible already (at least supports serialization or deserialization separately). If it's in a base class, we will overwrite it. Otherwise, throw an exception.

**Comment by layomia** [comment]
> Is there any reason to create a `JsonProperyInfo` for properties marked as ignored?

We need a `JsonPropertyInfo` in the cache for such properties to distinguish between ignored properties (where we skip), and data that doesn't map to any members (where we add to the data extension dictionary property, if present)

**Review by layomia — COMMENTED** [review]
https://github.com/dotnet/runtime/pull/32107#pullrequestreview-366417718 is yet to be addressed.

**Comment by layomia** [comment]
> Is there any reason to create a `JsonProperyInfo` for properties marked as ignored?

Creating a `JsonPropertyInfo` for ignored properties helps us distinguish between JSON to be ignored on deserialization, or [JSON to be put in extension data](https://github.com/dotnet/runtime/blob/54f34bbf56207ec80b05bae243333d2d05452527/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Read.HandlePropertyName.cs#L38) (if available). 

Perhaps we can remove instances where [`JsonPropertyInfo.ShouldSerialize`](https://github.com/dotnet/runtime/blob/54f34bbf56207ec80b05bae243333d2d05452527/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonPropertyInfo.cs#L298) is false from the [serialization cache](https://github.com/dotnet/runtime/blob/54f34bbf56207ec80b05bae243333d2d05452527/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.Cache.cs#L42) since we'll never serialize, but that should be considered outside of this PR.

**Comment by layomia** [comment]
Sample test failure log: https://helix.dot.net/api/2019-06-17/jobs/2609f8f5-cf39-4b17-a5ec-d3ff24614993/workitems/System.Text.Json.Tests/console

**Comment by YohDeadfall** [comment]
Thanks, saw this and fixed already (:

File: src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.cs [hunk 2]
```diff
@@ -99,41 +99,45 @@ public JsonClassInfo(Type type, JsonSerializerOptions options)
...
                                     {
-                                        ThrowHelper.ThrowInvalidOperationException_SerializerPropertyNameConflict(Type, jsonPropertyInfo);
+                                        JsonPropertyInfo other = cache[jsonPropertyInfo.NameAsString];
+
+                                        if (other.ShouldDeserialize == false && other.ShouldSerialize == false)
+                                        {
+                                            // Overwrite the one just added since it has [JsonIgnore].
+                                            cache[jsonPropertyInfo.NameAsString] = jsonPropertyInfo;
+                                        }
+                                        else if (other.PropertyInfo?.Name != jsonPropertyInfo.PropertyInfo?.Name &&
```
Comment (layomia) [inline src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.cs:134]: nit: we should add a comment here saying if the property names are equal, then the `new` keyword was used to override the property.

No need to reset CI for this; I can pick this up in an upcoming PR.

File: src/libraries/System.Text.Json/tests/Serialization/PropertyVisibilityTests.cs [hunk 3]
```diff
@@ -104,10 +104,10 @@ public static void Serealize_NewSlotPublicProperty_SpecifiedJsonPropertyName()
             var obj = new ClassWithNewSlotAttributedDecimalProperty();
             string json = JsonSerializer.Serialize(obj);
 
-            Assert.Equal(@"{""MyNumeric"":1,""MyNewNumeric"":1.5}", json);
+            Assert.Equal(@"{""MyNewNumeric"":1.5,""MyNumeric"":1}", json);
```
Comment (layomia) [inline src/libraries/System.Text.Json/tests/Serialization/PropertyVisibilityTests.cs:107]: Not sure we can guarantee the order of the JSON here. Even though we add properties on more derived types to `_properyCache` first, the order isn't deterministic when we copy that over to `_propertyCacheArray` (used on serialization). We should use `Assert.Contains` here and anywhere else the tests assume a specific order (more than two properties serialized).

**Review by layomia — COMMENTED** [review]
Otherwise, LGTM. @steveharter & @Jozkee, pls take a look.

File: src/libraries/System.Text.Json/tests/Serialization/PropertyVisibilityTests.cs [hunk 4]
```diff
@@ -11,6 +11,416 @@ namespace System.Text.Json.Serialization.Tests
...
+            // Deserialize
+            json = @"{""MyString"":""NewValue""}";
+            obj = JsonSerializer.Deserialize<ClassWithIgnoredPropertyNamingConflict>(json);
+
+            Assert.Equal("DefaultValue", obj.MyString);
+            Assert.Equal("ConflictingValue", obj.ConflictingString);
+        }
+
+        [Fact]
+        public static void Ignore_PublicProperty_ConflictWithPrivateDuePolicy()
```
Comment (Jozkee) [inline src/libraries/System.Text.Json/tests/Serialization/PropertyVisibilityTests.cs:186]: Consider adding these tests:
Ignore_PublicProperty_ConflictWith**Public**DueAttributes
Ignore_PublicProperty_ConflictWith**Public**DuePolicy

File: src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.cs [hunk 5]
```diff
@@ -96,52 +96,58 @@ public JsonClassInfo(Type type, JsonSerializerOptions options)
...
                                 }
 
-                                // Non-public properties should not be included for (de)serialization.
-                                continue;
-                            }
+                                if (IsNonPublicProperty(propertyInfo))
+                                {
+                                    if (JsonPropertyInfo.GetAttribute<JsonIncludeAttribute>(propertyInfo) != null)
+                                    {
+                                        ThrowHelper.ThrowInvalidOperationException_JsonIncludeOnNonPublicInvalid(propertyInfo, Type);
```
Comment (Jozkee) [inline src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonClassInfo.cs:118]:
```suggestion
                                        ThrowHelper.ThrowInvalidOperationException_JsonIncludeOnNonPublicInvalid(propertyInfo, currentType);
```

Otherwise, in case of collision you will be displaying the derived type and the name of a preperty from the base type, which may differ.

File: src/libraries/System.Text.Json/tests/Serialization/PropertyVisibilityTests.cs [hunk 6]
```diff
@@ -11,6 +11,416 @@ namespace System.Text.Json.Serialization.Tests
...
+            Assert.Equal("ConflictingValue", obj.myString);
+        }
+
+        [Fact]
+        public static void Throw_PublicProperty_ConflictDueAttributes()
+        {
+            // Serialize
+            var obj = new ClassWithPropertyNamingConflictWhichThrows();
+            Assert.Throws<InvalidOperationException>(
+                () => JsonSerializer.Serialize(obj));
```
Comment (Jozkee) [inline src/libraries/System.Text.Json/tests/Serialization/PropertyVisibilityTests.cs:210]:
```suggestion
            InvalidOperationException ex = Assert.Throws<InvalidOperationException>(() => JsonSerializer.Serialize(obj));
            Assert.Contains($"{typeof(ClassWithPublicProperty)}.{nameof(ClassWithPublicProperty.MyString)}", ex.Message);
```

For all the `Throw` tests we should be asserting that the exception message contains the expected type+property name

**Comment by Jozkee** [comment]
>System/Text/Json/Serialization/JsonClassInfo.cs(129,73): error CS1501: No overload for method 'AddProperty' takes 4 arguments

You will need to pull the latest changes to fix the build issue.

File: src/libraries/System.Text.Json/tests/Serialization/PropertyVisibilityTests.cs (hunk 6 above)
Comment (YohDeadfall) [reply src/libraries/System.Text.Json/tests/Serialization/PropertyVisibilityTests.cs:246]: In case when there is a conflict caused in the same class, there is no way to determine which property will be the first in metadata. Therefore, I reverted the suggestion.

**Comment by YohDeadfall** [comment]
@layomia tests fail, but for unrelated to this PR issue. Should I address it here?

File: src/libraries/System.Text.Json/tests/Serialization/PropertyVisibilityTests.cs (hunk 6 above)
Comment (Jozkee) [reply src/libraries/System.Text.Json/tests/Serialization/PropertyVisibilityTests.cs:246]: Ah, good point. `MyString` is not guaranteed to be the first property seen.

**Comment by Jozkee** [comment]
It seems to me like the test failures are related to this PR since those doesn't fail on master, only here.

**Comment by YohDeadfall** [comment]
The failing test should not be affected by this PR since it deserializes an object from an empty string. That area isn't touched, but will take a deeper look.

**Comment by Jozkee** [comment]
You removed the changes to JsonClassInfo recently introduced by https://github.com/dotnet/runtime/pull/34675
https://github.com/dotnet/runtime/commit/b3e791dc6d4d43a15f97c6e41f3fcbc8d335bad5#diff-ba9769bf9ab1b28aebe3b65065b96b10
Probably when merging with master.

**Comment by YohDeadfall** [comment]
@Jozkee @layomia, I've fixed merge issues, so all tests pass.

**Review by layomia — APPROVED** [review]
Thanks a ton!

**Comment by layomia** [comment]
This is a breaking change between .NET 3.1 Core/System.Text.Json 4.7.1 and .NET 5/System.Text.Json 5.0.0.

Rather than only observing properties visible from the type to be serialized, the serializer looks at the properties for all the base types in the inheritance chain. This means that `InvalidOperationException` could be thrown if there is JSON property name conflict between inheritance levels, if the property higher in the inheritance chain was not hidden by the property in the more derived class (by overriding or with the `new` operator).

The conflict would have to be fixed to avoid this exception. The most common way might be to place `[JsonIgnore]` on the conflicting property higher up in the inheritance chain.

**Comment by layomia** [comment]
Follow up: the breaking change this PR introduced was mitigated with https://github.com/dotnet/runtime/pull/36936.

**Comment by danmosemsft** [comment]
@layomia this is labeled breaking change. Can you please open an issue if necessary with https://github.com/dotnet/docs/issues/new?template=dotnet-breaking-change.md 

I don't [see an existing one](https://github.com/dotnet/docs/issues?q=+is%3Aissue+label%3Abreaking-change+)

**Comment by layomia** [comment]
Removing the breaking-change labels from this PR since the breaking change it introduced (https://github.com/dotnet/runtime/pull/32107#issuecomment-633115780) has been mitigated in follow up PRs https://github.com/dotnet/runtime/pull/36936 & https://github.com/dotnet/runtime/pull/37720 to avoid breaking the OpenMU app from internal AppCompat runs - https://github.com/dotnet/runtime/issues/37640.
