### ISSUE TITLE
BIGENDIAN not defined while building eventpipe on s390x

### ISSUE THREAD

**Issue by tmds** [dotnet/runtime#104036]
Our s390x CI cross builds are failing with:
```
      /workdir/dotnet/src/runtime/src/native/eventpipe/ep-stream.c:233:14: error: expected value in expression
      #if BIGENDIAN
                   ^
      1 error generated.
```
This probably regressed in https://github.com/dotnet/runtime/pull/103184.

cc @jkoritzinsky @uweigand @omajid
