### ISSUE TITLE
Test build failure: "coreclr Common Pri1 Test Build AnyOS AnyCPU checked" CI job fails

### ISSUE THREAD

**Issue by BruceForstall** [dotnet/runtime#108076]
Apparently starting with https://dev.azure.com/dnceng-public/public/_build/results?buildId=813293&view=results

```
    GCSimulator_127 -> /__w/1/s/artifacts/tests/coreclr/AnyOS.x64.Checked/GC/Scenarios/GCSimulator/GCSimulator_127/GCSimulator_127.dll
/__w/1/s/artifacts/tests/coreclr/obj/AnyOS.x64.Checked/Managed/CoreMangLib/CoreMangLib/generated/XUnitWrapperGenerator/XUnitWrapperGenerator.XUnitWrapperGenerator/FullRunner.g.cs(618,61): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. [/__w/1/s/src/tests/CoreMangLib/CoreMangLib.csproj] [/__w/1/s/src/tests/build.proj]
##[error]artifacts/tests/coreclr/obj/AnyOS.x64.Checked/Managed/CoreMangLib/CoreMangLib/generated/XUnitWrapperGenerator/XUnitWrapperGenerator.XUnitWrapperGenerator/FullRunner.g.cs(618,61): error CS0012: The type 'Object' is defined in an assembly that is not referenced. You must add a reference to assembly 'System.Runtime, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null'. [/__w/1/s/src/tests/CoreMangLib/CoreMangLib.csproj]
    GCSimulator_129 -> /__w/1/s/artifacts/tests/coreclr/AnyOS.x64.Checked/GC/Scenarios/GCSimulator/GCSimulator_129/GCSimulator_129.dll
```

Maybe due to https://github.com/dotnet/runtime/pull/104731? @jkotas @huoyaoyuan

**Comment by BruceForstall** [comment]
Fails in `runtime-coreclr outerloop`, but also in every outerloop pipeline that needs Pri-1 coreclr tests

**Comment by BruceForstall** [comment]
@jkotas Did your test https://github.com/dotnet/runtime/pull/108077 verify that the build failure was caused by #104731?

Looks like your "Fix?" there didn't work.

**Comment by BruceForstall** [comment]
A possible "big hammer" fix (that is not a full revert): https://github.com/dotnet/runtime/pull/108093

**Comment by jkotas** [comment]
> @jkotas Did your test https://github.com/dotnet/runtime/pull/108077 verify that the build failure was caused by https://github.com/dotnet/runtime/pull/104731?

Yes, it was caused by #104731. I have pushed a new change that should fix the build break (verified locally).

**Comment by huoyaoyuan** [comment]
I copied the pattern from some other test and it was successful when I tested it locally. I don't recall much details, but I had some issues building tests and did some workaround.
