### ISSUE TITLE
[ci-scan] Build break: ILCompiler.ReadyToRun.Tests fails CS7036 on ReadyToRunCompilerContext ctor

### ISSUE THREAD

**Issue by lewing** [dotnet/runtime#131504]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=1530244
Build error leg or test failing: linux-x64 checked CLR_Tools_Tests - ILCompiler.ReadyToRun.Tests

`main` @ 95b776802e7925130bde329247a2679b718f1e06 does not build.

Semantic merge conflict between two PRs that landed within ~18 hours of each other,
so neither one's CI saw the other:

- #131429 (merged 2026-07-27T20:14Z) added
  `src/coreclr/tools/aot/ILCompiler.ReadyToRun.Tests/WasmArgumentLayoutTests.cs`,
  which constructs `ReadyToRunCompilerContext` with 5 arguments.
- #130622 (merged 2026-07-28T14:04Z) added a `bool targetAllowsRuntimeCodeGeneration`
  parameter to that constructor, making it 6.

## Error Details

```
/__w/1/s/src/coreclr/tools/aot/ILCompiler.ReadyToRun.Tests/WasmArgumentLayoutTests.cs(166,45): error CS7036: There is no argument given that corresponds to the required parameter 'instructionSetSupport' of 'ReadyToRunCompilerContext.ReadyToRunCompilerContext(TargetDetails, SharedGenericsMode, bool, bool, InstructionSetSupport, CompilerTypeSystemContext)' [/__w/1/s/src/coreclr/tools/aot/ILCompiler.ReadyToRun.Tests/ILCompiler.ReadyToRun.Tests.csproj]
```

## Error Message

```json
{
  "ErrorMessage": "WasmArgumentLayoutTests.cs(166,45): error CS7036: There is no argument given that corresponds to the required parameter 'instructionSetSupport'",
  "ErrorPattern": "",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

> [!NOTE]
> This issue body was drafted with GitHub Copilot and reviewed by me before filing.

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=1530244
**Error message validated:** `[WasmArgumentLayoutTests.cs(166,45): error CS7036: There is no argument given that corresponds to the required parameter 'instructionSetSupport'`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 7/28/2026 10:51:17 PM UTC

#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|0|0|

**Comment by jeffschwMSFT** [comment]
removing blocking-clean-ci as it has not failed in 30 days

24-Hour Hit Count	7-Day Hit Count	1-Month Count
0	0	0

**Comment by lewing** [comment]
It is actually fixed I just kept it open initially to keep ci green and forgot to revisit.  We should have tooling to manage this better
