### PR TITLE
Fix build breaks

### PR DESCRIPTION
**Pull request by MichalStrehovsky**
Fixes build breaks on less mainstream platforms caused by #111771.

Samples:

Windows x86:

```
Runtime.WorkstationGC.lib(EHHelpers.cpp.obj)(0,0): error LNK2001: unresolved external symbol _RhpVTableOffsetDispatchAVLocation [D:\a\_work\1\s\src\tests\baseservices\compilerservices\FixedAddressValueType\FixedAddressValueType.csproj]
```

Riscv:

```
ld.lld : error : undefined symbol: RhpVTableOffsetDispatchAVLocation [/runtime/src/tests/nativeaot/GenerateUnmanagedEntryPoints/GenerateUnmanagedEntryPoints.csproj] [/runtime/src/tests/build.proj]
```

### CODE REVIEW

**Review by davidwrighton — APPROVED** [review]

**Review by am11 — APPROVED** [review]
Thank you. riscv64 test build gets fixed with this PR.
