### ISSUE TITLE
superpmi.py list-collections fail with 'CoreclrArguments' object has no attribute 'target_os'

### ISSUE THREAD

**Issue by echesakovMSFT** [dotnet/runtime#45981]
Started failing after #45605 

```
F:\echesako\git\runtime2>python src\coreclr\scripts\superpmi.py list-collections
Warning: deleting existing log file F:\echesako\git\runtime2\artifacts\spmi\superpmi.log
================ Logging to F:\echesako\git\runtime2\artifacts\spmi\superpmi.log
Using JIT/EE Version from jiteeversionguid.h: 790de1e5-1426-4ecf-939c-2cd60445c219
Traceback (most recent call last):
  File "F:\echesako\git\runtime2\src\coreclr\scripts\superpmi.py", line 3259, in <module>
    sys.exit(main(args))
  File "F:\echesako\git\runtime2\src\coreclr\scripts\superpmi.py", line 3242, in main
    list_collections_command(coreclr_args)
  File "F:\echesako\git\runtime2\src\coreclr\scripts\superpmi.py", line 2279, in list_collections_command
    blob_filter_string = "{}/{}/{}/".format(coreclr_args.jit_ee_version, coreclr_args.target_os, coreclr_args.mch_arch)
AttributeError: 'CoreclrArguments' object has no attribute 'target_os'
```

cc @BruceForstall
