### ISSUE TITLE
Runtime tests fail to AOT compile on Apple mobile platforms

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/runtime#103982]
## Build Information
Build: https://dev.azure.com/dnceng-public/public/_build/results?buildId=719424
Build error leg or test failing: https://dev.azure.com/dnceng-public/public/_build/results?buildId=719424&view=logs&j=da83f4c3-af55-5024-34f6-3ac8d11ac15f

## Error Message

Fill the error message using [step by step known issues guidance](https://github.com/dotnet/arcade/blob/main/Documentation/Projects/Build%20Analysis/KnownIssueJsonStepByStep.md).

```json
{
  "ErrorMessage": "duplicate symbol '_dn_simdhash_ptrpair_ptr_meta'",
  "BuildRetry": false,
  "ExcludeConsoleLog": false
}
```

```
...
[/private/tmp/helix/working/95610881/w/A2B908C5/e/publish/ProxyProjectForAOTOnHelix.proj]
/tmp/helix/working/95610881/p/build/apple/AppleBuild.targets(296,5): error MSB4018: duplicate symbol '_dn_simdhash_ptrpair_ptr_vtable' in: [/private/tmp/helix/working/95610881/w/A2B908C5/e/publish/ProxyProjectForAOTOnHelix.proj]
/tmp/helix/working/95610881/p/build/apple/AppleBuild.targets(296,5): error MSB4018:     /tmp/helix/working/95610881/w/A2B908C5/e/publish/libmono-component-diagnostics_tracing-static.a(dn-simdhash-ptrpair-ptr.c.o) [/private/tmp/helix/working/95610881/w/A2B908C5/e/publish/ProxyProjectForAOTOnHelix.proj]
/tmp/helix/working/95610881/p/build/apple/AppleBuild.targets(296,5): error MSB4018:     /tmp/helix/working/95610881/w/A2B908C5/e/publish/libmonosgen-2.0.a(dn-simdhash-ptrpair-ptr.c.o) [/private/tmp/helix/working/95610881/w/A2B908C5/e/publish/ProxyProjectForAOTOnHelix.proj]
/tmp/helix/working/95610881/p/build/apple/AppleBuild.targets(296,5): error MSB4018: duplicate symbol '_dn_simdhash_ptrpair_ptr_try_add' in: [/private/tmp/helix/working/95610881/w/A2B908C5/e/publish/ProxyProjectForAOTOnHelix.proj]
/tmp/helix/working/95610881/p/build/apple/AppleBuild.targets(296,5): error MSB4018:     /tmp/helix/working/95610881/w/A2B908C5/e/publish/libmono-component-diagnostics_tracing-static.a(dn-simdhash-ptrpair-ptr.c.o) [/private/tmp/helix/working/95610881/w/A2B908C5/e/publish/ProxyProjectForAOTOnHelix.proj]
/tmp/helix/working/95610881/p/build/apple/AppleBuild.targets(296,5): error MSB4018:     /tmp/helix/working/95610881/w/A2B908C5/e/publish/libmonosgen-2.0.a(dn-simdhash-ptrpair-ptr.c.o) [/private/tmp/helix/working/95610881/w/A2B908C5/e/publish/ProxyProjectForAOTOnHelix.proj]
/tmp/helix/working/95610881/p/build/apple/AppleBuild.targets(296,5): error MSB4018: duplicate symbol '_dn_simdhash_ptrpair_ptr_meta' in: [/private/tmp/helix/working/95610881/w/A2B908C5/e/publish/ProxyProjectForAOTOnHelix.proj]
/tmp/helix/working/95610881/p/build/apple/AppleBuild.targets(296,5): error MSB4018:     /tmp/helix/working/95610881/w/A2B908C5/e/publish/libmono-component-diagnostics_tracing-static.a(dn-simdhash-ptrpair-ptr.c.o) [/private/tmp/helix/working/95610881/w/A2B908C5/e/publish/ProxyProjectForAOTOnHelix.proj]
/tmp/helix/working/95610881/p/build/apple/AppleBuild.targets(296,5): error MSB4018:     /tmp/helix/working/95610881/w/A2B908C5/e/publish/libmonosgen-2.0.a(dn-simdhash-ptrpair-ptr.c.o) [/private/tmp/helix/working/95610881/w/A2B908C5/e/publish/ProxyProjectForAOTOnHelix.proj]
/tmp/helix/working/95610881/p/build/apple/AppleBuild.targets(296,5): error MSB4018: ld: 156 duplicate symbols for architecture arm64 [/private/tmp/helix/working/95610881/w/A2B908C5/e/publish/ProxyProjectForAOTOnHelix.proj]
```

The regression is likely introduced in https://github.com/dotnet/runtime/pull/103184.

/cc: @jkoritzinsky 

 ### Known issue validation
**Build: :mag_right:** https://dev.azure.com/dnceng-public/public/_build/results?buildId=719424
**Error message validated:** `[duplicate symbol '_dn_simdhash_ptrpair_ptr_meta'`]
**Result validation:** :white_check_mark: Known issue matched with the provided build.
**Validation performed at:** 6/25/2024 6:36:10 PM UTC

### Report

|Build|Definition|Test|Pull Request|
|---|---|---|---|
|[722476](https://dev.azure.com/dnceng-public/public/_build/results?buildId=722476)|dotnet/runtime|[baseservices_TieredCompilation.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=722476&view=ms.vss-test-web.build-test-results-tab&runId=18129490&resultId=100013)||
|[721722](https://dev.azure.com/dnceng-public/public/_build/results?buildId=721722)|dotnet/runtime|[baseservices_TieredCompilation.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=721722&view=ms.vss-test-web.build-test-results-tab&runId=18107258&resultId=100012)||
|[720898](https://dev.azure.com/dnceng-public/public/_build/results?buildId=720898)|dotnet/runtime|[baseservices_TieredCompilation.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=720898&view=ms.vss-test-web.build-test-results-tab&runId=18081448&resultId=100013)||
|[720816](https://dev.azure.com/dnceng-public/public/_build/results?buildId=720816)|dotnet/runtime|[baseservices_TieredCompilation.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=720816&view=ms.vss-test-web.build-test-results-tab&runId=18078286&resultId=100013)||
|[719424](https://dev.azure.com/dnceng-public/public/_build/results?buildId=719424)|dotnet/runtime|[baseservices_TieredCompilation.WorkItemExecution](https://dev.azure.com/dnceng-public/public/_build/results?buildId=719424&view=ms.vss-test-web.build-test-results-tab&runId=18033732&resultId=100013)||
#### Summary
|24-Hour Hit Count|7-Day Hit Count|1-Month Count|
|---|---|---|
|0|5|5|

**Comment by matouskozak** [comment]
Is this failure related to ```

        _ep_file_alloc in unity_0_c.c.o
        _ds_ipc_poll in unity_0_c.c.o
        _ds_ipc_connect in unity_0_c.c.o
        _ipc_stream_read_func in unity_0_c.c.o
        _ipc_stream_write_func in unity_0_c.c.o
    "_ep_rt_mono_provider_config_init", referenced from:
        _ep_provider_config_init in unity_0_c.c.o
        _ep_enable_2 in unity_0_c.c.o
        _disable_helper in unity_0_c.c.o
        _ep_session_enable_rundown in unity_0_c.c.o
        _eventpipe_collect_tracing_command_try_parse_config in unity_0_c.c.o
    "_ep_rt_mono_rand_try_get_bytes", referenced from:
        _ds_ipc_advertise_cookie_v1_init in unity_0_c.c.o
        _ds_server_init in unity_0_c.c.o
    "_ep_rt_mono_sample_profiler_write_sampling_event_for_threads", referenced from:
        _sampling_thread in unity_0_c.c.o
    "_ep_rt_mono_system_time_get", referenced from:
        _ep_file_alloc in unity_0_c.c.o
    "_ep_rt_mono_system_timestamp_get", referenced from:
        _ep_session_alloc in unity_0_c.c.o
    "_ep_rt_mono_thread_attach", referenced from:
        _disable_helper in unity_0_c.c.o
    "_ep_rt_mono_thread_attach_2", referenced from:
        _ep_rt_thread_mono_start_func in unity_0_c.c.o
    "_ep_rt_mono_thread_detach", referenced from:
        _ep_rt_thread_mono_start_func in unity_0_c.c.o
    "_ep_rt_mono_thread_get_or_create", referenced from:
        _disable_helper in unity_0_c.c.o
        _ep_write_event in unity_0_c.c.o
        _ep_write_event_2 in unity_0_c.c.o
        _write_event_2 in unity_0_c.c.o
        _ep_thread_get_or_create in unity_0_c.c.o
    "_ep_rt_mono_walk_managed_stack_for_thread", referenced from:
        _ep_buffer_manager_write_event in unity_0_c.c.o
    "_mono_component_debugger_init", referenced from:
        _components in components.c.o
    "_mono_component_diagnostics_server_init", referenced from:
        _components in components.c.o
    "_mono_component_event_pipe_init", referenced from:
        _components in components.c.o
    "_mono_component_hot_reload_init", referenced from:
        _components in components.c.o
    "_mono_component_marshal_ilgen_init", referenced from:
        _components in components.c.o
  ld: symbol(s) not found for architecture x86_64
``` occuring on x64 ios/tvos simulators (e.g. https://dev.azure.com/dnceng-public/public/_build/results?buildId=722192&view=logs&jobId=07effcfd-c63d-5008-e811-03b29530f5cb&j=cd385208-11d3-5d70-fa38-1c21a65d17f1&t=0fb08637-f78f-568d-a095-c4f3c07eba27)?

**Comment by kotlarmilos** [comment]
It should be related.
