### PR TITLE
Re-enable CoreLib analyzers

### LINKED ISSUE #422: Re-enable analyzers for System.Private.CoreLib
Disabled by #338 for some reason. See https://github.com/dotnet/runtime/pull/338/files#r352355176

### PR DESCRIPTION
**Pull request by ViktorHofer**
CoreLib analyzers were unintentionally disabled with
6afe96cc2e950379d13a87efa1fa5a651cbce9bd. This re-enables the analyzers
and conditions one which brings in external dependencies that CoreLib
can't deal with.

Fixes https://github.com/dotnet/runtime/issues/422

### CODE REVIEW

File: eng/Analyzers.props [hunk 1]
```diff
@@ -3,9 +3,10 @@
     <CodeAnalysisRuleset>$(MSBuildThisFileDirectory)CodeAnalysis.ruleset</CodeAnalysisRuleset>
   </PropertyGroup>
   <ItemGroup Condition="'$(EnableAnalyzers)' == 'true'">
-    <PackageReference Include="Microsoft.DotNet.CodeAnalysis" Version="$(MicrosoftDotNetCodeAnalysisVersion)" />
-    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="3.4.0-beta2-final" />
-    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.9.6" />
-    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.66" />
+    <PackageReference Include="Microsoft.DotNet.CodeAnalysis" Version="$(MicrosoftDotNetCodeAnalysisVersion)" PrivateAssets="all" IsImplicitlyDefined="true" />
+    <!-- Microsoft.CodeAnalysis.Common brings in external dependencies that CoreLib can't deal with. -->
```
Comment (stephentoub) [inline eng/Analyzers.props]: How does "can't deal with" manifest?

Comment (ViktorHofer) [reply eng/Analyzers.props]: Thousands of the following errors:

```
C:\git\runtime\src\libraries\System.Private.CoreLib\src\System\Runtime\MemoryFailPoint.cs(368,128): error CS0518: Predefined type 'System.Boolean' is not defined or imported [C:\git\runtime\src\coreclr\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
C:\git\runtime\src\libraries\System.Private.CoreLib\src\System\Runtime\MemoryFailPoint.cs(368,156): error CS0518: Predefined type 'System.UInt64' is not defined or imported [C:\git\runtime\src\coreclr\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
C:\git\runtime\src\libraries\System.Private.CoreLib\src\System\Runtime\MemoryFailPoint.cs(368,177): error CS0518: Predefined type 'System.UInt64' is not defined or imported [C:\git\runtime\src\coreclr\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
C:\git\runtime\src\libraries\System.Private.CoreLib\src\System\Runtime\MemoryFailPoint.cs(368,206): error CS0518: Predefined type 'System.Int64' is not defined or imported [C:\git\runtime\src\coreclr\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
C:\git\runtime\src\libraries\System.Private.CoreLib\src\System\Runtime\MemoryFailPoint.cs(368,238): error CS0518: Predefined type 'System.UInt64' is not defined or imported [C:\git\runtime\src\coreclr\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
C:\git\runtime\src\libraries\System.Private.CoreLib\src\System\Runtime\MemoryFailPoint.cs(368,13): error CS0518: Predefined type 'System.Void' is not defined or imported [C:\git\runtime\src\coreclr\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
src\System\RuntimeArgumentHandle.cs(15,23): error CS0518: Predefined type 'System.ValueType' is not defined or imported [C:\git\runtime\src\coreclr\src\System.Private.CoreLib\System.Private.CoreLib.csproj]
```

AFAIK CoreLib mustn't have any references. That packages brings some in. I'm right now experimenting with adding a netstandard2.1 configuration to `Microsoft.CodeAnalysis.csproj`.

Comment (jkotas) [inline eng/Analyzers.props]: What is the `Microsoft.CodeAnalysis.Common` package for? What is not going to work if we remove from here?

Comment (ViktorHofer) [reply eng/Analyzers.props]: That package was first introduced with https://github.com/dotnet/corefx/commit/87873f55d4d0d4f2b073e544f1295761976beca8#diff-c9ed7fc6ec49880569e6c2eb08120fc4R27. I'm not exactly sure, its description even says it shouldn't be referenced directly. I'll take a closer look.

Comment (jkotas) [reply eng/Analyzers.props]: The analyzer dependencies are not supposed to end up as `/r:` references for the compiler. This means that either this package is not authored correctly; or it is not used correctly.

**Comment by ViktorHofer** [comment]
I'll remove that package as its description clearly state that it shouldn't be referenced directly. @safern do you have context why that package was referenced directly in corefx/arcade?

**Comment by ViktorHofer** [comment]
OK, so the transitive dependency to Microsoft.CodeAnalysis.Common is required becaues of the special way we add analyzers to projects in libraries. We will clean this up with @Anipik's work to enable project restore for non test projects in libraries.

File: eng/Analyzers.props (hunk 1 above)
Comment (ViktorHofer) [reply eng/Analyzers.props]: > or it is not used correctly.

It shouldn't be referenced directly. The entry was added because libraries inject the analyzers into the csc task in a special way (no project restore). This should now be resolved.

File: src/libraries/restore/analyzers/analyzers.depproj [hunk 2]
```diff
@@ -5,6 +5,14 @@
     <Language>C#</Language>
   </PropertyGroup>
 
+  <ItemGroup>
+    <!-- 
+      Microsoft.CodeAnalysis.Common shouldn't be referenced directly but is needed by the analyzer depproj restore.
+      TODO: Remove when project restore is enabled for non test projects.
```
Comment (jkotas) [inline src/libraries/restore/analyzers/analyzers.depproj]: Add link to the issue that tracks this work?

File: eng/Analyzers.props [hunk 3]
```diff
@@ -3,9 +3,8 @@
     <CodeAnalysisRuleset>$(MSBuildThisFileDirectory)CodeAnalysis.ruleset</CodeAnalysisRuleset>
   </PropertyGroup>
   <ItemGroup Condition="'$(EnableAnalyzers)' == 'true'">
-    <PackageReference Include="Microsoft.DotNet.CodeAnalysis" Version="$(MicrosoftDotNetCodeAnalysisVersion)" />
-    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="3.4.0-beta2-final" />
-    <PackageReference Include="Microsoft.CodeAnalysis.FxCopAnalyzers" Version="2.9.6" />
-    <PackageReference Include="StyleCop.Analyzers" Version="1.2.0-beta.66" />
+    <PackageReference Include="Microsoft.DotNet.CodeAnalysis" Version="$(MicrosoftDotNetCodeAnalysisVersion)" PrivateAssets="all" IsImplicitlyDefined="true" />
```
Comment (jkotas) [inline eng/Analyzers.props]: Why this one needs `IsImplicitlyDefined="true"`, but the other two don't?

Comment (ViktorHofer) [reply eng/Analyzers.props]: Because that package is part of the dependency flow and shouldn't be updatable via the nuget package manager api. The other two are not part of the dependency flow.

File: src/libraries/restore/analyzers/analyzers.depproj (hunk 2 above)
Comment (ViktorHofer) [reply src/libraries/restore/analyzers/analyzers.depproj]: done.

**Comment by ViktorHofer** [comment]
This should be ready, can someone pls approve? Thanks

**Review by stephentoub — APPROVED** [review]

**Comment by ViktorHofer** [comment]
Thanks, merging as the previous run was green (except an unrelated test failure) and I just changed a comment which re-triggered CI.

**Review by safern — COMMENTED** [review]
LGTM
