### ISSUE TITLE
Test failure: readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd

### ISSUE THREAD

**Issue by v-wenyuxu** [dotnet/runtime#106948]
**Failed in:** [runtime-coreclr outerloop 20240825.2](https://dev.azure.com/dnceng-public/public/_build/results?buildId=787850&view=ms.vss-test-web.build-test-results-tab&runId=20240270&resultId=104817&paneView=debug)

**Failed tests:**
```
coreclr linux arm Checked @ (Alpine.316.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.17-helix-arm32v7
    - readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd
```

**Error message:**
```
 1 / 1 (100%, 1 failed): failed in 257 msecs, exit code 134, expected 0: crossgen2 @/root/helix/work/workitem/e/readytorun/coreroot_determinism/coreroot_determinism/seed1/CPAOT-ret.out/System.Private.CoreLib.dll.rsp
!! Assert failure(PID 59 [0x0000003b], Thread: 59 [0x003b]): Consistency check failed: Crst Level violation: Can't take level 6 lock CrstUnresolvedClassLock because you already holding level 0 lock CrstNativeImageEagerFixups
!! FAILED: false
!!     File: /__w/1/s/src/coreclr/vm/crst.cpp:765
!!     Image: /root/helix/work/correlation/crossgen2/crossgen2
!! [createdump] The app model does not support crash report generation
!! [createdump] Failure took 0ms
!! waitpid() returned successfully (wstatus 00000086) WEXITSTATUS 0 WTERMSIG 6
  [createdump] Target process is alive

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/coreroot_determinism/output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true coreroot_determinism.dll ''
================================== Compiling with seed 1 ==================================
Locating output folder /root/helix/work/workitem/e/readytorun/coreroot_determinism/coreroot_determinism/seed1
Deleting 0 output folders
Successfully deleted 0 output folders in 143 msecs
1 / 1 (0%, 0 failed): launching: /root/helix/work/correlation/crossgen2/crossgen2 @/root/helix/work/workitem/e/readytorun/coreroot_determinism/coreroot_determinism/seed1/CPAOT-ret.out/System.Private.CoreLib.dll.rsp
Compilation failed. /root/helix/work/correlation/corerun /root/helix/work/correlation/R2RTest/R2RTest.dll compile-directory -cr /root/helix/work/correlation -in TestAssemblies --nojit --noexe --large-bubble --release --nocleanup -ct 30 -out seed1 failed with exit code 1
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 100
Actual:   1
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 168
   at Xunit.Assert.Equal[T](T expected, T actual) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 90
   at __GeneratedMainWrapper.Main()
Expected: 100
Actual: 101
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 8/25/2024 7:41:29 PM
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> /root/helix/work/workitem/e/readytorun/coreroot_determinism/readytorun_coreroot_determinism/../coreroot_determinism/coreroot_determinism.sh
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor1|0_2(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by jkotas** [comment]
Introduced by #80154?

cc @am11 @jakobbotsch

**Comment by jkotas** [comment]
Note that the two failures mentioned in this issue are unrelated. The failure mode is very different for each of them.

>  man: 0x4c, unman: 0x48, Name: System.Diagnostics.StackFrameHelper

@agocke This was likely introduced by #108693. This failure is caused by running live System.Private.CoreLib.dll with LKG runtime. PTLA

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr outerloop 20241010.4](https://dev.azure.com/dnceng-public/public/_build/results?buildId=838675&view=ms.vss-test-web.build-test-results-tab&runId=21726904&resultId=104631&paneView=debug)

**Failed tests:**
```
coreclr linux arm Checked @ (Alpine.316.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.17-helix-arm32v7
    - readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd
```

**Error message:**
```
 1 / 1 (100%, 1 failed): failed in 233 msecs, exit code 134, expected 0: crossgen2 @/root/helix/work/workitem/e/readytorun/coreroot_determinism/coreroot_determinism/seed1/CPAOT-ret.out/System.Private.CoreLib.dll.rsp
  [createdump] Target process is alive
Process terminated. Assertion failed.
currentBlock.m_ChunkLength <= currentBlock.m_ChunkChars.Length
   at System.Text.StringBuilder.AssertInvariants()
   at System.Text.StringBuilder.AppendWithExpansion(Char& value, Int32 valueCount)
   at System.Text.StringBuilder.Append(String value)
   at System.Text.StringBuilder.AppendLine(String value)
   at ProcessRunner.StandardErrorEventHandler(Object sender, DataReceivedEventArgs eventArgs) in /_/src/coreclr/tools/r2rtest/ProcessRunner.cs:line 297
   at System.Diagnostics.Process.ErrorReadNotifyUser(String data) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 1731
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/AsyncStreamReader.cs:line 237
   at System.Diagnostics.AsyncStreamReader.ReadBufferAsync() in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/AsyncStreamReader.cs:line 123
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/coreroot_determinism/output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true coreroot_determinism.dll ''
================================== Compiling with seed 1 ==================================
Locating output folder /root/helix/work/workitem/e/readytorun/coreroot_determinism/coreroot_determinism/seed1
Deleting 0 output folders
Successfully deleted 0 output folders in 144 msecs
1 / 1 (0%, 0 failed): launching: /root/helix/work/correlation/crossgen2/crossgen2 @/root/helix/work/workitem/e/readytorun/coreroot_determinism/coreroot_determinism/seed1/CPAOT-ret.out/System.Private.CoreLib.dll.rsp
[createdump] Gathering state for process 41 corerun
[createdump] Crashing thread 0039 signal 6 (0006)
[createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/coredump.41.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.41.dmp
[createdump] Written 75431936 bytes (18416 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 204ms
Compilation failed. /root/helix/work/correlation/corerun /root/helix/work/correlation/R2RTest/R2RTest.dll compile-directory -cr /root/helix/work/correlation -in TestAssemblies --nojit --noexe --large-bubble --release --nocleanup -ct 30 -out seed1 failed with exit code 134
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 100
Actual:   1
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 168
   at Xunit.Assert.Equal[T](T expected, T actual) in /_/src/Microsoft.DotNet.XUnitAssert/src/
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor1|0_2(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr outerloop 20241011.6](https://dev.azure.com/dnceng-public/public/_build/results?buildId=840543&view=ms.vss-test-web.build-test-results-tab&runId=21789528&resultId=102435&paneView=debug)

**Failed tests:**
```
coreclr linux arm Checked @ (Alpine.316.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.17-helix-arm32v7
    - readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd
```

**Error message:**
```
 1 / 1 (100%, 1 failed): failed in 228 msecs, exit code 134, expected 0: crossgen2 @/root/helix/work/workitem/e/readytorun/coreroot_determinism/coreroot_determinism/seed1/CPAOT-ret.out/System.Private.CoreLib.dll.rsp
!! Assert failure(PID 59 [0x0000003b], Thread: 59 [0x003b]): Consistency check failed: Managed object size does not match unmanaged object size
!! man: 0x4c, unman: 0x48, Name: System.Diagnostics.StackFrameHelper
!! FAILED: size == expectedsize
!!     File: /__w/1/s/src/coreclr/vm/binder.cpp:647
!!     Image: /root/helix/work/correlation/crossgen2/crossgen2
!! [createdump] The app model does not support crash report generation
!! [createdump] Failure took 0ms
!! waitpid() returned successfully (wstatus 00000086) WEXITSTATUS 0 WTERMSIG 6
  [createdump] Target process is alive

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/coreroot_determinism/output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true coreroot_determinism.dll ''
================================== Compiling with seed 1 ==================================
Locating output folder /root/helix/work/workitem/e/readytorun/coreroot_determinism/coreroot_determinism/seed1
Deleting 0 output folders
Successfully deleted 0 output folders in 197 msecs
1 / 1 (0%, 0 failed): launching: /root/helix/work/correlation/crossgen2/crossgen2 @/root/helix/work/workitem/e/readytorun/coreroot_determinism/coreroot_determinism/seed1/CPAOT-ret.out/System.Private.CoreLib.dll.rsp
Compilation failed. /root/helix/work/correlation/corerun /root/helix/work/correlation/R2RTest/R2RTest.dll compile-directory -cr /root/helix/work/correlation -in TestAssemblies --nojit --noexe --large-bubble --release --nocleanup -ct 30 -out seed1 failed with exit code 1
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 100
Actual:   1
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 168
   at Xunit.Assert.Equal[T](T expected, T actual) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 90
   at __GeneratedMainWrapper.Main()
Expected: 100
Actual: 101
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 10/12/2024 2:52:35 AM
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> /root/helix/work/workitem/e/readytorun/coreroot_determinism/readytorun_coreroot_determinism/../coreroot_determinism/coreroot_determinism.sh
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor1|0_2(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr outerloop 20241013.3](https://dev.azure.com/dnceng-public/public/_build/results?buildId=841261&view=ms.vss-test-web.build-test-results-tab&runId=21812360&resultId=106236&paneView=debug)

**Failed tests:**
```
coreclr linux arm Checked @ (Alpine.316.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.17-helix-arm32v7
    - readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd
```

**Error message:**
```
 1 / 1 (100%, 1 failed): failed in 240 msecs, exit code 134, expected 0: crossgen2 @/root/helix/work/workitem/e/readytorun/coreroot_determinism/coreroot_determinism/seed1/CPAOT-ret.out/System.Private.CoreLib.dll.rsp
!! Assert failur  [createdump] Target process is alive
Process terminated. Assertion failed.
currentBlock.m_ChunkLength <= currentBlock.m_ChunkChars.Length
   at System.Text.StringBuilder.AssertInvariants()
   at System.Text.StringBuilder.AppendWithExpansion(Char& value, Int32 valueCount)
   at System.Text.StringBuilder.Append(String value)
   at System.Text.StringBuilder.AppendLine(String value)
   at ProcessRunner.StandardErrorEventHandler(Object sender, DataReceivedEventArgs eventArgs) in /_/src/coreclr/tools/r2rtest/ProcessRunner.cs:line 297
   at System.Diagnostics.Process.ErrorReadNotifyUser(String data) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 1731
   at System.Diagnostics.AsyncStreamReader.FlushMessageQueue(Boolean rethrowInNewThread) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/AsyncStreamReader.cs:line 237
   at System.Diagnostics.AsyncStreamReader.ReadBufferAsync() in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/AsyncStreamReader.cs:line 123
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecuteFromThreadPool(Thread threadPoolThread)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
waitpid() returned successfully (wstatus 00000000) WEXITSTATUS 0 WTERMSIG 0

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/coreroot_determinism/output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true coreroot_determinism.dll ''
================================== Compiling with seed 1 ==================================
Locating output folder /root/helix/work/workitem/e/readytorun/coreroot_determinism/coreroot_determinism/seed1
Deleting 0 output folders
Successfully deleted 0 output folders in 136 msecs
1 / 1 (0%, 0 failed): launching: /root/helix/work/correlation/crossgen2/crossgen2 @/root/helix/work/workitem/e/readytorun/coreroot_determinism/coreroot_determinism/seed1/CPAOT-ret.out/System.Private.CoreLib.dll.rsp
[createdump] Gathering state for process 41 corerun
[createdump] Crashing thread 0039 signal 6 (0006)
[createdump] Writing crash report to file /home/helixbot/dotnetbuild/dumps/coredump.41.dmp.crashreport.json
[createdump] Crash report successfully written
[createdump] Writing minidump with heap to file /home/helixbot/dotnetbuild/dumps/coredump.41.dmp
[createdump] Written 75149312 bytes (18347 pages) to core file
[createdump] Target process is alive
[createdump] Dump successfully written in 171ms
Compilation failed. /root/helix/work/correlation/corerun /root/helix/work/correlation/R2RTest/R2RTest.dll compile-directory -cr /root/helix/work/correlation -in TestAssemblies --nojit --noexe --large-bubble --release --nocleanup -ct 30 -out seed1 failed with exit code 134
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 100
Actual:   1
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 168
   at Xunit.Assert.Equal[T](T expected, T actual) in /_/src/Microsoft.DotNet.
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor1|0_2(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```

**Comment by v-wenyuxu** [comment]
**Failed in:** [runtime-coreclr outerloop 20241014.6](https://dev.azure.com/dnceng-public/public/_build/results?buildId=842144&view=ms.vss-test-web.build-test-results-tab&runId=21840388&resultId=108392&paneView=debug)

**Failed tests:**
```
coreclr linux arm Checked @ (Alpine.316.Arm32.Open)Ubuntu.2004.ArmArch.Open@mcr.microsoft.com/dotnet-buildtools/prereqs:alpine-3.17-helix-arm32v7
    - readytorun/coreroot_determinism/coreroot_determinism/coreroot_determinism.cmd
```

**Error message:**
```
 1 / 1 (100%, 1 failed): failed in 242 msecs, exit code 134, expected 0: crossgen2 @/root/helix/work/workitem/e/readytorun/coreroot_determinism/coreroot_determinism/seed1/CPAOT-ret.out/System.Private.CoreLib.dll.rsp
!! Assert failure(PID 61 [0x0000003d], Thread: 61 [0x003d]): Consistency check failed: Managed object size does not match unmanaged object size
!! man: 0x4c, unman: 0x48, Name: System.Diagnostics.StackFrameHelper
!! FAILED: size == expectedsize
!!     File: /__w/1/s/src/coreclr/vm/binder.cpp:647
!!     Image: /root/helix/work/correlation/crossgen2/crossgen2
!! [createdump] The app model does not support crash report generation
!! [createdump] Failure took 0ms
!! waitpid() returned successfully (wstatus 00000086) WEXITSTATUS 0 WTERMSIG 6
  [createdump] Target process is alive

Return code:      1
Raw output file:      /root/helix/work/workitem/uploads/coreroot_determinism/output.txt
Raw output:
BEGIN EXECUTION
/root/helix/work/correlation/corerun -p System.Reflection.Metadata.MetadataUpdater.IsSupported=false -p System.Runtime.Serialization.EnableUnsafeBinaryFormatterSerialization=true coreroot_determinism.dll ''
================================== Compiling with seed 1 ==================================
Locating output folder /root/helix/work/workitem/e/readytorun/coreroot_determinism/coreroot_determinism/seed1
Deleting 0 output folders
Successfully deleted 0 output folders in 190 msecs
1 / 1 (0%, 0 failed): launching: /root/helix/work/correlation/crossgen2/crossgen2 @/root/helix/work/workitem/e/readytorun/coreroot_determinism/coreroot_determinism/seed1/CPAOT-ret.out/System.Private.CoreLib.dll.rsp
Compilation failed. /root/helix/work/correlation/corerun /root/helix/work/correlation/R2RTest/R2RTest.dll compile-directory -cr /root/helix/work/correlation -in TestAssemblies --nojit --noexe --large-bubble --release --nocleanup -ct 30 -out seed1 failed with exit code 1
Xunit.Sdk.EqualException: Assert.Equal() Failure: Values differ
Expected: 100
Actual:   1
   at Xunit.Assert.Equal[T](T expected, T actual, IEqualityComparer`1 comparer) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 168
   at Xunit.Assert.Equal[T](T expected, T actual) in /_/src/Microsoft.DotNet.XUnitAssert/src/EqualityAsserts.cs:line 90
   at __GeneratedMainWrapper.Main()
Expected: 100
Actual: 101
END EXECUTION - FAILED
Test failed. Trying to see if dump file was created in /home/helixbot/dotnetbuild/dumps since 10/14/2024 7:48:05 PM
Test Harness Exitcode is : 1
To run the test:
Set up CORE_ROOT and run.
> /root/helix/work/workitem/e/readytorun/coreroot_determinism/readytorun_coreroot_determinism/../coreroot_determinism/coreroot_determinism.sh
```

**Stack trace:**
```
   at Xunit.Assert.True(Nullable`1 condition, String userMessage) in /_/src/Microsoft.DotNet.XUnitAssert/src/BooleanAsserts.cs:line 146
   at TestLibrary.OutOfProcessTest.RunOutOfProcessTest(String assemblyPath, String testPathPrefix)
   at Program.<<Main>$>g__TestExecutor1|0_2(StreamWriter tempLogSw, StreamWriter statsCsvSw, <>c__DisplayClass0_0&)
```
