### PR TITLE
fix the build

### LINKED ISSUE #62574: Libraries build fail
Failed after https://github.com/dotnet/runtime/pull/62507

```sh
./build.sh --arch x64 --runtimeConfiguration Release --librariesConfiguration Release --subset clr+libs
```
output:
```
Build FAILED.

CSC : error CS2001: Source file '/home/z/Dev/runtime/src/libraries/Common/src/Interop/Interop.ZLib.cs' could not be found. [/home/z/Dev/runtime/src/libraries/System.IO.Compression/src/System.IO.Compression.csproj]
CSC : error CS2001: Source file '/home/z/Dev/runtime/src/libraries/Common/src/Interop/Interop.ZLib.cs' could not be found. [/home/z/Dev/runtime/src/libraries/System.Net.WebSockets/src/System.Net.WebSockets.csproj]
    0 Warning(s)
    2 Error(s)
```

Simple rename `src/libraries/Common/src/Interop/Interop.zlib.cs` -> `src/libraries/Common/src/Interop/Interop.ZLib.cs` needed?

### PR DESCRIPTION
**Pull request by adamsitnik**
fixes #62574, see #62574 for context

I've verified that it fixes the problem locally.

### CODE REVIEW

**Comment by adamsitnik** [comment]
@EgorBo @krwq @eiriktsarpalis I've asked you for review because you are also located in Europe and there is a chance that we could fix the CI before folks from Redmond wake up

**Review by stephentoub — APPROVED** [review]

**Review by EgorBo — APPROVED** [review]

**Comment by stephentoub** [comment]
Thanks for fixing it.

**Comment by akoeplinger** [comment]
Thanks. Do you know why it failed? The source file on disk does have the lower-cased name. Is it because of the source-genrator for `GeneratedDllImport`? I wonder if we should correct the casing for the Interop.zlib.cs file itself too.

**Comment by adamsitnik** [comment]
> Do you know why it failed?

#62507 has introduced a bug and it was merged despite the fact that CI legs have failed:

image

**Comment by akoeplinger** [comment]
Yeah but I'm a little confused _why_ it failed since the file on disk is `Interop.zlib.cs` like it was in the .csproj, so I assume the problem is related to the source generator somehow now that the type name is pascal cased?

**Comment by akoeplinger** [comment]
Maybe @jcouv can shed some light on how this works.

**Comment by adamsitnik** [comment]
@akoeplinger I would expect that it's because file paths are just case-sensitive on Linux?

**Review by safern — COMMENTED** [review]
LGTM

**Comment by jcouv** [comment]
Thanks for fixing this. Sorry about that. I'd done the rename of the file, but seems like git didn't persist that.
