### PR TITLE
Clean-up `Microsoft.Win32.Registry` and remove the non-Windows code.

### LINKED ISSUE #77974: Simplify Microsoft.Win32.Registry sources split
Microsoft.Win32.Registry is Windows only library but contains types that are implemented in multiple source files (e.g. RegistryKey.cs and RegistryKey.Windows.cs). Such files can be folded into single file for easier navigation and maintenance.

### PR DESCRIPTION
**Pull request by teo-tsirpanis**
In a similar vein with other Windows-exclusive libraries, this PR makes the sources of `Microsoft.Win32.Registry` compile only on Windows, removes the non-Windows files (they just threw PNSE), merges the `.Windows` source files and cleans-up some stuff.

Fixes #77974

### CODE REVIEW

**Comment by stephentoub** [comment]
@marek-safar, how close are you to merging #72667?  This is going to conflict.

File: src/libraries/Microsoft.Win32.Registry/src/Microsoft.Win32.Registry.csproj [hunk 1]
```diff
@@ -8,34 +8,17 @@
   <!-- DesignTimeBuild requires all the TargetFramework Derived Properties to not be present in the first property group. -->
   <PropertyGroup>
     <TargetPlatformIdentifier>$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)'))</TargetPlatformIdentifier>
-    <!-- Avoid unused fields warnings in Unix build -->
-    <NoWarn Condition="'$(TargetPlatformIdentifier)' != 'windows'">$(NoWarn);CA1823</NoWarn>
+    <GeneratePlatformNotSupportedAssemblyMessage Condition="'$(TargetPlatformIdentifier)' != 'windows'">SR.PlatformNotSupported_Registry</GeneratePlatformNotSupportedAssemblyMessage>
```
Comment (ViktorHofer) [inline src/libraries/Microsoft.Win32.Registry/src/Microsoft.Win32.Registry.csproj:11]: Do we know why the `$(NetCoreAppCurrent)` target framework wasn't a PNSE throwing assembly? Looks to me that this assembly actually worked on Unix before (even though it doesn't make sense, because of the Win32 dependency).

Comment (ViktorHofer) [reply src/libraries/Microsoft.Win32.Registry/src/Microsoft.Win32.Registry.csproj:11]: cc @ericstj

**Comment by marek-safar** [comment]
> how close are you to merging https://github.com/dotnet/runtime/pull/72667? This is going to conflict.

Want to merge is ASAP (likely today)

File: src/libraries/Microsoft.Win32.Registry/src/Microsoft.Win32.Registry.csproj (hunk 1 above)
Comment (stephentoub) [reply src/libraries/Microsoft.Win32.Registry/src/Microsoft.Win32.Registry.csproj:11]: > Looks to me that this assembly actually worked on Unix before

Not really:
https://github.com/dotnet/runtime/pull/72667#discussion_r974375107

**Comment by teo-tsirpanis** [comment]
Conflicts are resolved.

**Review by ViktorHofer — APPROVED** [review]

**Comment by carlossanlop** [comment]
Are any of the CI failures concerning, @teo-tsirpanis ?

**Comment by teo-tsirpanis** [comment]
It fails with `CSC(0,0): error CS2001: (NETCORE_ENGINEERING_TELEMETRY=Build) Source file 'D:\a\_work\1\s\src\libraries\System.Private.CoreLib\src\Microsoft\Win32\SafeHandles\SafeRegistryHandle.Windows.cs' could not be found` but I removed it from the corelib project.

**Comment by marek-safar** [comment]
The error comes from this project https://github.com/dotnet/runtime/blob/db213657acc53fc48212867d5728e83d9e36a558/src/libraries/System.Diagnostics.PerformanceCounter/src/System.Diagnostics.PerformanceCounter.csproj#L61

**Comment by teo-tsirpanis** [comment]
Fixed.

**Comment by teo-tsirpanis** [comment]
Can we merge it? It will conflict with #78558.

File: src/libraries/Common/src/Interop/Windows/Advapi32/Interop.RegEnumKeyEx.cs [hunk 2]
```diff
@@ -13,10 +13,10 @@ internal static partial class Interop
     internal static partial class Advapi32
     {
         [LibraryImport(Libraries.Advapi32, EntryPoint = "RegEnumKeyExW", StringMarshalling = StringMarshalling.Utf16)]
-        internal static partial int RegEnumKeyEx(
+        internal static unsafe partial int RegEnumKeyEx(
             SafeRegistryHandle hKey,
             int dwIndex,
-            [Out] char[] lpName,
+            ref char lpName,
```
Comment (ViktorHofer) [inline src/libraries/Common/src/Interop/Windows/Advapi32/Interop.RegEnumKeyEx.cs:19]: For my own education, why did you change this from a char array to a ref char?

**Review by ViktorHofer — APPROVED** [review]

File: src/libraries/Common/src/Interop/Windows/Advapi32/Interop.RegEnumKeyEx.cs (hunk 2 above)
Comment (teo-tsirpanis) [reply src/libraries/Common/src/Interop/Windows/Advapi32/Interop.RegEnumKeyEx.cs:19]: Because the name is in a `stackalloc`ed span (could make it a `char*`, don't remember why I didn't).

**Comment by ViktorHofer** [comment]
Apparently, two tests are failing deterministically. Let me retry them once again.

**Comment by ViktorHofer** [comment]
Test failures are due to a known issue: https://github.com/dotnet/runtime/issues/78718
